### ISSUE TITLE
how to add egress value on my vlan interace

### ISSUE THREAD

**Issue by daytona675** [svinota/pyroute2#1000]
Hi Svinota,
hope you're well today.
I would like to add egress policy on my vlan interface. 
With linux cli command : ip link set myVlanInterface type vlan egress 0:6
I've parse the code and found this filter: IFLA_VLAN_EGRESS_QOS

But I don't know how to use it from ip.link('add') directive.
When I tried something like:
ip.link('add',IFLA_LINKINFO={'attrs': [['IFLA_VLAN_EGRESS_QOS', '0:6']]})

My interface was created but the vlan parameter isn't apply on my interface.
I think I've miss something.

thanks for your help :)

**Comment by svinota** [comment]
To `add` a vlan interface with egress:
```python
ipr.link(
    'add',
    kind='vlan',
    ifname=…,
    link=…,
    vlan_id=…,
    vlan_egress_qos={
        'attrs': [
            ('IFLA_VLAN_QOS_MAPPING', {'from': 0, 'to': 7})
        ]}
)
```
ref. code:
https://github.com/svinota/pyroute2/blob/823474b71a62b0d34ff0e676a6c26d38f0791d70/pyroute2/netlink/rtnl/ifinfmsg/plugins/vlan.py#L9-L28

There is no shortcut to setup egress; I'm to fix this asap.

Also — `set` doesn't work, unlike `add`; it is a bug and will be fixed this weekend.

**Comment by daytona675** [comment]
Hi svinota,
many thanks for your help! 
It's working well so I close the issue.
King regards.

**Comment by svinota** [comment]
I reopen the ticket to finalize some related tasks.

- [ ] vlan egress shortcut in requests
- [ ] vlan ingress shortcut
- [ ] check and fix link `set` with egress/ingress
- [ ] tests

**Comment by daytona675** [comment]
No problems 
Thank you again

**Comment by svinota** [comment]
Added the shortcuts:
```python
# add VLAN link
ipr.link('add', kind='vlan', ifname=ifname, …, vlan_egress_qos={'from': 0, 'to': 3})

# same format for set VLAN link
ipr.link('set', kind='vlan', index=index, …, vlan_ingress_qos={'from': 0, 'to': 4})
```

**Comment by svinota** [comment]
(will be merged into the master tomorrow)

**Comment by daytona675** [comment]
Great !
I will try monday and tell you if it s Rubinho well
King regards

Le sam. 20 août 2022 à 21:15, Peter Saveliev ***@***.***> a
écrit :

**Comment by daytona675** [comment]
Hi svinota, 
sorry for the late answer but from my side you can close the issue.
I've tested in my setup and running well.
thanks for your work !

**Comment by svinota** [comment]
Thanks for the feedback!
