### ISSUE TITLE
Lack of documentation for generic netlink features

### ISSUE THREAD

**Issue by VorpalBlade** [svinota/pyroute2#1001]
I'm interested in the ACPI events netlink features. Unfortunately I have been unable to find any documentation of this feature anywhere in [the official documentation](https://docs.pyroute2.org/). Nor do I see very little of documentation of anything outside of networking features apart from `generic.wireguard` (which is still a networking feature, but maybe using generic netlink sockets? It isn't clear).

It would be great if documentation covered all the features, at least in brief and with an example.

**Comment by svinota** [comment]
Hej Arvid!

Yep, you're right — the documentation of acpi, dquot etc is missing. Partly 'cause these are too simple features, that work only with monitoring; but anyways the docs must be updated.

Regarding ACPI:
```python
>>> from pyroute2 import AcpiEventSocket
>>> s = AcpiEventSocket()
>>> print(s.get())
({'cmd': 1, 'version': 1, 'reserved': 0, 'attrs': [('ACPI_GENL_ATTR_EVENT', {'device_class': b'ibm/hotkey', 'bus_id': b'LEN0268:00', 'type': 32768, 'data': 6336768})], 'header': {'length': 68, 'type': 27, 'flags': 0, 'sequence_number': 31704, 'pid': 0, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}},)
>>> for msg in s.get():
...     event = msg.get(('acpi_genl_attr_event', ))  # OBS! A tuple as the key to get()
...     print(event['device_class'], event['bus_id'], event['data'])
... 
b'ibm/hotkey' b'LEN0268:00' 6336768
```

I'm to update the docs asap.

**Comment by svinota** [comment]
Updated docs on beta (after the release will be available at the ordinary docs site): https://beta.pyroute2.org/event.html

The PR for that was: #1003 (there's a bit more than just docs, since I make docs testable step by step)

**Comment by svinota** [comment]
I close this ticket, but don't hesitate to reopen, or create a new one if there are issues.
