### ISSUE TITLE
[Feature Request] Process connector support

### ISSUE THREAD

**Issue by mirfatif** [svinota/pyroute2#1036]
Please add support for creating / binding socket with [`NETLINK_CONNECTOR`](https://github.com/svinota/pyroute2/blob/0.7.3/pyroute2/netlink/__init__.py#L606) family and parsing [`proc_event`](https://github.com/torvalds/linux/blob/v6.0-rc7/include/uapi/linux/cn_proc.h#L46). An incomplete implementation is available [here](https://github.com/dbrandt/proc_events)

**Comment by svinota** [comment]
Thanks, I'll take a look tonight!

**Comment by svinota** [comment]
Started to work on that. ETA by the weekend.

**Comment by mirfatif** [comment]
@svinota sorry this is unrelated.

Is it possible to make [`NetlinkSocket.get()`](https://github.com/svinota/pyroute2/blob/0.7.3/pyroute2/netlink/nlsocket.py#L831) non-blocking? E.g. in C we can close the socket from another thread or a signal handler and [`recv()`](https://www.man7.org/linux/man-pages/man2/recv.2.html) would return with `EBADF`. Or we can do [`poll()`](https://www.man7.org/linux/man-pages/man2/poll.2.html) with small timeouts before doing `recv()` in a loop which checks for a terminate condition.

Can we make `get()` return (with or without Exception) once [`NetlinkSocket.close()`](https://github.com/svinota/pyroute2/blob/0.7.3/pyroute2/netlink/nlsocket.py#L1332) is called. I `get()` dead PID events with [`TaskStats.register_mask()`](https://github.com/svinota/pyroute2/blob/0.7.3/pyroute2/netlink/taskstats/__init__.py#L147).

**Comment by svinota** [comment]
May I ask you to open a separate ticket for that? Right now `NetlinkSocket.get()` does that, but not as a part of a normal behaviour, just as a side-effect of another feature, and this definitely should be fixed. The current behaviour is more like a bug.

**Comment by svinota** [comment]
A rather basic implementation merged.

```python
from pyroute2 import ProcEventSocket

ps = ProcEventSocket()
ps.bind()
ps.control(listen=True)
while not enough:
    for event in ps.get():
        print(event)
```
