### ISSUE TITLE
0.7.4 IPRSocket.put() raises exception 'EngineThreadSafe' object has no attribute 'marshal'

### ISSUE THREAD

**Issue by jtluka** [svinota/pyroute2#1068]
I hit this with LNST code available [here](https://github.com/LNST-project/lnst/blob/master/lnst/Agent/InterfaceManager.py#L92)

Downgrading to pyroute2 0.7.3 resolves the issue.

**Comment by svinota** [comment]
To be fixed tonight

**Comment by svinota** [comment]
Pls check if it works now, and I will tag a minor release.

**Comment by jtluka** [comment]
> Pls check if it works now, and I will tag a minor release.

@svinota hey, thanks for fixing this. our github ci tests now run succesfully, check https://github.com/LNST-project/lnst/pull/281

I'll wait for you tagging the version so that our poetry installer can fetch it.

**Comment by svinota** [comment]
Expect it to be tagged this week

**Comment by svinota** [comment]
0.7.5 is tagged

**Comment by jtluka** [comment]
> 0.7.5 is tagged

Thanks, I've already tested and confirm it works.
