### ISSUE TITLE
cannot call isinstance() with IPRSocket

### ISSUE THREAD

**Issue by jtluka** [svinota/pyroute2#109]
Hi,
LNST is incompatible with the 0.3.5 version of pyroute2 (available via pip). I've came up with the following simplified reproducer,

```
>>> from pyroute2 import IPRSocket
>>> s = IPRSocket()
>>> s.bind()
>>> isinstance(s, IPRSocket)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
>>> IPRSocket
<functools.partial object at 0x7ffc4650e7e0>
>>> IPRSocket()
<pyroute2.netlink.rtnl.IPRSocket object at 0x7ffc3a2e5320>
>>> 
```

I know that this is because of introducing functools.partial code but do you have any idea, how can we fix this?

**Comment by jtluka** [comment]
Looks like following is possible, however not sure if this is correct way.

>>> from pyroute2.netlink.rtnl import IPRSocket
>>> s = IPRSocket()
>>> 
>>> isinstance(s, IPRSocket)
True

**Comment by svinota** [comment]
Yes, if you need to check the object type, you can directly import `pyroute2.netlink.rtnl.IPRSocket` — I will not change this module layout any more, so it is safe.

Partial proxy was introduced to postpone the import, thus enabling the safe base class monkey patching, as in https://github.com/svinota/pyroute2/blob/master/examples/custom_socket_base.py

**Comment by jtluka** [comment]
Ok, thanks Peet! I'm going to fix this in LNST.

**Comment by svinota** [comment]
Thank you for the patience :)
