### ISSUE TITLE
ip route replace support

### ISSUE THREAD

**Issue by brianphaley** [svinota/pyroute2#111]
Guess this is more of a feature request, but I just started taking a look at this library recently, thanks for writing it.

One thing some scripts I work on do is to call 'ip route replace...' instead of ever calling 'ip route add...' since replace will do an add if there isn't an existing entry, else change it.  It helps with having to check first, and eliminates the possibility of duplicate routes.

The flags used in this case are (NLM_F_CREATE|NLM_F_REPLACE).

My only other comment is that although this is a library, it does closely mimic what /sbin/ip does, so was a little confused why 'set' was chosen instead of 'change', but that's a nit and possibly just something the user has to manage.

**Comment by svinota** [comment]
Thanks for reporting, will be fixed asap (I'm in the middle of ipset feature, so the fix will done only tomorrow)

"set" also will not be an issue — I will add "change", it's a line of code :)

**Comment by brianphaley** [comment]
Thanks for the quick update, now I just have to find some time to start trying to use the library :)

**Comment by svinota** [comment]
Added route `change` command; `set` semantics stays intact. Documentation to be added, so not closing.

**Comment by svinota** [comment]
`change` vs. `replace` logic aligned with ip-route(8):

* `change` only changes existing routes
* `replace` changes or adds new one

documentation updated.

**Comment by svinota** [comment]
Docs published: http://docs.pyroute2.org/iproute.html#pyroute2.iproute.IPRouteMixin.route

Is it ok, can we close the issue, or it can be fixed better?
