### ISSUE TITLE
How to create XFRM interfaces

### ISSUE THREAD

**Issue by draggeta** [svinota/pyroute2#1139]
I may be missing something, but I cannot create an XFRM interface.
With iproute2 I can do:
```bash
ip link add xfrm-uplink01 type xfrm dev ens3 if_id 0x999901
```

but with ndb or iproute I get:
```python
from pyroute2 import IPRoute, NDB

ndb = NDB()
ipr = IPRoute()

ndb.interfaces.create(ifname='xfrm01', kind='xfrm').commit()
ipr.link('add', ifname='xfrm02', kind='xfrm')

# Returns an error
pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')
```

Seems like it doesn't accept the 'xfrm' kind.

**Comment by liske** [comment]
An XFRM interfaces **requires** the `xfrm_if_id` attribute (the `if_id` parameter of your iproute2 cli command).

```python
ipr.link('add', ifname='xfrm02', kind='xfrm', xfrm_if_id=0x999901)
```

**Comment by draggeta** [comment]
@liske Ah wow, thank you. It feels so stupid that I couldn't find the solution after your answer. Thank you
