### ISSUE TITLE
0.7.10 tag missing

### ISSUE THREAD

**Issue by henning-schild** [svinota/pyroute2#1153]
there seems to be a release on pypi but no tag here

**Comment by henning-schild** [comment]
also no CHANGELOG entry it seems

**Comment by svinota** [comment]
Yep, missed push. Trying to realize what to do now with that. Most probably 0.7.11 will be pushed today, as otherwise I will have to do foced push.

**Comment by svinota** [comment]
Ok, pushed both the tag and the changelog. Hope I didn't ruin the log.

**Comment by henning-schild** [comment]
Good you managed. Not sure it was the best idea to force-push, that might cause issues with distributors and the checksums they use. Better to create another "fake" release next time.
