### ISSUE TITLE
ipdb.route.RoutingTable should have __contains__

### ISSUE THREAD

**Issue by takaomag** [svinota/pyroute2#127]
Hi,

**ipdb.route.RoutingTable** has methods as if it is a dict.
Even though it does not have `__contains__` method, we can do `some_route_string in RoutingTable()` operation without Exception (since It have `__iter__` method), but the result is not intuitive.

```
>>> from ipdb import IPDB
>>> ipdb = IPDB()

>>> '10.8.0.0/22' in ipdb.routes
False
>>> '10.8.0.0/22' in ipdb.routes.keys()
True
```

Could you please implement `__contains__` against RoutingTable class ?

**Comment by svinota** [comment]
Yep, sure. Thanks for the FR, will implement asap.

**Comment by svinota** [comment]
Committed to the branch. Pls notice:

```
# Lets assume we have the route to 10.0.0.0/24 and don't have any
# specific to 172.16.0.0/24 but the default. Then:
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> ipdb.routes['10.0.0.0/24']
{'family': 2, 'dst_len': 24, 'proto': 2, 'oif': 3, 'dst': '10.0.0.0/24', 'prefsrc': '10.0.0.165', 'tos': 0, 'metrics': {}, 'flags': 0, 'src_len': 0, 'table': 254, 'type': 1, 'scope': 253}
>>> '10.0.0.0/24' in ipdb.routes
True
>>> '10.0.0.0/24' in ipdb.routes.tables[254]
True
# when you ask for non-existing route it's an equivalent to  `ip route get`:
>>> ipdb.routes['172.16.0.0/24']
{'type': 1, 'dst_len': 32, 'family': 2, 'proto': 0, 'oif': 3, 'dst': '172.16.0.0/32', 'table': 254, 'src_len': 0, 'metrics': {}, 'flags': 512, 'tos': 0, 'scope': 0, 'prefsrc': '10.0.0.165', 'gateway': '10.0.0.1', 'cacheinfo': {'rta_error': 0, 'rta_id': 0, 'rta_expires': 0, 'rta_ts': 0, 'rta_lastuse': 0, 'rta_tsage': 0, 'rta_used': 0, 'rta_clntref': 1}}
# the specific route doesn't exist:
>>> '172.16.0.0/24' in ipdb.routes
False
>>> '172.16.0.0/24' in ipdb.routes.tables[254]
False
```

**Comment by takaomag** [comment]
It works well.
> when you ask for non-existing route it's an equivalent to  `ip route get`:
> ipdb.routes['172.16.0.0/24']
> {'type': 1, 'dst_len': 32, 'family': 2, 'proto': 0, 'oif': 3, 'dst': '172.16.0.0/32', 'table': 254, 'src_len': 0, 'metrics': {}, 'flags': 512, 'tos': 0, 'scope': 0, 'prefsrc': '10.0.0.165', 'gateway': '10.0.0.1', 'cacheinfo': {'rta_error': 0, 'rta_id': 0, 'rta_expires': 0, 'rta_ts': 0, 'rta_lastuse': 0, 'rta_tsage': 0, 'rta_used': 0, 'rta_clntref': 1}}


I did not know it. It is useful.
Thanks a lot !

**Comment by svinota** [comment]
It didn't exist in 0.3.6, and it is not documented yet.

You can use not only route prefixes, but any other route specs as a key:
```
ipdb.routes[{'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.1'}]
ipdb.routes[{'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.99'}]
```
Pls refer to https://github.com/svinota/pyroute2/issues/115, in comments the syntax is described shortly, with examples.

I will document it a bit later, having enough time.

**Comment by takaomag** [comment]
That is cool interface !

**Comment by svinota** [comment]
Thanks :)
