### ISSUE TITLE
IPDB direct mode is requiring a commit to apply the changes

### ISSUE THREAD

**Issue by tsemczyszyn** [svinota/pyroute2#130]
I'm trying to use IPDB in 'direct' mode which as far as I understand should cause any commands to apply immediately without the need for commit()?

I tried the following:
```
ipdb = IPDB(mode='direct')
ipdb.create(ifname='v0p0', kind='veth', peer='v0p1')
````

If I then run the 'ip link' command I don't see the veth interfaces on my system. If I then commit in the following way:
```
ipdb.interfaces.v0p0.commit()
```

At that point the interfaces appear to be created.

**Comment by svinota** [comment]
Indeed. Thanks for reporting.

**Comment by svinota** [comment]
Should be fixed now.

**Comment by tsemczyszyn** [comment]
Thanks, its working now.
