### ISSUE TITLE
IPRoute ip.close() socket error: bad file descriptor

### ISSUE THREAD

**Issue by kim-acmehi** [svinota/pyroute2#132]
Hello,

I have a very simple example showing ip.close() causing a bad file descriptor exception.  This was isolated from a much more complicated multi-threaded program:

    import sys
    import time
	import os
	from pyroute2 import IPRoute
	from socket import AF_INET

	interfaceName = 'eth0'

	while True:
		ip = IPRoute();
		dev = ip.link_lookup(ifname=interfaceName)[0]
	#	addr = ip.get_addr(family=AF_INET,index=dev)
	#	ipv4Addr = ([x.get_attr('IFA_ADDRESS') for x in addr])[0]
		ip.close()
		print "dev:", dev
	#	print "IP:", ipv4Addr
	#	except BaseException, e:
	#		print "Caught exception", e.args
	#		sys.exit(1)
		time.sleep(1)

I can get 9 or 10 iterations of this until an exception occurs:

    dev: 5
    dev: 5
    dev: 5
    dev: 5
    dev: 5
    dev: 5
    dev: 5
    dev: 5
    dev: 5
    Traceback (most recent call last):
      File "./iproute_test.py", line 16, in <module>
        dev = ip.link_lookup(ifname=interfaceName)[0]
      File "/usr/lib/python2.7/site-packages/pyroute2/iproute.py", line 391, in link_lookup
        [i for i in self.get_links() if 'attrs' in i] if
      File "/usr/lib/python2.7/site-packages/pyroute2/iproute.py", line 220, in get_links
        result.extend(self.nlm_request(msg, RTM_GETLINK, msg_flags))
      File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 791, in nlm_request
        ret = self.get(msg_seq=msg_seq, terminate=terminate)
      File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 708, in get
        data = self.recv_plugin(bufsize)
      File "/usr/lib/python2.7/site-packages/pyroute2/netlink/rtnl/__init__.py", line 269, in proxy_recv
        data = self._recv(bufsize, flags)
    socket.error: [Errno 9] Bad file descriptor

If the ip.close() line is commented out this will run indefinitely with the process opening up to about 12 or so netlink sockets and then closing them all when the GC runs.

I am currently working around this problem by not calling ip.close() which is contrary to many of the tests and examples provided.  It seems like the file descriptor is being closed by ip.close() and later the GC tries to close the socket and either gets the bad file descriptor exception or (worse) closes the wrong fd and causes another thread to discover its fd suddenly closed.

# Version details
Python 2.7.5
pyroute2 0.3.7
CentOS 7 x86_64

**Comment by svinota** [comment]
Related issue: https://github.com/svinota/pyroute2/issues/126

**Comment by svinota** [comment]
Thanks for reporting!

Fixing it.

**Comment by svinota** [comment]
Python2-specific.

Related issue: https://bugs.python.org/issue808164

**Comment by svinota** [comment]
Looks to be fixed, but tests are still running.

**Comment by svinota** [comment]
Regression tests are passed.

New test module is added after your code: https://github.com/svinota/pyroute2/blob/master/tests/test_stress.py

Please check, if the master branch is working for you now. Thanks!

**Comment by kim-acmehi** [comment]
I tested with the simple failure example, the original program and the same with refactored use of the IPRoute object and all are working fine as expected.  It seems your fix is good.  Thanks for the very quick response!

**Comment by svinota** [comment]
Thanks for the report — the issue was pretty serious.

**Comment by kim-acmehi** [comment]
How long has this problem been around?  Was there a release that this would have worked without this problem?

**Comment by svinota** [comment]
This particular issue was introduced about 10 days ago with that commit: https://github.com/svinota/pyroute2/commit/b3b18b9cb880a3c321b4ad45fcc89c0738d9dd01

so 0.3.7 has the issue; 0.3.6 — has not. The next, 0.3.8, will be rolled out with all the fixes in approx. two weeks.

Actually, there was not one issue, but a whole bunch of related issues in different forms. Now I believe it's mostly over for both, `IPRoute` and `IPDB` — I managed to fix also issues with python2 gc (https://github.com/svinota/pyroute2/commit/77e4c9eb7c8ef9862e6bf83d8085526dd75451f7), and the refactoring also fixed one of the eventlet integration issues (https://github.com/svinota/pyroute2/pull/94) much better, than it was done before.

**Comment by kim-acmehi** [comment]
Thanks.  I ask because was using 0.3.3 and needed the filter by index feature introduced in 0.3.5. I jumped too far ahead I guess but at least we were able to get a good stress test element and allow you to refactor the foundation.  I may roll back to 0.3.6 if I see any more problems with 0.3.7.  I will let you know.

**Comment by svinota** [comment]
I'm sorry about the issue in 0.3.7 — I try to keep versions not less stable than previous ones, but shit happens. At least, with the recent changes this issue is covered by tests, so will not repeat ever.

**Comment by svinota** [comment]
Probably, it would be better even to release 0.3.8 as errata asap.

**Comment by svinota** [comment]
So be it. Tomorrow one more cosmetic issue (#133) will be fixed and 0.3.8 will be rolled out to pypi.

**Comment by svinota** [comment]
0.3.8 with the fix is rolled out:

https://github.com/svinota/pyroute2/releases/tag/0.3.8

Also available on pypi: https://pypi.python.org/pypi/pyroute2

If the issue will reappear, reopen the ticket please. Thanks!
