### ISSUE TITLE
Problems in the result of IW.scan()

### ISSUE THREAD

**Issue by creasyw** [svinota/pyroute2#134]
Hi Peter,

This is Qiong. After our last email, I kept debugging the `iw.scan()` and found more questions. For the completeness of the issue report, I list all of my questions along with my temporary solutions here.

The part of scanning result that I would like to use is about `NL80211_ATTR_BSS`, but it reveals like:
```
......
['NL80211_ATTR_BSS',
  {'attrs': [['NL80211_BSS_BSSID', '6c:70:9f:d9:a7:c6'],
        ['NL80211_BSS_TSF', 1210658410574],
        ['UNDECODED', 'e2:00:06:00:00:0b:65:65:72:6f:20:62:61:63:6b:75:70:01:08:82:84:8b:96:24:30:48:6c:03:01:06:05:04:00:03:01:00:07:06:55:53:20:01:0b:1e:20:01:00:23:02:19:00:2a:01:04:30:14:01:00:00:0f:ac:04:01:00:00:0f:ac:04:01:00:00:0f:ac:02:00:00:32:04:0c:12:18:60:2d:1a:ad:19:17:ff:ff:ff:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:3d:16:06:08:15:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:7f:08:00:00:00:00:00:00:00:40:dd:0b:00:17:f2:01:00:01:01:00:00:00:07:dd:07:00:03:93:01:78:03:20:dd:0e:00:17:f2:07:00:01:01:06:6c:70:9f:d9:a7:c7:dd:09:00:10:18:02:07:00:1c:00:00:dd:18:00:50:f2:02:01:01:80:00:03:a4:00:00:27:a4:00:00:42:43:5e:00:62:32:2f:00:46:05:02:00:01:00:00'],
                        ['UNKNOWN',
                         '0c:00:0d:00:4e:50:dd:e0:19:01:00:00'],
                        ['NL80211_BSS_CHAN_WIDTH', 1701120768],
                        ['NL80211_BSS_BEACON_INTERVAL', 100],
                        ['NL80211_BSS_CAPABILITY', 17],
                        ['NL80211_BSS_FREQUENCY', 2437],
                        ['NL80211_BSS_BEACON_TSF', 2814784126844928],
                        ['NL80211_BSS_BEACON_IES', '23:00:00:00'],
                        ['NL80211_BSS_SIGNAL_MBM', 4294962896]]}]],
......
```

Compared with the output of `iw`, the `'UNDECODED'` part should be `NL80211_BSS_INFORMATION_ELEMENTS`, which contains quite a few entries. Among the missing items, I would like to know the `SSID` first, so I [comment out the snippet that has `TypeError`](https://github.com/creasyw/pyroute2/commit/41b6197ce94df6a695f285f831e763071459bee7).

The next part is the `UNKNOWN`, which will reveal the correct names of attributes when I add the other two entires by comparing the `nla_map` with [linux/nl80211.h](http://lxr.free-electrons.com/source/include/uapi/linux/nl80211.h#L3304)

[The changed code](https://github.com/creasyw/pyroute2/blob/feature/iwfunction/pyroute2/netlink/nl80211/__init__.py#L469) has following effect:
```
......
['NL80211_ATTR_BSS',
             {'attrs': [['NL80211_BSS_BSSID', 'f6:ed:a5:62:c5:40'],
                        ['NL80211_BSS_TSF', 4308141576451],
                        ['NL80211_BSS_INFORMATION_ELEMENTS',
                         {'SSID': b'xfinitywifi'}],
                        ['NL80211_BSS_MAX', '03:91:3f:11:eb:03:00:00'],
                        ['NL80211_BSS_CHAN_WIDTH', 1719143168],
                        ['NL80211_BSS_BEACON_INTERVAL', 100],
                        ['NL80211_BSS_CAPABILITY', 1025],
                        ['NL80211_BSS_FREQUENCY', 2437],
                        ['NL80211_BSS_PRESP_DATA', '00:00:00:00'],
                        ['NL80211_BSS_BEACON_IES', '25:00:00:00'],
                        ['NL80211_BSS_SIGNAL_MBM', 4294959996]]}]],
......
```
But it still does not have the flag of `NL80211_BSS_STATUS` and the signal strength `NL80211_BSS_UNSPEC`. These two corresponding attributes are in the output of `iw`, but I do not know how to find them here...

Please let me know if there is a way to solve it.

Thanks,
Qiong

**Comment by svinota** [comment]
Yep, there is a way. I would try to play with iw code and traces.

The usage of `NL80211_BSS_UNSPEC` looks really strange. If `NL80211_BSS_UNSPEC` is used, it will be the first time across all netlink families when one uses unspec NLA type. So, probably there is an issue with whole NLA structure in these messages. I will try to take a look at raw packets.

**Comment by ryan3thompson** [comment]
We came up with a solution to solve the TypeErrors that Qiong was getting (Python2 vs Python3 byte issues), as well as decoding more of the Information Elements. @creasyw should be able to put in a pull request very soon with some of these improvements and more IBSS functionality.

**Comment by svinota** [comment]
Great, thanks. Meanwhile I'm preparing for the OpenStack summit, but shortly I'll be back and active again, so will test/integrate the code.

**Comment by creasyw** [comment]
Hi Peter, we still cannot decode the `NL80211_BSS_STATUS` out of `NL80211_ATTR_BSS`. Is there any luck in your end?

**Comment by svinota** [comment]
Uh, I just forgot that issue, excuse me for so long silence. Let me take a look tomorrow, we'll see what I can do.

**Comment by svinota** [comment]
I can not get it neither. How to reproduce the situation, when I'm supposed to get `NL80211_BSS_STATUS`? Is it a scan request? What the device setup should be?

**Comment by creasyw** [comment]
This is a flag which is included in the stations that are meshed up together. It does not have specific parameters to evoke, but comes with regular scan results when the I scan a station interface. The sample output looks like
```
root@eero-vega:/# iw sta scan | grep connect_point -B8
BSS 14:22:db:00:aa:28(on sta) -- associated
        TSF: 70730721558 usec (0d, 19:38:50)
        freq: 5785
        beacon interval: 100 TUs
        capability: ESS (0x0001)
        signal: -53.00 dBm
        last seen: 90 ms ago
        Information elements from Probe Response frame:
        SSID: connect_point
--
BSS 14:22:db:00:aa:27(on sta)
        TSF: 70735113324 usec (0d, 19:38:55)
        freq: 5180
        beacon interval: 100 TUs
        capability: ESS ShortPreamble (0x0021)
        signal: -20.00 dBm
        last seen: 2310 ms ago
        Information elements from Probe Response frame:
        SSID: connect_point
```
In the `nl80211.h`, the definition is:
```c
/**
 * enum nl80211_bss_status - BSS "status"
 * @NL80211_BSS_STATUS_AUTHENTICATED: Authenticated with this BSS.
 *  Note that this is no longer used since cfg80211 no longer
 *  keeps track of whether or not authentication was done with
 *  a given BSS.
 * @NL80211_BSS_STATUS_ASSOCIATED: Associated with this BSS.
 * @NL80211_BSS_STATUS_IBSS_JOINED: Joined to this IBSS.
 *
 * The BSS status is a BSS attribute in scan dumps, which
 * indicates the status the interface has wrt. this BSS.
 */
enum nl80211_bss_status {
    NL80211_BSS_STATUS_AUTHENTICATED,
    NL80211_BSS_STATUS_ASSOCIATED,
    NL80211_BSS_STATUS_IBSS_JOINED,
};
```

Besides, the `NL80211_BSS_MAX` might not be included in the decoded items in the `NL80211_ATTR_BSS`. Because in the `iw/scan.c`, it has
```c
static struct nla_policy bss_policy[NL80211_BSS_MAX + 1] = {
        [NL80211_BSS_TSF] = { .type = NLA_U64 },
        [NL80211_BSS_FREQUENCY] = { .type = NLA_U32 },
        [NL80211_BSS_BSSID] = { },
        [NL80211_BSS_BEACON_INTERVAL] = { .type = NLA_U16 },
        [NL80211_BSS_CAPABILITY] = { .type = NLA_U16 },
        [NL80211_BSS_INFORMATION_ELEMENTS] = { },
        [NL80211_BSS_SIGNAL_MBM] = { .type = NLA_U32 },
        [NL80211_BSS_SIGNAL_UNSPEC] = { .type = NLA_U8 },
        [NL80211_BSS_STATUS] = { .type = NLA_U32 },
        [NL80211_BSS_SEEN_MS_AGO] = { .type = NLA_U32 },
        [NL80211_BSS_BEACON_IES] = { },
    };
```
and is defined at `nl80211.h` as `NL80211_BSS_MAX = __NL80211_BSS_AFTER_LAST - 1`. In turn, I cannot find other information for this `__NL80211_BSS_AFTER_LAST`.
