### ISSUE TITLE
How to start a multiprocessing.process in a netns

### ISSUE THREAD

**Issue by geekscrapy** [svinota/pyroute2#136]
Basically, I'd like to either run a full process in a netns or be able to issue commands from within the netns.

**Comment by svinota** [comment]
Popen-like
-------------

To run a separate process within a netns: `NSPopen`

http://docs.pyroute2.org/netns.html#nspopen

Set netns for the script
----------------------------
To run a Python code within a netns:

1. Using `multiprocessing` start a process
2. Set netns in the child:
```
from pyroute2 import netns
netns.setns('…')
```
http://docs.pyroute2.org/netns.html#pyroute2.netns.setns

**Comment by geekscrapy** [comment]
Thanks, I have no idea why I couldn't find that. Apologies!!

**Comment by svinota** [comment]
If there will be issues with that functionality, pls don't hesitate to file bugs — the feedback is important to keep it working.
