### ISSUE TITLE
Add ip route get support

### ISSUE THREAD

**Issue by jaderhs** [svinota/pyroute2#154]
Allow probing route for a specific destination. e.g.:
```sh
$ ip route get 1.2.3.4
```
implemented as something like:

```python
from pyroute2 import IPRoute

iproute = IPRoute()
iproute.ip("get", dst="1.2.3.4")
```

**Comment by svinota** [comment]
```
from pyroute2 import IPRoute

ipr = IPRoute()
ipr.get_routes(dst='8.8.8.8')
ipr.close()
```

or

```
from pyroute2 import IPDB
ipdb = IPDB()
ipdb.routes[spec]
```
If `spec` points to an existing route, the route record will be returned, otherwise will be returned the same as for `ip route get`.

The `spec` can be a string (prefix) or a dict, e.g.:
```
ipdb.routes['8.8.8.8']
ipdb.routes[{'dst': '172.16.0.0/24', 'oif': 2}]
```
the latter can be used when there are several routes with the same prefix.

**Comment by svinota** [comment]
May I close the issue?

**Comment by jaderhs** [comment]
Hello. Thanks for the answer. Yes, you may close it.

**Comment by svinota** [comment]
Thanks!
