### ISSUE TITLE
flush rules

### ISSUE THREAD

**Issue by tomislacker** [svinota/pyroute2#158]
Similar to #40 but for rules instead.  Something like `ip.rule("flush")`

```python
from pyroute2 import IPRoute
ip = IPRoute()
ip.rule("flush")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: rule() takes at least 3 arguments (2 given)
```

**Comment by svinota** [comment]
There is a set of default rules:
```
$ ip rule
0:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 
```

By flushing these rules, one can get in troubles :)

The question is what to do then. I would do it in the same way as with routes (and addresses, the latter is to be committed) — when one can specify parameters to be tested, so only matched objects will be deleted:

```
ipr.flush_routes(table=100)
ipr.flush_addr(index=2)
ipr.flush_addr(label='eth0', broadcast='172.16.0.255')
```

so to say, it could be like that (not implemented, just a sample):
```
# remove only IPv4 rules with priority above 0 and below 32500:
ipr.flush_rules(family=socket.AF_INET, priority=lambda x: 0 < x < 32500)

# following is still valid, but extremely dangerous as it removes ALL rules in the system:
ipr.flush_rules()
```

does it sound OK?

if yes, I would do.

**Comment by tomislacker** [comment]
Wow, thanks for the quick follow-up.

Your proposed solution would certainly be helpful assuming you can flush all rules such as with `ipr.flush_rules()` *(no arguments)*

When providing matches such as your example, would it address the case of having two identical rules?  Example:

```sh
# Status quo (pre-experiment)
$ ip rule
0:      from all lookup local 
32766:  from all lookup main 
32767:  from all lookup default 

# Add two identical rules
$ ip rule add pref 100 lookup main
$ ip rule add pref 100 lookup main

# Delete the rules pref 100
$ ip rule del pref 100

# One rule still remains
$ ip rule
0:      from all lookup local 
100:    from all lookup main 
32766:  from all lookup main 
32767:  from all lookup default
```

**Comment by svinota** [comment]
If the implementation will follow the same logic as in `flush_routes()` and `flush_addr()`, then **all** matching rules will be deleted, not only the first one.

And I would do so, since to delete one rule one can use `ipr.rule('del', <<spec>>)`.

**Comment by tomislacker** [comment]
That sounds awesome

**Comment by svinota** [comment]
Ok, will be done asap.

**Comment by svinota** [comment]
But one more question: is it OK, if the `rule()` will use the same scheme as `route()` and `addr()` — no positional parameters, only keyword ones?

So no more `ipr.rule('add', 10, 32000, …)`,
only `ipr.rule('add', table=10, priority=32000, …)` ?

**Comment by tomislacker** [comment]
For sure, that sounds perfectly fine.

**Comment by svinota** [comment]
Should work now, more docs to be written later. Please check, if it works for you.

Please be careful as by default it works on **all** the rules of **all** the families. A bit dangerous.

To check, if it will to what you want, you can run `get_rules()` first and if it is OK, then run `flush_rules()` with the same arguments.

**Comment by tomislacker** [comment]
You, sir, are awesome! I'll be able to validate it in about 6-8hrs.

**Comment by tomislacker** [comment]
@svinota Works great!  Thank you so very much.

**Comment by svinota** [comment]
You're welcome!
