### ISSUE TITLE
NSPopen: Working with piped .stdout does not work

### ISSUE THREAD

**Issue by sklp3** [svinota/pyroute2#160]
Hi,

Trying to read from NSPopen object's stdout attribute raises "ValueError: I/O operation on closed file". The Following script works with subprocess.Popen, but not with NSPopen:

```python
#!/usr/bin/env python
import subprocess
import pyroute2
import pyroute2.netns.nslink
import pyroute2.netns.process.proxy


#p = subprocess.Popen(["/usr/sbin/openvpn"], stdout = subprocess.PIPE, stderr = subprocess.STDOUT)

n = pyroute2.netns.nslink.NetNS("test")
p = pyroute2.netns.process.proxy.NSPopen("test", ["/usr/sbin/openvpn"], stdout = subprocess.PIPE, stderr = subprocess.STDOUT)

with p.stdout:
    for line in iter(p.stdout.readline, b''):
        print line

p.wait()

print "DONE"

n.close()
n.remove()
```

**Comment by svinota** [comment]
Thanks, fixing

**Comment by svinota** [comment]
Excuse me for the delay, I was in a trip. Now it should be fixed in some way. I'm not closing the issue though, since some refactoring is needed (now it's just a draft implementation) as well as the test coverage.

**Comment by sim590** [comment]
Related to this issue and your fix, I think there's still something missing. When trying to get the file descriptor's flags in order to set them to non blocking read as I'd do after a normal `Popen()` call.:
```python
import subprocess
import pyroute2
import pyroute2.netns.nslink
import pyroute2.netns.process.proxy
import fcntl

pyroute2.netns.setns("test")
proc = NSPopen('test', ['cat'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
fd = proc.stdout.fileno()
flags = fcntl.fcntl(fd, fcntl.F_GETFL)
```
I get this:
```
OSError: [Errno 9] Bad file descriptor
```
While doing so with `Popen` object works.

**Comment by svinota** [comment]
Yep, thanks!

**Comment by svinota** [comment]
Nope.

The NSPopen operates not only in a separate netns, but in a separate process. So one can not call fcntl directly — it must be called in the netns server process.

```
[ script process ] <-----> [ netns server process] <-----> [ Popen child process ]
+                     +                                                          +
|     main netns      |                    target netns                          |
+---------------------+----------------------------------------------------------+
```

The main issue is not how to implement that. But how to provide it in terms of API…

**Comment by svinota** [comment]
Actually, there is a solution:

1. setns()
2. Popen()
3. fcntl()

But it means that the process will not be able to continue in the main netns — the `setns()` operation can not be undone. So if you need to run a process in the main netns and sometimes spawn child processes in other netns, there should be some specific API implemented to cover your usecase.

One possible way would be to provide file operations directly on NSPopen() «file» attributes, like `proc.stdout.fcntl()`. If it is ok for you, I can try to do so.

**Comment by svinota** [comment]
Several notes, as the patch is provided:

1. `setns` sets netns for the whole process, you do not need to use NSPopen after it, simple Popen will be enough.
2. if you need to keep the process in the main netns, while running children in some other netns, you can use NSPopen then

If NSPopen object has any of stderr, stdin, stdout objects not None, they have all the file methods as well as fcntl methods. It is possible to run like that:

```
proc = NSPopen('test', ['cat'], stdout=subprocess.PIPE)
flags = proc.stdout.fcntl(fcntl.F_GETFL)
```

I'm not closing the bug since it has to be documented still.

**Comment by sim590** [comment]
Awesome! This is exactly what I wanted to do actually, i.e keep the main process in a different netns of childs' netns and change childs' pipe file descriptors falgs for non blocking read. Thank you addressing the issue so quickly! I've tested it and it does work now.

**Comment by svinota** [comment]
Yeah :) That's good. Docs on the site are updated as well: http://docs.pyroute2.org/netns.html#nspopen

**Comment by svinota** [comment]
Re-opening the issue to keep it on-check for some time.

I'm going to send back file objects (together with file descriptors) from the proxy process to the main process, thus all file operations will be done only in the main context. This will simplify the logic and will reduce amount of data sent between the proxy and the main processes.

But it has to be compatible with what we have now — so if you will notice any behaviour change in the NSPopen on the master branch this or the next week, pls, do not hesitate to report it here. Thanks in advance.

**Comment by svinota** [comment]
No, dismiss. It looks like one can not send FDs between netns — it just doesn't work. Unfortunately. So `NSPopen` still continues with what we have up to now.
