### ISSUE TITLE
Create route with metric?

### ISSUE THREAD

**Issue by tomislacker** [svinota/pyroute2#170]
From [the documentation](http://docs.pyroute2.org/iproute.html) and groking through the code, there does not seem to be a way to add routes with a given metric.

### Desired Output

```
default via 192.168.1.1 dev eth0  metric 100
default via 172.16.0.1 dev eth1  metric 200
```

### Desired Syntax

```python
from pyroute2.iproute import IPRoute

ip = IPRoute()
ip.route('add',
         table=253,
         dst='0.0.0.0',
         gateway='192.168.1.1',
         family=AF_INET,
         metric=100
         )
ip.route('add',
         table=253,
         dst='0.0.0.0',
         gateway='172.16.0.1',
         family=AF_INET,
         metric=200
         )
```

**Comment by tomislacker** [comment]
Nevermind...  I was using the `metric` parameter instead of `priority` like I *should* have been.

**Comment by svinota** [comment]
I'm reopening the issue to document the metrics. Since there is a way to add routes with metrics, but it is not documented.

**Comment by svinota** [comment]
Docs are updated:

IPRoute: http://docs.pyroute2.org/iproute.html#pyroute2.iproute.IPRouteMixin.route
IPDB: http://docs.pyroute2.org/ipdb.html#routing-management

**Comment by tomislacker** [comment]
Thanks sir!
