### ISSUE TITLE
Create multihop default gateways

### ISSUE THREAD

**Issue by tomislacker** [svinota/pyroute2#171]
Based on the documentation & grokking through the code, it doesn't seem possible to make a round-robin default gateway.  Example:

```sh
$ ip r show table default
default  proto static 
        nexthop via 222.111.222.1  dev eth0 weight 1
        nexthop via 111.222.111.2  dev eth1 weight 3
```

- If this doesn't exist, how difficult would it be to implement? *(Admittedly, I'm not sure how I'd go about it)*
- If this does already exist, could [the docs](http://docs.pyroute2.org/) be updated to include the usage?

**Comment by tomislacker** [comment]
For what it's worth, when you have two hops, you can find two 16-byte segments that seem to describe the uplinks:

- Hop 1: `10 00 00 00 02 00 00 00 08 00 05 00 d0 4a 27 69`
- Hop 2: `10 00 00 02 03 00 00 00 08 00 05 00 46 11 0b 01`

So far, I can say for certain that:

1. 4th byte seems to be somewhat related to the preference...
1. 5th byte is the `ifindex`
1. Last 4 bytes are the IPv4 address of the hop

I'll be spending some time later today or tomorrow trying to decode more & reading into the kernel source.

**Comment by svinota** [comment]
No, it is not implemented yet. Will be done soon.

**Comment by svinota** [comment]
Nexthop msg are supported — yet only for decoding.

NH messages are represented as array inside NLA, but a bit specific array, and the issue is that it is not so easy to make a generic solution that would work with all NLA array cases — I would not like to have individual array-specific routines in different message classes.

But it's doable anyway, decoding is done and encoding will be delivered tomorrow.

Still are not implemented `RTA_VIA` and `RTA_FLOW`, but it also will be done soon.

**Comment by svinota** [comment]
Encoding from raw NLA notation done, see the syntax in the test code (1026a690d6690ed8b87b7a08192e2e680c08ea5b).

Next will be helper and docs update.

**Comment by svinota** [comment]
Multipath management, yet with gateway option only:

IPDB: http://docs.pyroute2.org/ipdb.html#routing-management
IPRoute: http://docs.pyroute2.org/iproute.html#pyroute2.iproute.IPRouteMixin.route

Support for RTA_VIA and RTA_FLOW will be done next week, or you can try to play with it yourself. On this week there is an important task about MPLS routing support.

**Comment by svinota** [comment]
Does it work, may I close the bug?

**Comment by tomislacker** [comment]
@svinota sorry for never responding on this.  I think we can probably close it.  The only reason I even ended up coming back to this issue is because I was going to make a new issue to inquire if you wanted to update the documentation to deprecate this functionality.  As of the merge of [kill_rtcache](https://git.kernel.org/cgit/linux/kernel/git/davem/net.git/commit/?id=5e9965c15ba88319500284e590733f4a4629a288) into the kernel, and it's release in ~3.6, weighted default routes no longer work.  The new recommended implementation of weighted default routes is similar to [this](http://blog.khax.net/2009/12/01/multi-gateway-balancing-with-iptables/).

**Comment by svinota** [comment]
Ok, thanks. Will update docs too.

**Comment by tomislacker** [comment]
Sounds good.  The *[proprietary]* project I'm working on currently is to create a daemon for a [CPE](https://en.wikipedia.org/wiki/Customer-premises_equipment) product that handles multi-WAN setups in light of the route cache removal and is actually what led me to pyroute2 in the first place.  Once I get through the project, I intend to make an OSS example that I can publish.  I'll let you know if/when I get to that point in case you're interested in also linking to that.

**Comment by svinota** [comment]
Yep, sure. Thanks :)

**Comment by svinota** [comment]
Updated. Thanks again.
