### ISSUE TITLE
master attribute disappears from bridge port interface in ipdb if bridge is removed

### ISSUE THREAD

**Issue by jimfunk** [svinota/pyroute2#175]
If a bridge with ports is removed, the master attribute on the port interfaces disappears completely and can no longer be retrieved or set. This was observed in 0.3.11.

Here is a script that replicates the behaviour:

    import pyroute2
    
    ipdb = pyroute2.IPDB()
    
    try:
        testbr = ipdb.create(kind='bridge', ifname='testbr')
        testbr.commit()
    
        testdummy = ipdb.create(kind='dummy', ifname='testdummy')
        testdummy.master = testbr.index
        testdummy.commit()
        print(testdummy.master)
    
        testbr.remove().commit()
    
        testdummy = ipdb.interfaces.testdummy
        print(testdummy.master)
    
    finally:
        ipdb.release()

Expected behaviour: testdummy.master should be None

Actual behaviour: master attribute removed entirely. If set, it simply creates a new string and does not actually set the master

**Comment by svinota** [comment]
Definitely a bug. Thanks a lot, will be fixed today.

**Comment by svinota** [comment]
Should be fixed now.
