### ISSUE TITLE
Incorrect call to RTM_GETROUTE when specifying destination

### ISSUE THREAD

**Issue by kostko** [svinota/pyroute2#184]
Currently, when you try to call `IPRoute.get_routes` with a `dst` argument, this results in an incorrect netlink call as the `rule` method is used which transforms `dst` into `FRA_DST` (format `ipaddr`) instead of the correct `RTA_DST` (format `target`). The result is that the call fails with the kernel returning an error "Operation not supported".

A workaround is to use:
```python
iproute.route((rtnl.RTM_GETROUTE, netlink.NLM_F_REQUEST), dst='8.8.8.8')
```

**Comment by svinota** [comment]
It was really stupid bug. Thanks :)

Should be fixed now, pls check.

**Comment by kostko** [comment]
I can confirm that it works now, thanks!

**Comment by svinota** [comment]
Thousand thanks for the report. Don't know, how I missed that — and it passed the tests :) But now it's covered too.
