### ISSUE TITLE
[Docs] Explain filter flags for IP/subnets

### ISSUE THREAD

**Issue by tomislacker** [svinota/pyroute2#185]
The [`IPRouteMixin.tc()` method](../blob/84f99fbbce049517300a08c0389bf27765e1e4f6/pyroute2/iproute.py#L777) has good documentation for most components but is a bit lacking on the bitwise math necessary to create a valid filter.  For example, the following snippet:

> ```py
> # two filters: one to load packets into 1:10 and the
> # second to 1:20
> ip.tc("add-filter", "u32", eth0,
>       parent=0x10000,
>       prio=10,
>       protocol=socket.AF_INET,
>       target=0x10010,
>       keys=["0x0006/0x00ff+8", "0x0000/0xffc0+2"])
> ip.tc("add-filter", "u32", eth0,
>       parent=0x10000,
>       prio=10,
>       protocol=socket.AF_INET,
>       target=0x10020,
>       keys=["0x5/0xf+0", "0x10/0xff+33"])
> ```

It may not be clear to most users how to compose the `keys` argument or even what the example `keys` arguments are describing.

**Comment by svinota** [comment]
True. Will be done.

**Comment by tomislacker** [comment]
@svinota I've got some documentation at least for src & dst addresses that I can contribute tomorrow

**Comment by svinota** [comment]
Wow. That's cool, thanks.

**Comment by tomislacker** [comment]
Here's an example using [drkjam/netaddr](https://github.com/drkjam/netaddr) for ease of explanation and because I'm writing a class that utilities both libraries in concert to do something similar to my below example.

```python
###########################################################################
# The following example will filter traffic on eth0 and send traffic from #
# network 192.168.0.0/24 to handle 1:20 and 172.16.0.0/26 to handle 1:30  #
###########################################################################
from netaddr import IPNetwork
from pyroute2 import IPRoute

####################
# Setup Parameters #
####################
iface_name = 'eth0'

network1 = '192.168.0.0/24'
network2 = '172.16.0.0/26'

parent = 0x10000
handle1 = 0x20
handle2 = 0x30

TC_FILTER_OFFSET_SRCNET = 12
TC_FILTER_OFFSET_DSTNET = 16

#################
# Pre-Execution #
#################
ip = IPRoute()

iface_index = ip.link_lookup(ifname=iface_name)[0]
handle1 += parent
handle2 += parent

lan1 = IPNetwork(network1)
lan2 = IPNetwork(network2)

filter_key_src = "{network}/{mask}+{offset}".format(
    network=hex(lan1.network),
    mask=hex(lan1.netmask),
    offset=TC_FILTER_OFFSET_SRCNET)

filter_key_dst = "{network}/{mask}+{offset}".format(
    network=hex(lan2.network),
    mask=hex(lan2.netmask),
    offset=TC_FILTER_OFFSET_DSTNET)

#############
# Execution #
#############
ip.tc("add-filter", "u32", iface_index,
    parent=parent,
    prio=10,
    protocol=socket.AF_INET,
    target=handle1,
    keys=[filter_key_src])

ip.tc("add-filter", "u32", iface_index,
    parent=parent,
    prio=10,
    protocol=socket.AF_INET,
    target=handle2,
    keys=[filter_key_dst])
```

I think at minimum having a description for what headers are being compared in your example would be helpful.  My case of needing the offsets of src/dst addresses may actually be in the minority for all I know.
