### ISSUE TITLE
NetNS leaks open unix sockets until the open file limit is reached

### ISSUE THREAD

**Issue by nacx** [svinota/pyroute2#194]
This is possibly related to #167, but this issue appears version 0.3.14 and also in 0.3.4, where NSPopen still didn't exist, so I think it is ok to report this particular case. It can be easily reproduced by running the following script:

```python
import time
from pyroute2 import NetNS
from pyroute2 import netns as netnsmod

i = 0
while True:
    nsid = 'testns_%s' % i
    ns = NetNS(nsid)
    time.sleep(5)
    ns.close()
    netnsmod.remove(nsid)
    time.sleep(70)  # Intentionally big to let the namespace resources be properly closed
    i = i + 1
```

Looking at the open unix sockets for the process one can see the open unix sockets (I assume they correspond to the communication channel with the namespace server):

```bash
$ watch -n 1 "ss -p | egrep 'Netid|14381'"
Netid  State      Recv-Q Send-Q   Local Address:Port       Peer Address:Port
u_str  ESTAB      0      0                    * 1142354               * 1142353 users:(("python",14386,8),("python",14381,8))
u_str  ESTAB      0      0                    * 1142352               * 1142351 users:(("python",14386,6),("python",14381,6))
u_str  ESTAB      0      0                    * 1142353               * 1142354 users:(("python",14386,7),("python",14381,7))
u_str  ESTAB      0      0                    * 1142351               * 1142352 users:(("python",14386,5),("python",14381,5))
...
```

During the first 5 seconds sleep, before closing the namespace, the unix sockets appear open and connected (both ends of the socket are shown), but after the namespace is closed and removed, during the second wait, the unix sockets are still alive but the output only shows one extreme of the socket (it is actually disconnected, but still alive).

Those sockets are leaked and never closed, and each iteration creates new sockets when each new namespace is created. The program will eventually start failing with `Too many open files` errors, which makes it a blocker issue when it comes to use the network namespace support in production.

**Comment by svinota** [comment]
Thanks for reporting and for details, fixing

**Comment by svinota** [comment]
The root cause discovered. Sorry for such a stupid bug. The first fix (not final) will be pushed in one hour, but it leaves an issue with cleanup after Ctrl-C. The final fix will be not later than tomorrow.

**Comment by svinota** [comment]
If you don't care about the Ctrl-C cleanup, you can already try the code.

**Comment by svinota** [comment]
Fixed Ctrl-C exit and added a testcase.

Please, check, if it works for you.

Thanks again.

**Comment by nacx** [comment]
Thanks for the quick fix! I won't be able to test it until Wednesday, but I'll try it out and give feedback by then.

**Comment by nacx** [comment]
Thanks for the quick fix and the release. I've been able to verify it and confirm that the issue is gone. Thanks!

**Comment by tomislacker** [comment]
@svinota since 752afccf394c9c7e64cdb53f718657e2e630a981 affects the `NetlinkMixin`, does this fix also possibly repair a similar issue when using `IPRoute`?

```
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/rtnl/iprsocket.py", line 63, in __init__
    super(IPRSocketMixin, self).__init__(NETLINK_ROUTE, fileno=fileno)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 305, in __init__
    self._ctrl_read, self._ctrl_write = os.pipe()
OSError: [Errno 24] Too many open files
```

My application I've composed so far runs into that failure after running for a bit.  I'm using an `IPDB` callback to assess each WAN uplink *(by using a new `IPRoute` instance on each)* by checking carrier, link status, and bound addresses.

**Comment by svinota** [comment]
Let me check.

**Comment by svinota** [comment]
Strange. Do you execute `close()` on `IPRoute` instances?

**Comment by tomislacker** [comment]
On shutdown but not after each use.  Is that what I should be doing to avoid this?

**Comment by svinota** [comment]
Each `IPRoute` instance opens not one, but several FDs. If it is not the case to keep `IPRoute` as a singleton, I would advise to close `IPRoute` instances when they're not required anymore.

**Comment by svinota** [comment]
There is a test module: https://github.com/svinota/pyroute2/blob/master/tests/general/test_stress.py#L8

It doesn't fail on the master branch. It can mean that the tests are incorrect. Pls try to close the `IPRoute` instances in your code, when they're not used — e.g. the `with` statement can work well for that case. If the code will continue to fail, it means that there is another bug in my code and I have to fix the tests (to catch it) and the code.

**Comment by svinota** [comment]
I close the bug. If you think it still affects your code, pls let me know.

**Comment by tomislacker** [comment]
I think we're good to close it.  I appreciate the guidance you provided and after updating my code, that does appear to have resolved my issues.

**Comment by svinota** [comment]
Cool, thanks for the feedback!
