### ISSUE TITLE
ikey/okey values not added when creating GRE tunnels through IPDB

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#199]
Hi, I'm trying to create keyed GRE tunnels using pyroute2. I see that `IFLA_GRE_IKEY` and `IFLA_GRE_OKEY` are supported and should be accepted, but just aren't being configured on the resulting GRE tunnel.

Here is a test script which can be used to reproduce the problem:

```python
from pyroute2 import IPDB

ipdb = IPDB()

gre = ipdb.create(ifname='m64511l5',
        kind='gre',
        gre_local='172.16.0.1',
        gre_remote='172.16.0.101', 
        gre_ttl=16,
        gre_ikey=10,
        gre_okey=10)

gre.commit()
gre.up()
```

Here is the resulting output from `ip tunnel list`:

```
root@contained-console:~# ip tunnel list
m64511l5: gre/ip  remote 172.16.0.101  local 172.16.0.1  ttl 16 
gre0: gre/ip  remote any  local any  ttl inherit  nopmtudisc
```

And here is the expected output:
```
root@contained-console:~# ip tunnel add m64511l5 mode gre local 172.16.0.1 remote 172.16.0.101 ttl 16 ikey 10 okey 10
root@contained-console:~# ip tunnel list
m64511l5: gre/ip  remote 172.16.0.101  local 172.16.0.1  ttl 16  key 10
gre0: gre/ip  remote any  local any  ttl inherit  nopmtudisc
```

Doesn't matter if it is encapsulated in a network namespace or not. Using unique input/output keys also doesn't make a difference. Tried this on CentOS 7 and Ubuntu 14.04 LTS.

Let me know if there is anything else I should try.

**Comment by svinota** [comment]
Thanks for reporting, fixing

**Comment by svinota** [comment]
There were two issues in one.
1. The library had wrong type for `IFLA_GRE_IKEY` and `IFLA_GRE_OKEY` — **fixed**
2. One should explicitly specify `IFLA_GRE_IFLAGS` and `IFLA_GRE_OFLAGS`:

```
from pyroute2 import IPDB

ipdb = IPDB()

try:
    gre = ipdb.create(ifname='m64511l5',
                      kind='gre',
                      gre_local='172.16.0.1',
                      gre_remote='172.16.0.101',
                      gre_ttl=16,
                      gre_ikey=10,
                      gre_okey=10,
                      gre_iflags=32,
                      gre_oflags=32).up().commit()
finally:
    ipdb.release()
```

I will read the kernel code, may be there is a way to omit explicit iflags and oflags, but for now it is still so.

Please check, if it will work for you.

**Comment by Callum027** [comment]
Thanks for looking into this issue quickly. Using `IFLA_GRE_IFLAGS` and `IFLA_GRE_OFLAGS` as you described, the key values now get configured as expected for me.

**Comment by svinota** [comment]
Docs added, closing the issue.
