### ISSUE TITLE
latest pyroute2 is not working with iovisor/bcc

### ISSUE THREAD

**Issue by yonghong-song** [svinota/pyroute2#202]
Hi,

The latest pyroute2 does not work with iovisor/bcc
(https://github.com/iovisor/bcc/).

Specifically, I am using kernel 4.4.0-rc1, which is the latest net-next trunk version
(https://kernel.googlesource.com/pub/scm/linux/kernel/git/davem/net-next)

I traced the reason is due to the commit:
commit dd4069b5f4b5dfa0417c4b1ccf291f558133fb95
Author: Peter V. Saveliev <petr.savelyev@ericsson.com>
Date:   Thu Nov 26 12:43:08 2015 +0100

    ifinfmsg: linkinfo proxy bypass for new kernels

The commit change looks like:

diff --git a/pyroute2/netlink/rtnl/ifinfmsg.py b/pyroute2/netlink/rtnl/ifinfmsg.py
index a4f2c9c..f0a4cce 100644
--- a/pyroute2/netlink/rtnl/ifinfmsg.py
+++ b/pyroute2/netlink/rtnl/ifinfmsg.py
@@ -8,6 +8,7 @@ import threading
 import subprocess
 from fcntl import ioctl
 from pyroute2 import RawIPRoute
+from pyroute2 import config
 from pyroute2.common import map_namespace
 from pyroute2.common import map_enoent
 from pyroute2.netlink import nla
@@ -731,6 +732,10 @@ def compat_fix_attrs(msg, nl):
 
 
 def proxy_linkinfo(data, nl):
+    if config.kernel > [3, 2, 0]:
+        return {'verdict': 'forward',
+                'data': data}
+
     offset = 0
     inbox = []
     while offset < len(data):
diff --git a/tests/general/test_ipdb.py b/tests/general/test_ipdb.py
index 74590f5..1aa6d41 100644
--- a/tests/general/test_ipdb.py
+++ b/tests/general/test_ipdb.py
@@ -1285,6 +1285,7 @@ class TestCompat(TestExplicit):
                                    'create_bridge': False,
                                    'create_bond': False,
                                    'provide_master': False}
+        config.kernel = [2, 6, 32]  # RHEL 6
 
 
 class TestImplicit(TestExplicit):
yhs@ubuntu:~/work/pyroute2$ 

Could you explain what exactly this commit does and how may impact a kernel version greater than 3.2.0?

**Comment by yonghong-song** [comment]
To test the failure, following bcc INSTALL.md instructions with latest net-next kernel and latest pyroute2,
after installation, go to your build directory do
   ctest
you will find test_brb and test_brb2 failures.
Further investigation on pyroute2 commits will show the commit in previous comment is responsible for the failure.

**Comment by svinota** [comment]
Thanks for the report, investigating.

The commit you refer to deals with the compatibility subsystem. If it affects the work on new kernels, it is definitively a bug.

The proxy functions in the `ifinfmsg.py` run additional link attributes detection (master interface, link kind)  in the case of bridge and bond interfaces (it is required on the old kernels, since this info is not provided there). This particular commit removes these checks on the link info getting.

**Comment by drzaeus77** [comment]
For reference, here is the traceback I see on my system, similar to @yonghong-song 

```
10: Test command: /home/bblanco/work/bcc/build/tests/wrapper.sh "py_brb_c" "sudo" "/home/bblanco/work/bcc/tests/cc/test_brb.py" "test_brb.c"
10: Test timeout computed to be: 9.99988e+06
10: ERROR:root:  File "/home/bblanco/work/bcc/tests/cc/test_brb.py", line 219, in <module>
10:     main()
10:   File "/usr/lib/python3.5/unittest/main.py", line 94, in __init__
10:     self.runTests()
10:   File "/usr/lib/python3.5/unittest/main.py", line 255, in runTests
10:     self.result = testRunner.run(self.test)
10:   File "/usr/lib/python3.5/unittest/runner.py", line 176, in run
10:     test(result)
10:   File "/usr/lib/python3.5/unittest/suite.py", line 84, in __call__
10:     return self.run(*args, **kwds)
10:   File "/usr/lib/python3.5/unittest/suite.py", line 122, in run
10:     test(result)
10:   File "/usr/lib/python3.5/unittest/suite.py", line 84, in __call__
10:     return self.run(*args, **kwds)
10:   File "/usr/lib/python3.5/unittest/suite.py", line 122, in run
10:     test(result)
10:   File "/usr/lib/python3.5/unittest/case.py", line 645, in __call__
10:     return self.run(*args, **kwds)
10:   File "/usr/lib/python3.5/unittest/case.py", line 597, in run
10:     testMethod()
10:   File "/home/bblanco/work/bcc/tests/cc/test_brb.py", line 161, in test_brb
10:     disable_ipv6=True)
10:   File "/home/bblanco/work/bcc/tests/cc/simulation.py", line 93, in _create_ns
10:     disable_ipv6)
10:   File "/home/bblanco/work/bcc/tests/cc/simulation.py", line 30, in _ns_add_ifc
10:     nl=NetNS(name)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/__init__.py", line 90, in __new__
10:     return cls.registry['class'](*argv, **kwarg)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/netns/nslink.py", line 189, in __init__
10:     self.server.start()
10:   File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
10:     self._popen = self._Popen(self)
10:   File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
10:     return _default_context.get_context().Process._Popen(process_obj)
10:   File "/usr/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
10:     return Popen(process_obj)
10:   File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
10:     self._launch(process_obj)
10:   File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 74, in _launch
10:     code = process_obj._bootstrap()
10:   File "/usr/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
10:     self.run()
10:   File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
10:     self._target(*self._args, **self._kwargs)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/netns/nslink.py", line 137, in NetNServer
10:     Server(cmdch, brdch)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/remote/__init__.py", line 183, in Server
10:     **cmd['kwarg'])
10:   File "/usr/lib/python3.5/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 84, in sendto
10:     ret = self._sproxy.handle(data)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/proxy.py", line 52, in handle
10:     logging.error(''.join(traceback.format_stack()))
10:   File "/usr/lib/python3.5/traceback.py", line 189, in format_stack
10:     return format_list(extract_stack(f, limit=limit))
10:   File "/usr/lib/python3.5/traceback.py", line 201, in extract_stack
10:     stack = StackSummary.extract(walk_stack(f), limit=limit)
10:
10: ERROR:root:Traceback (most recent call last):
10:   File "/usr/lib/python3.5/site-packages/pyroute2/proxy.py", line 39, in handle
10:     ret = plugin(data, self.nl)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/netlink/rtnl/ifinfmsg.py", line 786, in proxy_setlink
10:     get_interface(msg['index'])['ifname']
10:   File "/usr/lib/python3.5/site-packages/pyroute2/netlink/rtnl/ifinfmsg.py", line 775, in get_interface
10:     get_attr('IFLA_LINKINFO').
10: AttributeError: 'NoneType' object has no attribute 'get_attr'
10: 
10: ERROR:root:Restarting IPDB instance after error:
10: Traceback (most recent call last):
10:   File "/usr/lib/python3.5/site-packages/pyroute2/ipdb/__init__.py", line 1115, in serve_forever
10:     messages = self.nl.get()
10:   File "/usr/lib/python3.5/site-packages/pyroute2/netlink/nlsocket.py", line 677, in get
10:     data = self.recv(bufsize)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/netlink/nlsocket.py", line 472, in recv
10:     return self._recv(*argv, **kwarg)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/remote/__init__.py", line 270, in _recv
10:     return Client.recv(self, *argv, **kwarg)
10:   File "/usr/lib/python3.5/site-packages/pyroute2/remote/__init__.py", line 211, in recv
10:     return self.brdch.recv()['data']
10: TypeError: byte indices must be integers or slices, not str
10: 
```

**Comment by svinota** [comment]
Everything is even worse — it's not one, but two bugs. The fix will be ready in approx. one hour.

**Comment by svinota** [comment]
Pls check if it will work. Thanks

**Comment by yonghong-song** [comment]
Just tried. The latest pyroute2 indeed fixed the problem. Thanks!

**Comment by svinota** [comment]
Thank you!
