### ISSUE TITLE
"Error: failed to open netns" on RaspberryPI

### ISSUE THREAD

**Issue by Symen** [svinota/pyroute2#203]
Hey,

I'm trying to create a namespace and assign it a vlan, like discribed in the docs.
The code is working on my laptop 

(Linux bunsenlabs 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) i686 GNU/Linux) 

but on my RaspberryPI 

(Linux controller 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux)

I get this error:
```
  File "/home/pi/TestFramework_0/network/namespace.py", line 14, in __init__
    self.ipdb_netns = IPDB(nl=NetNS(nsp_name))
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netns/nslink.py", line 187, in __init__
    super(NetNS, self).__init__()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 279, in __init__
    super(NetlinkMixin, self).__init__()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/remote/__init__.py", line 206, in __init__
    raise init['error']
OSError: [Errno 22] failed to open netns: 'nsp21'
```
I could trace back the error to this function in "…/pyroute2/netns/__init__.py"
```python
    def setns(netns, flags=os.O_CREAT, libc=None):
        '''
        Set netns for the current process.
        The flags semantics is the same as for the `open(2)`
        call:
            - O_CREAT -- create netns, if doesn't exist
            - O_CREAT | O_EXCL -- create only if doesn't exist
        '''
        libc = libc or ctypes.CDLL('libc.so.6', use_errno=True)
        netnspath = '%s/%s' % (NETNS_RUN_DIR, netns)
        netnspath = netnspath.encode('ascii')
        if netns in listnetns():
            if flags & (os.O_CREAT | os.O_EXCL) == (os.O_CREAT | os.O_EXCL):
                raise OSError(errno.EEXIST, 'netns exists', netns)
        else:
            if flags & os.O_CREAT:
                create(netns, libc=libc)
        nsfd = os.open(netnspath, os.O_RDONLY)
        ret = libc.syscall(__NR_setns, nsfd, CLONE_NEWNET)
        if ret != 0:
            raise OSError(ctypes.get_errno(), 'failed to open netns', netns)
        return nsfd
```
Any ideas how to solve this problem?

**Comment by svinota** [comment]
A syscall is used to create netns — `libc.syscall(__NR_setns, …)`.

Obviously, the library uses wrong syscall number. The hotfix (a proper syscall number) will be provided today.

But probably it's a time to think on more generic solution. The issue is that I'mtrying to avoid using gcc: it would require also kernel and other headers. Not all the platforms can provide that. Without gcc, all that we can, is to guess architecture and try to pick the proper syscall value from constants. So if you have any other idea, pls do not hesitate to write it.

**Comment by svinota** [comment]
Pls check if it will work for you.

**Comment by Symen** [comment]
Thanks for the quick response. 
Unfortunately the fix doesn't help, I got the same error again.

**Comment by svinota** [comment]
Not good. Ok, it can take some time.

**Comment by svinota** [comment]
One more attempt. Pls check. (BTW fixed netns for MIPS as well — thanks :)

**Comment by Symen** [comment]
That's great, it works perfectly :)
Thanks a lot

**Comment by svinota** [comment]
Thank you! Now the library can a bit more :)
