### ISSUE TITLE
[iproute2 rules] Incorrect table inference for FRA_TABLE > 255

### ISSUE THREAD

**Issue by grandrew** [svinota/pyroute2#204]
I am seeing this on my setup:

```
>>> import pyroute2
>>> r=pyroute2.IPRoute()
>>> a=r.get_rules()
>>> for o in a: print o
...
{'family': 2, 'dst_len': 0, 'res2': 0, 'tos': 0, 'res1': 0, 'header': {'pid': 23415, 'length': 60, 'flags': 2, 'error': None, 'type': 32, 'sequence_number': 255}, 'flags': 0, 'attrs': [['FRA_TABLE', 117], ['FRA_SUPPRESS_PREFIXLEN', 4294967295L], ['FRA_FWMARK', 17], ['FRA_FWMASK', 4294967295L]], 'table': 117, ' action': 1, 'src_len': 0, 'event': 'RTM_NEWRULE'}
{'family': 2, 'dst_len': 0, 'res2': 0, 'tos': 0, 'res1': 0, 'header': {'pid': 23415, 'length': 52, 'flags': 2, 'error': None, 'type': 32, 'sequence_number': 255}, 'flags': 0, 'attrs': [['FRA_TABLE', 1017], ['FRA_SUPPRESS_PREFIXLEN', 4294967295L], ['FRA_SRC', '10.9.0.18']], 'table': 249, 'action': 1, 'src_len': 32, 'event': 'RTM_NEWRULE'}
{'family': 2, 'dst_len': 0, 'res2': 0, 'tos': 0, 'res1': 0, 'header': {'pid': 23415, 'length': 60, 'flags': 2, 'error': None, 'type': 32, 'sequence_number': 255}, 'flags': 0, 'attrs': [['FRA_TABLE', 118], ['FRA_SUPPRESS_PREFIXLEN', 4294967295L], ['FRA_FWMARK', 18], ['FRA_FWMASK', 4294967295L]], 'table': 118, ' action': 1, 'src_len': 0, 'event': 'RTM_NEWRULE'}
{'family': 2, 'dst_len': 0, 'res2': 0, 'tos': 0, 'res1': 0, 'header': {'pid': 23415, 'length': 52, 'flags': 2, 'error': None, 'type': 32, 'sequence_number': 255}, 'flags': 0, 'attrs': [['FRA_TABLE', 1018], ['FRA_SUPPRESS_PREFIXLEN', 4294967295L], ['FRA_SRC', '10.9.0.19']], 'table': 250, 'action': 1, 'src_len': 32, 'event': 'RTM_NEWRULE'}
```

note that `table` field does not match `FRA_TABLE` in list for entries with table id > 255

**Comment by svinota** [comment]
Not good, it should work. Thanks, fixing.

**Comment by svinota** [comment]
No, not fixing. After the investigation:
`linux:net/core/fib_rules.c`
```
560 static int fib_nl_fill_rule(struct sk_buff *skb, struct fib_rule *rule,          
561                 u32 pid, u32 seq, int type, int flags,                           
562                 struct fib_rules_ops *ops)                                       
563 {                                                                                
564     struct nlmsghdr *nlh;                                                        
565     struct fib_rule_hdr *frh;                                                    
566                                                                                  
567     nlh = nlmsg_put(skb, pid, seq, type, sizeof(*frh), flags);                   
568     if (nlh == NULL)                                                             
569         return -EMSGSIZE;                                                        
570                                                                                  
571     frh = nlmsg_data(nlh);                                                       
572     frh->family = ops->family;                                                   
573     frh->table = rule->table;                                                    
574     if (nla_put_u32(skb, FRA_TABLE, rule->table))                                
575         goto nla_put_failure;
```

So, if `rule->table` fits in one byte (__u8, see also `include/net/fib_rules.h`), everything is OK. If not — only one byte left in the `frh->table`, and the `frh->table` becomes invalid. To get the correct table value one should use `FRA_TABLE`, not `frh->table`.

Since the library on that level decodes exactly what the kernel provides, you get there 249 (0xf9) from 1017 (0x3f9) and 250 (0xfa) from 1018 (0x3fa).

Strictly speacking, it is not a bug, and I can not even fix the value on the fly — packets should be ready for re-encoding, and if I provide «correct» values in `frh->table`, an occasional packet encoding will fail with a type error.

If you have some idea how to handle the case, pls suggest.

**Comment by grandrew** [comment]
Actually, `table` defined as `u32`:

http://lxr.free-electrons.com/source/include/net/fib_rules.h#L18

but in `fib_rule_hdr` it is indeed `u8`:

http://lxr.free-electrons.com/source/include/uapi/linux/fib_rules.h#L24 while `flags` is `u32` as expected.

but as you can see there are two bytes resrerved in the structure and they were there since the first commit:
https://github.com/torvalds/linux/commit/14c0b97ddfc2944982d078b8e33b088840068976

```c
 18 struct fib_rule_hdr {
 19         __u8            family;
 20         __u8            dst_len;
 21         __u8            src_len;
 22         __u8            tos;
 23 
 24         __u8            table;
 25         __u8            res1;   /* reserved */
 26         __u8            res2;   /* reserved */
 27         __u8            action;
 28 
 29         __u32           flags;
 30 };
```

so maybe they actually do get filled? or, if not, did somebody forget to patch the kernel?

also, I have noticed that in kernel tree there are direct copy operations like

```c
frh->table = rule->table;
```

see http://lxr.free-electrons.com/source/net/core/fib_rules.c?v=3.7#L548

while in del rule in the same file they do a 

```c
if (frh->table && (frh_get_table(frh, tb) != rule->table))
```

so I can assume that this inconsistency is definitely a kernel bug and should be filed to the tracker

**Comment by svinota** [comment]
The reserved fields can be filled, but we can not rely on that. The possible solution would be to follow the same convention as with routes, when `table == 252` means that the `rule->table` is >255. Not 'cause it's the best, but only 'cause it's already used with routes. I will try to propose a fix to LKML, we'll see the reaction.

**Comment by PaulSD** [comment]
I think the same convention used for routes should be followed for rules.  If FRA_TABLE is present, then it should be used, otherwise fall back to frh->table.

However, note that this works like IPv6 routes, not IPv4 routes.  For IPv4, rtm_table==252 when RTA_TABLE>255, but for IPv6 and rules, rtm_table/frh->table==(table & 0xff) when RTA_TABLE/FRA_TABLE is > 255.  See https://github.com/svinota/pyroute2/commit/5705e1020ecccdb0e1446e54b203252dfad936b4
