### ISSUE TITLE
Please support bridge vlan filtering

### ISSUE THREAD

**Issue by nbartos** [svinota/pyroute2#207]
The "bridge" binary in the iproute2 package allows VLAN filtering management (via things like "bridge vlan add dev foo vid 200") on interfaces that have /sys/class/net/foo/bridge/vlan_filtering=1.  It would be really awesome if this package could be extended to allow adding and removing allowed VLANs on bridge slave devices.

**Comment by svinota** [comment]
Ok, will try to do it.

**Comment by svinota** [comment]
Done. Will be documented in the coming release.

**Comment by svinota** [comment]
Syntax:
```
ipr.link('vlan-add', index=idx, vlan_info={'vid': 200})
ipr.link('vlan-del', index=idx, vlan_info={'vid': 200})
```
where `idx` is a bridge port index.

**Comment by svinota** [comment]
included in the release
