### ISSUE TITLE
Please add a few more advanced examples

### ISSUE THREAD

**Issue by nbartos** [svinota/pyroute2#208]
I'm attempting to replicate the iproute2 command:

ip link add extif address 06:00:00:00:00:01 type veth peer name intif address 06:00:00:00:00:02 netns namespace

In the examples I see it's evident how to do these as separate commands, however for both simplicity and due to naming conflicts for the interface inside the various namespaces, I'd really like to do this in a single command.

**Comment by svinota** [comment]
A good question. It looks like it is not implemented in the library to set up the veth peer hwaddr in one single request.

Investigating, thanks.

**Comment by nbartos** [comment]
It would also be nice to have an example of how to configure a point-to-point ip address on an interface.  For example the analog of:
```ip addr add 10.1.1.1/32 peer 192.168.1.1/32 dev veth1```

**Comment by svinota** [comment]
A veth sample: https://github.com/svinota/pyroute2/commit/2ce2a66557d6f9914a9e807859af157713bccc94#diff-9936dcf1e586ec12c9fd7855ba838f02R867

Docs & p2p sample will follow shortly

**Comment by svinota** [comment]
Starting with 79b3db28 possible errors with veth peer attributes. Will be fixed asap.

**Comment by svinota** [comment]
Fixed again

**Comment by svinota** [comment]
Related issue: https://github.com/svinota/pyroute2/issues/216

**Comment by svinota** [comment]
Docs addedd
