### ISSUE TITLE
Problem with IPDB: creating namespace and vlan inside a loop

### ISSUE THREAD

**Issue by Symen** [svinota/pyroute2#210]
Hey, 

I'm trying to assign a vlan to a network namespace more than once, but in the second loop iteration IPDB does only find the lo-interface and I get an error.

I have simplified my problem to the following lines:
```
from pyroute2.netns.nslink import NetNS
from pyroute2.ipdb import IPDB
from pyroute2 import netns

link_iface_name = "eth0"
vlan_iface_name = "vlan21"
vlan_iface_id = 21
namespace_name = "nsp21"
for i in range(0,2):
    print("Create vlan")
    ipdb = IPDB()
    link_iface = ipdb.interfaces[link_iface_name]
    with ipdb.create(kind="vlan", ifname=vlan_iface_name, link=link_iface, vlan_id=vlan_iface_id).commit() as i:
          i.add_ip("192.168.1.11", 24)
          i.mtu = 1400

    print("Create namespace")
    ipdb_netns = IPDB(nl=NetNS(namespace_name))
    netns.setns(namespace_name)
    ipdb_netns.interfaces['lo'].up().commit()

    print("Encapsulate vlan1 in namespace1")
    with ipdb.interfaces[vlan_iface_name] as iface:
          iface.net_ns_fd = namespace_name
    with ipdb_netns.interfaces[vlan_iface_name] as iface:
          iface.add_ip("192.168.1.11/24")
          iface.up()

    print("Delete vlan and namespace")
    ipdb_netns.interfaces[vlan_iface_name].remove().commit()
    netns.remove(namespace_name)
    ipdb_netns.release()
    ipdb.release()
```
It is Interesting that if I remove the namespace section and only use vlans it is working:
```
link_iface_name = "eth0"
vlan_iface_name = "vlan21"
vlan_iface_id = 21
namespace_name = "nsp21"
for i in range(0,2):
    print("Create vlan")
    ipdb = IPDB()
    link_iface = ipdb.interfaces[link_iface_name]
    with ipdb.create(kind="vlan", ifname=vlan_iface_name, link=link_iface, vlan_id=vlan_iface_id).commit() as i:
          i.add_ip("192.168.1.11", 24)
          i.mtu = 1400

    ipdb.interfaces[vlan_iface_name].remove().commit()
    ipdb.release()
```
I also know if I only use one IPDB it is working fine, but that isn't possible for me.

What could be the reason that the IPDB doesn't find the link interface, in the second loop iteration?

**Comment by svinota** [comment]
Sorry for delays in responses.

Thanks for the report, investigating.

**Comment by svinota** [comment]
Ough, why do you do `netns.setns(namespace_name)` ? It is not needed here. To operate with a netns interfaces, one can use `IPDB(nl=NetNS(…))` without any `setns()`

**Comment by Symen** [comment]
Oh my fault. I thought that would be necessary.
Thanks, it works again :)

**Comment by svinota** [comment]
That obviously shows that the documentation is not clear, my bad. Will try to fix it.

**Comment by Symen** [comment]
Srry, but I believe I have to use `netns.setns(namespace_name)`, cause I need to set the namespace to the current process. I want to use the externel library _paramiko_ to set up a ssh-connection and I don't have the option to select a namespace or vlan. If I remove `netns.setns(namespace_name)` paramiko can't find the vlan inside the namespace. Is there another solution?

**Comment by svinota** [comment]
Look, once you set a netns for a process, you **can not** leave it. So there is only one way: fork a child and run setns in the child. No other solution. It's not a library feature, but the OS design.

Pls notice, that if you instantiate `IPDB` or `IPRoute` within a process running in a netns, you do not need to use `NetNS(…)` or `IPDB(nl=NetNS(…))` — any instantiated `IPDB` or `IPRoute` will operate in the netns of the process.

**Comment by Symen** [comment]
Ok, I think I finally got it and it is much easier as I thought. Thanks again.

**Comment by svinota** [comment]
Thanks for the issue, I'm truing to fix the docs
