### ISSUE TITLE
Creating a NetNS does not work on i386 architecture (Ubuntu, at least)

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#213]
Ran into this problem while testing for issue #211.

Test script:
```python
#!/usr/bin/env python3

from pyroute2 import IPDB
from pyroute2 import netns
from pyroute2 import NetNS

print('creating netns')
nl = NetNS('test')

print('creating netns ipdb')
ipdb = IPDB(nl=nl)

print('creating gre')
testgre0 = ipdb.create(ifname='testgre0', kind='gre', gre_local='192.0.2.0', gre_remote='192.0.2.1') if 'testgre0' not in ipdb.by_name.keys() else ipdb.interfaces['testgre0']
print('committing')
ipdb.commit()
print('bringing up gre')
testgre0.up()
print('committing')
ipdb.commit()

print('bringing down gre')
testgre0.down()
print('committing')
ipdb.commit()
print('removing gre')
testgre0.remove()
print('committing')
ipdb.commit()

print('removing netns')
nl.remove()
print('releasing netns ipdb')
ipdb.release()
```

Output on a 64-bit Ubuntu VM:

    root@ubuntu:~# python3 test.py
    creating netns
    creating netns ipdb
    creating gre
    committing
    bringing up gre
    committing
    bringing down gre
    committing
    removing gre
    committing
    removing netns
    releasing netns ipdb

Output on a 32-bit Ubuntu VM:

    root@ubuntu:~# python3 test.py
    creating netns
    Traceback (most recent call last):
      File "test.py", line 8, in <module>
        nl = NetNS('test')
      File "/usr/lib/python3.4/pyroute2/__init__.py", line 90, in __new__
        return cls.registry['class'](*argv, **kwarg)
      File "/usr/lib/python3.4/pyroute2/netns/nslink.py", line 190, in __init__
        super(NetNS, self).__init__()
      File "/usr/lib/python3.4/pyroute2/netlink/nlsocket.py", line 279, in __init__
        super(NetlinkMixin, self).__init__()
      File "/usr/lib/python3.4/pyroute2/remote/__init__.py", line 226, in __init__
        raise init['error']
    OSError: [Errno 22] failed to open netns: 'test'
    ERROR:root:forced shutdown procedure, clean up netns manually

Despite the error shown above, the network namespace actually gets created. Creating network namespaces manually using `ip netns add test` works fine. Using Ubuntu 14.04 LTS with kernel 4.2.0-27-generic on both 32-bit and 64-bit.

**Comment by svinota** [comment]
Expect the fix tonight.

**Comment by svinota** [comment]
Pls check, if it works for you.

**Comment by Callum027** [comment]
Yep, works for me now. Thanks.

**Comment by svinota** [comment]
Thanks!
