### ISSUE TITLE
GRE tunnel iflags/oflags no longer configured/properly shown under IPDB interfaces

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#214]
Looks like commit c78babb causes a regression where the iflags/oflags values configured on GRE tunnel interfaces either are not configured properly or simply show up with value 0 on its IPDB interface (or both).

Test script:
```python
#!/usr/bin/env python3

from pyroute2 import IPDB

ipdb = IPDB()

testgre0 = ipdb.create(ifname='testgre0', kind='gre', gre_local='192.0.2.0', gre_remote='192.0.2.1', gre_iflags=32, gre_oflags=32) if 'testgre0' not in ipdb.by_name.keys() else ipdb.interfaces['testgre0']
testgre0.up().commit()

assert testgre0.gre_iflags == 32
assert testgre0.gre_oflags == 32

testgre0.down()
testgre0.remove().commit()

ipdb.release()
```
Testing commit e9ceafd:

    root@ubuntu:~# pip3 list | grep pyroute2
    pyroute2 (0.3.15.post30)
    root@ubuntu:~# python3 test.py

Testing commit c78babb:

    root@ubuntu:~# pip3 list | grep pyroute2
    pyroute2 (0.3.15.post31)
    root@ubuntu:~# python3 test.py
    Traceback (most recent call last):
      File "test.py", line 10, in <module>
        assert testgre0.gre_iflags == 32
    AssertionError

Using Ubuntu 14.04 LTS, kernel 4.2.0-27-generic, with Python 3.4.3.

**Comment by svinota** [comment]
Mea culpa. I tried to «fix» some IFLA types recently, and it looks like I did it badly.

**Comment by svinota** [comment]
Will be fixed tonight.

**Comment by svinota** [comment]
Pls check

**Comment by Callum027** [comment]
Yep, works for me now. Thanks for the quick fix.

**Comment by svinota** [comment]
Thanks for the report.
