### ISSUE TITLE
New remote netlink syntax example?

### ISSUE THREAD

**Issue by seiferteric** [svinota/pyroute2#215]
Hello, I found the old docs for the remote netlink (which is an awesome feature) but I see it has be reimplemented. Is there any simple examples with the new interface?

**Comment by seiferteric** [comment]
Okay, after some playing around, I got this:

Server:
```
from pyroute2 import remote
s = remote.Master()
s.start()
```

Client:
```
from pyroute2 import remote
c = remote.Remote('tcp://localhost')
dev = c.link_lookup(ifname='eth1')[0]
c.addr('add', index=dev, address='192.168.42.201', mask=24, broadcast='192.168.42.255')
```

**Comment by svinota** [comment]
Technically speaking, it is a security hole — the server trusts the client connection w/o any authentication. So I strongly recommend to use any kind of encrypted tunnels to protect the netlink traffic. If you believe that it should be documented, tell me, I'll try to fix. If you will have feature requests, do not hesitate to file them also.

**Comment by seiferteric** [comment]
I am planning on using [stunnel](https://www.stunnel.org/index.html) to wrap it, thanks for the feedback and your work on the project
