### ISSUE TITLE
Can't set point to point peer IP on address

### ISSUE THREAD

**Issue by jimfunk** [svinota/pyroute2#216]
Looking at netlink, in order to create a point to point address (ip addr add 10.1.1.1 peer 10.1.1.2/32 dev whatever) You have to set IFA_ADDRESS to the remote peer address and IFA_LOCAL to the actual local address. This means that use with IPRoute() should be something like this:

    ipr = IPRoute()
    ipr.addr('add', address='10.1.1.2', mask=24, local='10.1.1.1', index=1)

However, it seems that addr() explicitly overwrites the local parameter with the address parameter, making this impossible to do.

**Comment by svinota** [comment]
Yep. To be fixed.

**Comment by svinota** [comment]
Should be fixed now.

**Comment by svinota** [comment]
Docs added.
