### ISSUE TITLE
HFSC defcls option

### ISSUE THREAD

**Issue by ti-mo** [svinota/pyroute2#221]
Hey @svinota 

Over the past few nights, I've been attempting to build an HFSC / fq_codel hierarchy, but I'm running into an issue with HFSC's `defcls` property. From what I can tell, `options_hfsc()` is complete and the types are correct. (`defcls` is a u16 in struct `hfsc_sched` in the kernel's net/sched/sch_hfsc.c, which corresponds to the `H` datatype)

I've noticed the absence of `gef_hfsc_parameters` in tcmsg.py, so I quickly added this:

```python
def get_hfsc_parameters(kwarg):
    defcls = kwarg.get('default', 0x1)
    return {'attrs': [['TCA_HFSC_UNSPEC', { 'defcls': defcls }]]}
```

and linked to it in `iproute::tc()` so defcls gets added to TCA_OPTIONS. However, when running something like `ipr.tc('add', 'hfsc', 'enp13s0', 0x10000, default=1)`, it shows up as follows:
```
$ tc qdisc             
qdisc hfsc 1: dev enp13s0 root refcnt 2 default 6
```

Equally, `ipr.get_qdiscs(index='enp13s0)` returns
```
        ['TCA_OPTIONS',
         {'attrs': [['TCA_HFSC_UNSPEC', {'defcls': 48}]]}],
```

I cannot seem to modify this value using the library. Any ideas? Cheers!

**Comment by svinota** [comment]
Huh. Give me a day, I'll try to play with that.

**Comment by svinota** [comment]
Found a bug. Thanks.

**Comment by svinota** [comment]
Pls take a look. Default class option is fixed (tested) and curve parameters added (not tested yet):
```
# add HFSC on the interface with index 2, default class == 50 (0x32)
ip.tc('add', 'hfsc', 2, default=50)

# add HFSC and set up real-time curve:
ip.tc('add', 'hfsc', 2, default=50, rsc={'m2': '2mbit'})
```

**Comment by ti-mo** [comment]
Awesome! That fixes the defcls issue. However, it is not possible to add curves to a qdisc, only to a class. The tc userland tool does not support this, but netlink does, it's just silently ignored. Now, when adding a class, netlink complains:

```
ipr.tc('add', 'hfsc', linkid, handle='1:0', default=1)
ipr.tc('add-class', 'hfsc', linkid, parent='1:0', rsc={"m2": "500kbit"})
...
{'info': 0, 'index': 2, 'handle': 65537, 'family': 0, 'parent': 65536, 'value': <class 'pyroute2.netlink.NotInitialized'>, 'pad1': 0, 'header': {'pid': 0, 'value': <class 'pyroute2.netlink.NotInitialized'>, 'length': 0, 'flags': 0, 'attrs': [], 'type': 0, 'sequence_number': 0}, 'pad2': 0, 'attrs': [['TCA_KIND', 'hfsc'], ['TCA_OPTIONS', {'defcls': 16, 'attrs': []}]]} 40 1541
```

Values seem to be correct, but I suppose 'defcls' cannot be a part of an RTM_NEWTCLASS message.

**Comment by svinota** [comment]
Indeed. Will be fixed tomorrow morning. And thanks for the patience :)

**Comment by svinota** [comment]
At least partly should be working now:
```
ip = IPRoute()
testif = ip.link_lookup(ifname='testif')[0]
ip.tc('add', 'hfsc', testif, handle='1:0', default='1:5')
ip.tc('add-class', 'hfsc', testif, handle='1:5', parent='1:0', rsc={'m2': '3mbit'})
```

**Comment by ti-mo** [comment]
Looks great. Will do some more testing over the weekend, but I think that's about it for the scope of this ticket!

**Comment by svinota** [comment]
Added a test case, so it will be covered by CI from now on.

Will be there any issues, pls let me know. Thanks for the feedback!
