### ISSUE TITLE
How to make an IP interface a slave of a VRF interface ?

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#238]
Hi Peter,

I'm progressing a lot in the direction of a working Linux stack MPLS driver for bagpipe-bgp, based on pyroute2.

There is one thing I haven't found how to do with pyroute2:

`ip link set my_interface master vrf_interface`

where vrf_interface is a VRF interface, created with:
```
        ip.create(kind='vrf',
                       ifname=vrf_interface,
                       vrf_table=42).commit()
```

Reading the code, I get the impression that everything related to slave/master control is done via reading/wrinting into sys files, but it doesn't seem like this is what should be done for vrf interfaces, which seems to be done with "pure" netlink messages.

**Comment by svinota** [comment]
Let me investigate a bit. Will be ready tomorrow.

**Comment by svinota** [comment]
It looks like I have no `vrf` interfaces on my system (`4.4.6-301.fc23.x86_64`), should I use `net-next`, will it help?

Meanwhile, can you try pls:
```
with ip.interfaces[vrf_interface] as i:
    i.add_port(…)
```
The argument to `add_port()` can be a string (interface name), int (interface index) or an interface object, like that:
```
with ip.interfaces[vrf_interface] as i:
    i.add_port(ip.interfaces['eth0'])
```

(not sure it **will** work correctly, though, but if the port management on vrf type is generic enough, then it **may** work)

**Comment by svinota** [comment]
Yep, `net-next` works. Shortly will add the support for VRF ports to the library.

**Comment by svinota** [comment]
Should work now, as described, with `add_port()`
```
ipdb.create(ifname='vrf0', kind='vrf', vrf_table=42).commit()
ipdb.create(ifname='v0p0', kind='dummy').commit()
ipdb.create(ifname='v0p1', kind='dummy').commit()
ipdb.interfaces.vrf0.add_port('v0p0').add_port('v0p1').commit()
```

**Comment by svinota** [comment]
«Like a boss» — «enterprise» VRF management (create vrf + 20 veth interfaces, set all as vrf ports):
```
from pyroute2 import IPDB

with IPDB() as ip:
    ip.create(ifname='v0', kind='vrf', vrf_table=42).commit()

    map(lambda x: x.commit(),
        map(lambda x: ip.create(ifname='v0p%02i' % x,
                                peer='p0p%02i' % x,
                                kind='veth'),
            range(20)))

    reduce(lambda x, y: x.add_port(y),
           map(lambda x: ip.interfaces[x],
               sorted(filter(lambda x: x.startswith('v0'),
                             ip.by_name.keys())))).commit()
```
^_^

**Comment by tmmorin** [comment]
Wow, that's pythonic! :)

I confirm that .add_port works as expected to make interfaces slave of a vrf interface.

Thanks!

**Comment by svinota** [comment]
Pls notice, that `add_port()` allows the deferred port addition with partial commits (not documented yet), like that: https://gist.github.com/svinota/c3de8b32ef7986a154dc3897e474d3c2

The API is not public yet, and may be changed, but one can already play with it.
