### ISSUE TITLE
"CommitException: target flags is not set" with interface.up() in IPDB transaction

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#241]
I have the following error with if.up() in IPDB:

```
        with ip.create(kind='vrf',
                            ifname=self.vrf_if,
                            vrf_table=self.rt_table,
                            reuse=True) as i:
            i.up()
```

Trace:
```
    i.up()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 230, in __exit__
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 940, in commit
    raise error
CommitException: target flags is not set
```

There is no such issue if I don't do i.up() .

**Comment by svinota** [comment]
Investigating.

**Comment by svinota** [comment]
Is it ok to ask you to try some even *less* stable code? Or it's better not to make it more serious?

**Comment by svinota** [comment]
Reproduced, fixing

**Comment by svinota** [comment]
Looks like fixed, pls check.

**Comment by svinota** [comment]
Thanks to your issues, found a serious desing flow in the transactions. Fixing

**Comment by tmmorin** [comment]
Thanks for the fix. I confirm it solves the issue.

About testing "less stable" code: why not... :)

**Comment by svinota** [comment]
Thousand thanks!

**Comment by svinota** [comment]
In one-two days I will roll out 0.4.0, it is now in the branch 0.4.x, but has serious issues with multipath routes as well as races in ipaddr and port setup. I hope to fix these issues shortly, so it will be available to install.

Key differences:
* performance
* reliability — routes setup becomes true synchronous with OS, relying on netlink broadcasts (it isn't so in 0.3.x, where IPDB *assumes* that a route is set up)
* transparent compatibility support is **dropped** in favour of the performance — IPDB in 0.4.x will have only limited functionality on kernels prior to 3.2

Also IPDB internals are changed seriously, but it should not affect the public API.

I will make an announce, when it is ready.
