### ISSUE TITLE
ipdb.route / issue when creating an MPLS route

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#242]
Here is my code: 
```
        req = {'family': AF_MPLS,
               'oif': self.ip.interfaces[interface].index,
               'dst': {'label': label,
                       'bos': 1},
               'via': {'family': AF_INET,
                       'addr': ipAddress}
               }

        ip.routes.add(req).commit()
```

Trace:

```
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 554, in add
    self.tables[table][route['dst']] = route
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 513, in __setitem__
    'key': key}
TypeError: unhashable type: 'dict'
```

**Comment by svinota** [comment]
Strange. I was sure it is covered by CI tests. Fixing.

Thanks for the patience.

**Comment by svinota** [comment]
Reproduced, fixing.

**Comment by svinota** [comment]
Ough. Just realized. There is support for MPLS lwtunnel — is that what you want to? If so, then:
```python
# pls notice that labels are strings, e.g. '200' or '200/300'
req = {'dst': 'default',  # or an inet prefix, like, 1.2.3.0/24
       'gateway': ipAddress,
       'encap': {'type': 'mpls', 'labels': str(label)} 
       'oif': self.ip.interfaces[interface].index}
```

There was some initial support that required AF_MPLS, but the API in `net-next` is changed so much, so I'm not sure it will work at all on the current pyroute2 codebase. I'll investigate it, give me a bit more time.

**Comment by svinota** [comment]
Just checked MPLS routes (`linux:net/mpls/af_mpls.c`), they still work well with pyroute2. So I'm to integrate it into IPDB.

**Comment by tmmorin** [comment]
Ah, I got where the misunderstanding comes from.
There are different things you can do with MPLS:
a) forward MPLS to MPLS, typically by swapping labels
b) receive MPLS, pop, and forward as IP
c) forward IP with an MPLS encap

a) and b) is supported with the AF_MPLS family
b) is supported with lwtunnel

**Comment by svinota** [comment]
Yep. LWTunnel support is already done (see `encap` attr in the sample with usual route).

AF_MPLS (label swap/pop/add) routes support will be ready tonight, and finally merge 0.4.x to the master. Thanks for the issue, it promises to be really cool feature :)

I'm going to place AF_MPLS routes into a separate table (`ip.routes.tables['mpls']`) with destination labels as keys, does it sound reasonable?

**Comment by tmmorin** [comment]
> I'm going to place AF_MPLS routes into a separate table (ip.routes.tables['mpls']) with destination labels as keys, does it sound reasonable?

I can't find a practical problem for my use case, but this is maybe not a perfect model, because you can add AF_MPLS to any table. However, I can't find an obvious use case that would lead you to do this...

**Comment by svinota** [comment]
> because you can add AF_MPLS to any table

No, I can not: http://git.kernel.org/cgit/linux/kernel/git/davem/net-next.git/tree/net/mpls/af_mpls.c#n1229

But you're right — later it may change.

**Comment by svinota** [comment]
The master switched to 0.4.x (0.3.x will continue to get fixes), so 0.4.0 is coming this weekend.

Docs are not ready yet, but you can try already:
```python
ip.routes.add({'family': AF_MPLS,
               'dst': label,
               'oif': self.ip.interfaces[interface].index,
               'via': {'family': AF_INET, 'addr': ipAddress}}).commit()
```

Labels syntax:
```python
{…
 'dst': int,
 'newdst': [int, …]}
# swap:
{…
 'dst': 50,
 'newdst': [60]}
# push:
{…
 'dst': 50,
 'newdst': [50, 60]}
```
etc. All the MPLS routes (not lwtunnel) reside in `ip.routes.tables['mpls']`. The key is `(oif, dst)` (see also `ip.routes.tables['mpls'].idx`)

More details will follow.

**Comment by svinota** [comment]
Pls. look also at 7b2a5d2884f9f88492d3f58a011ce0a3ccf39cff

Some functionality is missing still (like correct changing VIA ;)), but it will be completed asap.

**Comment by svinota** [comment]
After 00407e91af3315c4ea4c28a796bda012259488e6 it mostly works (w/o multipath MPLS yet), though there is some unclear API incosistency between vanilla 4.4.6 and net-next master.

**Comment by tmmorin** [comment]
It's now solved for me.

But I've got one question: 
> All the MPLS routes (not lwtunnel) reside in ip.routes.tables['mpls']. The key is (oif, dst) (see also ip.routes.tables['mpls'].idx)

I don't get why the key is (oif,dst): I don't think you can have different routes for a same label, even on different interfaces. What is the intention ?

**Comment by svinota** [comment]
That's true, you're right. Will leave only label as a key :)

**Comment by svinota** [comment]
Done.
