### ISSUE TITLE
"CommitException: target device is not set"

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#243]
When adding the following route:

`req = {'device': 1, 'table': 1002, 'dst': '12.11.11.2/32', 'gateway': '127.0.0.1', 'encap': {'labels': [{'bos': 1, 'label': 119}], 'type': 'mpls'}}
`
The following exception raises:
```
    self.ip.routes.add(req).commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 342, in commit
    raise error
CommitException: target device is not set 
```

It seems that e55eb2abb6669f0b8b19ae0bb214c1dea3269714 is the commit that introduces the issue.

The issue was not 100% reproducible, it maybe because of subtle threading things (bagpipe is  multithreaded), which sounds plausible given that the change is thread-related.

**Comment by svinota** [comment]
Are you sure it must be «device», not «iif» or «oif»? The issue is that there is no RTA_DEVICE in the rtmsg, so the «device» target will never be set up.

And thousand thanks again for your patience.

**Comment by tmmorin** [comment]
I just know that the add request with 'device' was working before in pyroute2, and that in the iproute2 command 'dev' is used.

I can try with oif as well (iif would not make sense here).

**Comment by svinota** [comment]
> was working before

That was my failure then — I cleaned up some deprecated code (there was a really big work done to improve the performance), and probably dropped also these aliases. Thanks, will write it as a warning in the release notes.
