### ISSUE TITLE
Issue with multipath routes (lwtunnel)

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#244]
I don't know if the issue is specific to lwtunnel mpls routes, but I have the following:

Script:
```
from pyroute2 import IPDB

ip = IPDB()

ip.routes.add({'dst': 'default',
               'table': 1002,
               'type': 'unreachable'}).commit()

req = {'table': 1002, 'dst': '12.11.11.1/32', 'oif': 1, 'gateway': '127.0.0.1', 'encap': {'labels': [{'bos': 1, 'label': 192}], 'type': 'mpls'}}

ip.routes.add(req).commit()

req = {'table': 1002, 'dst': '12.11.11.2/32', 'multipath': [{'oif': 1, 'gateway': '127.0.0.1', 'encap': {'labels': [{'bos': 1, 'label': 192}], 'type': 'mpls'}}]}

ip.routes.add(req).commit()


req = {'table': 1002, 'dst': '12.11.11.3/32', 'multipath': [{'oif': 1, 'gateway': '127.0.0.1', 'encap': {'labels': [{'bos': 1, 'label': 192}], 'type': 'mpls'}},
                                                            {'oif': 1, 'gateway': '127.0.0.1', 'encap': {'labels': [{'bos': 1, 'label': 177}], 'type': 'mpls'}}]}
ip.routes.add(req).commit()
```

Run:
```
lnx01:~# ip route flush table 1002 ; python test.py ; ip route show table 1002
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    ip.routes.add(req).commit()
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 343, in commit
    raise error
pyroute2.ipdb.exceptions.CommitException: target table is not set
unreachable default  proto static 
12.11.11.1  encap mpls  192 via 127.0.0.1 dev lo  proto static 
12.11.11.2 via 127.0.0.1 dev lo  proto static 
lnx01:~#
```

Conclusion:
- the default route addition works
- the non multipath lwtunnnel mpls route works
- the multipath route with one lwtunnel mpls nexthop does not raise an exception, but creates a route that has no lwtunnel mpls information
- the multipath route with two lwtunnel mpls nexthops raises an exception

(this is with dbb0128df4b3dd3332a8f8d0752adbb361ab1957)

**Comment by svinota** [comment]
Thanks, investigating

**Comment by svinota** [comment]
The multipath code rewritten. Partly fixed, filly fixed will be today. The features map:
```
IPDB   IPRoute
-----+--------+-------------------------------------
 +   |   +    |  add: {'gateway': …, 'encap': {'type': 'mpls', 'labels': …}}
 -   |   +    |  add: {…, 'multipath': [{'encap': {'type': 'mpls', 'labels': …}}]}  # one NH
 +   |   +    |  add: {…, 'multipath': [{'encap': {'type': 'mpls', 'labels': …}}, …]}  # two and more NH
-----+--------+-------------------------------------
```
The reason why IPDB is failing in the one-NH case is known and is being fixed.

**Comment by svinota** [comment]
ok, now looks that it's almost fixed :) At least, you can try to use it. The code, based on yours, that I used to debug (pls note different labels syntax — you can use any you like more; the code piece just tests that it works in any way):
```python
from pyroute2 import IPDB

with IPDB() as ip:

    ip.routes.add({'dst': 'default',
                   'table': 1002,
                   'type': 'unreachable'}).commit()

    req = {'table': 1002,
           'dst': '12.11.11.1/32',
           'oif': 1,
           'gateway': '127.0.0.1',
           'encap': {'labels': [{'bos': 1, 'label': 192}],  # labels as list of dicts
                     'type': 'mpls'}}
    ip.routes.add(req).commit()

    # The issue with one-NH  route is that it is valid, but on the OS level it
    # produces NOT-mp route. Related issues:
    #
    # * create a proper route key (solved for now)
    # * transform mp to not-mp and vice versa (has to be investigated)
    req = {'table': 1002,
           'dst': '12.11.11.2/32',
           'multipath': [{'oif': 1,
                          'gateway': '127.0.0.1',
                          'encap': {'labels': [192],  # labels as list of ints
                                    'type': 'mpls'}}]}
    ip.routes.add(req).commit()

    req = {'table': 1002,
           'dst': '12.11.11.3/32',
           'multipath': [{'oif': 1,
                          'gateway': '127.0.0.1',
                          'encap': {'labels': [192, 200],
                                    'type': 'mpls'}},
                         {'oif': 1,
                          'gateway': '127.0.0.1',
                          'encap': {'labels': "177/200",  # labels as string
                                    'type': 'mpls'}}]}
    ip.routes.add(req).commit()

    # test NH management (provide more simple API?)
    r = ip.routes.tables[1002]['12.11.11.3/32']
    r.del_nh({'oif': 1,
              'gateway':
              '127.0.0.1',
              'encap': {'labels': [{'bos': 0, 'label': 192},
                                   {'bos': 1, 'label': 200}],
                        'type': 1}})
    r.add_nh({'oif': 1,
              'gateway': '127.0.0.1',
              'encap': {'labels': '192/660', 'type': 1}})
    r.add_nh({'oif': 1,
              'gateway': '127.0.0.1',
              'encap': {'labels': '192/667', 'type': 1}})
    r.commit()

    with ip.routes.tables[1002]['default'] as r:
        r.remove()
    with ip.routes.tables[1002]['12.11.11.1/32'] as r:
        r.remove()
    with ip.routes.tables[1002]['12.11.11.2/32'] as r:
        r.remove()
    with ip.routes.tables[1002]['12.11.11.3/32'] as r:
        r.remove()
```

Some issues still remain, but mostly it should work now.

The code will be included in the CI tests.

**Comment by svinota** [comment]
Also note one important change, that is done against the kernel structure: in NH the interface index field now is not `ifindex`, but `oif` to be uniform with the common route field. I hope it will be less confusing, though not uniform with the kernel.

**Comment by svinota** [comment]
NB: multipath AF_MPLS are also ready for testing.

**Comment by svinota** [comment]
Tests provided.

**Comment by svinota** [comment]
Related docs added: http://docs.pyroute2.org/mpls.html

**Comment by tmmorin** [comment]
Hi Petr, thanks for the improvements.

There is one thing that remains a problem: if you create a route with nexthop information for a single nexthop, a subsequent call to r.add_nh() will actually overwrite the initial nexthop.

The typical way the dataplane is updated in bagpipe is the following:  we receive routing information one next-hop at a time and update the dataplane accordingly.  When a route is received, things are lihgt/easy to implement if we can simply add a next hop to the existing route. Currently we would need to check if a non-multipath nexthop already exist and eventually parse it to recreate a multipath route.

Would it be possible to have add_nh() **not** overwrite existing single next-hop information, but rather reintegrate this next-hop information in the multipath list ?

**Comment by svinota** [comment]
Yep, sure. Thanks for the reminder, I had to fix it already, actually, but didn't.

**Comment by svinota** [comment]
branch «parser2»:

* `del_nh()` is still broken, but will be fixed today.
* `add_nh()` looks like working, but not well tested yet.

Expected time for this to be fixed completely: this weekend, I hope.

**Comment by svinota** [comment]
The code used as the model:
```python
from pyroute2 import IPDB


def main():
    with IPDB() as ip:
        (ip
         .routes
         .add({'dst': '90.0.0.0/24', 'gateway': '127.0.0.2', 'oif': 1})
         .commit())

        (ip
         .routes['90.0.0.0/24']
         .add_nh({'gateway': '127.0.0.3', 'oif': 1})
         .commit())

        (ip
         .routes['90.0.0.0/24']
         .del_nh({'gateway': '127.0.0.2', 'oif': 1})
         .commit())

        (ip
         .routes['90.0.0.0/24']
         .remove()
         .commit())

main()
```

And for AF_MPLS:
```python
from pyroute2 import IPDB


def main():
    with IPDB() as ip:
        (ip
         .routes
         .add({'family': 28,
               'dst': 20,
               'oif': 1,
               'via': {'family': 2, 'addr': '127.0.0.2'},
               'newdst': [50]})
         .commit())

        (ip
         .routes
         .tables['mpls'][20]
         .add_nh({'via': {'family': 2, 'addr': '127.0.0.3'},
                  'oif': 1,
                  'newdst': [60]})
         .commit())

        (ip
         .routes
         .tables['mpls'][20]
         .del_nh({'via': {'family': 2, 'addr': '127.0.0.2'},
                  'oif': 1,
                  'newdst': [50]})
         .commit())

        (ip
         .routes
         .tables['mpls'][20]
         .remove()
         .commit())

main()
```

Corresponding tests are included into CI:
https://github.com/svinota/pyroute2/blob/parser2/tests/general/test_ipdb.py#L894
https://github.com/svinota/pyroute2/blob/parser2/tests/general/test_ipdb.py#L422

The lwtunnel code will be tested (and fixed) asap, but there is a chance that it works already :)

**Comment by svinota** [comment]
Now everything should be working. Pls check, if any issue still remains. Thanks!

**Comment by tmmorin** [comment]
I've just tested parser2, and add_nh works fine, but del_nh works but not completely: it works fine for deleting one of 2 nexthops, but when removing the last one it fails.

```
  File "/opt/bagpipe-bgp/bagpipe/bgp/vpn/ipvpn/mpls_linux_dataplane.py", line 338, in removeDataplaneForRemoteEndpoint
    r.del_nh(self._nh(repr(remotePE), label, None))
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 64, in decorated
    return f(self, direct, *argv, **kwarg)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 75, in decorated
    f(transaction, *argv, **kwarg)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 215, in del_nh
    self['multipath'].remove(nh)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/route.py", line 95, in remove
    raise e
KeyError: IPNHKey(gateway='127.0.0.1', encap='109', oif=1)
```

```
lnx01:~# ip route show table 1001
...
13.11.11.3  encap mpls  109 via 127.0.0.1 dev lo  proto static 
```

**Comment by svinota** [comment]
Yep. 'Cause the last NH record gets merged into the main route record, and I can not do anything with that — it's the kernel behaviour. The route becomes a normal not-multipath route. If you have any suggestions how pyroute2 would behave in that case, pls tell, I'll try to implement.

And the branch is merged into the «master», finally.

**Comment by svinota** [comment]
So, roughly speaking, a multipath route can have `>= 2` NHs, otherwise `Route['multipath']` is empty.

**Comment by tmmorin** [comment]
As I said it would be legitimate to be able to do r.add_nh(x) followed by r.del_nh(x) and obtain the effect of a noop.  But of course for a single nexthop, it does not make much sense, because the resulting route would be invalid (without nexthop information).

And it is quite easy to do the following:
```
 with ip.routes[prefix] as r:
                if r['multipath']:
                    r.del_nh( my_nexthop )
                else:
                    r.remove()
```

So, ok :)

**Comment by svinota** [comment]
Ok. The docs will be ready asap, then I will close the issue.

**Comment by svinota** [comment]
http://docs.pyroute2.org/ipdb.html#multipath-routing

docs updated
