### ISSUE TITLE
/proc/net/psched may be missing

### ISSUE THREAD

**Issue by zgoda** [svinota/pyroute2#245]
The presence of /proc/net/psched on Linux depends on kernel CONFIG_NET_SCHED setting, library assumes it's always available in pyroute2/netlink/rtnl/tcmsg/common.py.

**Comment by svinota** [comment]
Thanks, that's my fault. Fixing.

**Comment by svinota** [comment]
Will be ready tomorrow.

**Comment by svinota** [comment]
Should be fixed now, the module load should not fail.

But the lack of `/proc/net/psched` will limit `tc` functionality anyway, alas. I'm not sure, maybe it's better to place there some `logging.warning()`.

**Comment by zgoda** [comment]
Without CONFIG_NET_SCHED system will use plain fifo scheduler. I don't know how this translates to values otherwise found in /proc/net/psched. Warning will not hurt but the situation should not lead to crash (although functionality may be limited, etc).

**Comment by svinota** [comment]
Yep, thanks.

**Comment by svinota** [comment]
I believe it's resolved now, so I'm closing the bug. Feel free to reopen, if you still encounter any issues with that.

**Comment by zgoda** [comment]
Thank you, works like a charm.

**Comment by svinota** [comment]
Thanks for the feedback!
