### ISSUE TITLE
pvid/untagged in vlan_filter

### ISSUE THREAD

**Issue by nesanton** [svinota/pyroute2#249]
Is it possible to make a vid untagged when adding with IPRoute.vlan_filter?
Something alike the result of command **bridge vlan add dev eth0 vid 20 pvid untagged** 

Sorry if I missed some obvious flags

**Comment by svinota** [comment]
```python
from pyroute2 import IPRoute
ipr = IPRoute()
idx = ipr.link_lookup(ifname="eth0")
ipr.vlan_filter("add", index=idx, vlan_info={"vid": 20, "flags": 6})  # Egress Untagged
```

Thanks for the issue — I have to document it somehow :)

**Comment by svinota** [comment]
added literal flags (to be documented, though):

```python
from pyroute2 import IPRoute
with IPRoute() as ipr:
    idx = ipr.link_lookup(ifname="eth0")[0]
    ipr.vlan_filter("add",
                    index=idx,
                    vlan_info={"vid": 20,
                               "flags": ["pvid", "untagged"]})
```

Available flags: `master` (1), `pvid` (2), `untagged` (4), `range_begin` (8), `range_end` (16), `brentry` (32).

**Comment by svinota** [comment]
Docs updated. Don't hesitate to update the issue, if something is needed. Or to close it, if everything is ok.

**Comment by nesanton** [comment]
How promptly! Thanks very much!

**Comment by svinota** [comment]
Thanks!
