### ISSUE TITLE
Set hub mode fails

### ISSUE THREAD

**Issue by nachtmaar** [svinota/pyroute2#253]
Hi, I am trying to create a hub with pyroute2 without success.
I'm not sure, whether this is a bug, or if I am using pyroute2 wrong.

Version: 0.4.1.post11

I hope you can help me:

```
from pyroute2 import IPDB
ip = IPDB()

with ip.create(kind='bridge', ifname='control') as i:
	i.ageing_time = 0
   
---------------------------------------------------------------------------
CommitException                           Traceback (most recent call last)
<ipython-input-3-fbbc5f3e3e85> in <module>()
      1 with ip.create(kind='bridge', ifname='control') as i:
----> 2         i.ageing_time = 0
      3

/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.pyc in __exit__(self, exc_type, exc_value, traceback)
    192         if exc_type is None:
    193             try:
--> 194                 self.commit()
    195             except Exception as e:
    196                 self.last_error = e

/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.pyc in commit(self, tid, transaction, rollback, newif)
    881         if error is not None:
    882             error.transaction = transaction
--> 883             raise error
    884
    885         time.sleep(config.commit_barrier)

CommitException: target ageing_time is not set
```

**Comment by svinota** [comment]
A question: does the interface «control» exist already?

**Comment by nachtmaar** [comment]
Before I executed the commands above, it doesn't.
Afterwards it does.

**Comment by nachtmaar** [comment]
Ah, I see your point. Your right, as I wanted to reproduce the behaviour the bridge was alrady existing.

The actual traceback is:

```
<ipython-input-3-e022f58fee04> in <module>()
      1 with ip.create(kind='bridge', ifname='control') as i:
      2         i.add_port("tap_00004_3")
----> 3         i.ageing_time = 0
      4

/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.pyc in __exit__(self, exc_type, exc_value, traceback)
    192         if exc_type is None:
    193             try:
--> 194                 self.commit()
    195             except Exception as e:
    196                 self.last_error = e

/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.pyc in commit(self, tid, transaction, rollback, newif)
    881         if error is not None:
    882             error.transaction = transaction
--> 883             raise error
    884
    885         time.sleep(config.commit_barrier)

CommitException: target ageing_time is not set
```

**Comment by svinota** [comment]
There are several issues at once.

1. IPDB doesn't provide (yet) an interface to bridge controls like ageing_time, so the first error should be about «ageing_time» target.
2. «interface control exists» — an error of a next run, when it exists already.

So.

1. IPDB to provide bridge controls — FR is created, #254 
2. Failed `create()` should not leave the interface in the system, removing it (will be tracked here)

**Comment by svinota** [comment]
Both fixes will be ready asap, you can expect a draft version of the bridge / bond controls support in two days. It wasn't implemented yet, since IPDB 0.3.x has to be compatible with LTS kernels. But 0.4.x has no such requirement, so I hope to implement it soon.

**Comment by svinota** [comment]
Looks like github is experiencing issues with the backend now. I will update the bug record as soon as it will work more stable. I hope you've got mails with answers.

**Comment by nachtmaar** [comment]
Yes, I got the mails and I think it is working stable again.
Thats a lot for your effort!

**Comment by svinota** [comment]
Transactions refactored (as usual, docs are pending :| ).

**Comment by nachtmaar** [comment]
Works for me, thanks a lot!

I also think you fixed another bug :)
