### ISSUE TITLE
IPDB traffic shaping

### ISSUE THREAD

**Issue by nachtmaar** [svinota/pyroute2#256]
Is there support in IPDB for traffic shaping? Or do I have to use IPRoute?

E.g:

```
tc qdisc add dev $DEV root handle 1:0 htb default 12
tc class add dev $DEV parent 1:0 classid 1:1 htb rate 190kbit ceil 190kbit
tc class add dev $DEV parent 1:1 classid 1:12 htb rate 100kbit ceil 190kbit prio 2
```

**Comment by svinota** [comment]
IPDB keeps objects in sync with OS using netlink broadcasts, and that allows to run IPDB regardless of what else is used to set up the network.

Unfortunately, unlike other RTNL subsystems, the TC subsystem doesn't send updates, so there are only two ways:

1. tc objects polling
2. place a requirement for IPDB to be the only TC manager at a time

So the TC objects in IPDB are not supported and I see no easy way to implement this support. If you have any ideas or proposals, you're welcome.

**Comment by svinota** [comment]
So for now yes, only `IPRoute` can be used to set up the TC subsystem. I'm sorry.

If your project has a restriction not to introduce new objects, you can use the same netlink socket that IPDB uses for commands, it is accessible via `IPDB.nl` attribute.

**Comment by nachtmaar** [comment]
I am using IPDB mainly because I have a lot of operations I have to do on bridges and tap devices, inclusive traffic shaping.

The IPDB approach seems to be much faster than executing the "classic" system commands like ifconfig, brctl, tc etc.

So my question is, is there a way to save also time with traffic shaping, by sending all commands in one step to the kernel? 

I rewrote my code to use IPDB wherever I can, but traffic shaping and setting the hub mode on a bridge is missing for me (#253).

**Comment by svinota** [comment]
IPDB is faster not 'cause of batch requests — it does not employ batch requests yet, the feature is planned; but batch requests don't make the work much faster, though.

The main reason, why it is faster, is that it doesn't look up all the system info every time it makes a request. Look, an example:
```
# iproute command
$ ip addr add 10.0.0.2/24 dev eth0

# under the hood
# 1. get all the interfaces info
type: RTM_GETLINK, flags: |NLM_F_DUMP → all the interfaces info (a HUGE load of messages)
# 2. resolve the interface name «eth0»
# 3. add the address
type: RTM_NEWADDR → RTM_NEWADDR (response)
```

But for IPDB the workflow differs a lot:
```
# the code
with ipdb.interfaces['eth0'] as i:
    i.add_ip('10.0.0.2/24')

# under the hood
# 1. resolve the interface via cached names (no netlink requests)
# 2. add the address
type: RTM_NEWADDR → RTM_NEWADDR (response + broadcast)
# 3. update the DB with the broadcasted information
```

When you work on hundreds of the network objects like interfaces or routes, IPDB just collects the broadcasted information, it makes no dumps (almost ;), it saves a lot of CPU resources just not requesting what's known already.

So you can use IPRoute together with IPDB to add the TC objects, using IPDB as the cache for interface names, address, routes etc.

If you will need a TC cache, you will have to implement it yourself. But there is an issue.

Sync with RTNL broadcasts:
```
→ request RTM_NEWADDR
← response RTM_NEWADDR
# but the address may be NOT ready yet!
← broadcast RTM_NEWADDR
# here the address IS ready to use
```

IPDB doesn't rely solely on responses, it waits for broadcasts, and it is a relatively reliable way to keep cache in sync and have no races. 

With TC objects everything differs:
```
→ request RTM_NEWQDISC
← response RTM_NEWQDISC
# the qdisc may be NOT ready
# but there is no broadcasts
loop:
    → request RTM_GETQDISC, flags: |NLM_F_DUMP
    ← response RTM_NEWQDISC, a list of all qdisc objects
    # look up if the qdisc appeared in the list, otherwise repeat
```

That loop with qdisc lookups kills all the performance. If in your case it is not important to wait until the qdisc appears, you can avoid the sync step, but IPDB would not: it has to guarantee the system state after the `commit()` call.

…

That's if shortly. I will update docs with that info a bit later.

…

There is the `-b` option for the `ip` command (batch mode), but it doesn't completely solve the issue for iproute.

**Comment by nachtmaar** [comment]
Thanks a lot for the insights! The batch mode is working good for me.
