### ISSUE TITLE
IPDB cannot parse just created bridge

### ISSUE THREAD

**Issue by petraki-boy** [svinota/pyroute2#259]
On latest 0.4.2 there's an exception inside IPDB NL parse engine when creating bridge, see the reproducing lines below:

import pyroute2
ipdb = pyroute2.IPDB()
ipdb.create(ifname='test', kind='bridge').commit()

Exception in thread IPDB event loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 922, in serve_forever
    func(msg)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 1109, in _new
    device.load_netlink(msg)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interface.py", line 283, in load_netlink
    for nla in data.get('attrs', []):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by svinota** [comment]
Could you please run in the git tree:
```
$ sudo make test-platform
```

It is needed to know at least the kernel version and Python version. Also it would be cool if you post the stack trace.

Thanks a lot!

**Comment by petraki-boy** [comment]
$ sudo make test-platform
{'create_bond': True,
 'create_bridge': True,
 'create_dummy': True,
 'ghost_newlink_count': 0,
 'python_version': '2.7.9 (default, Mar  1 2015, 12:57:24) \n[GCC 4.9.2]',
 'uname': ('Linux',
           'dp',
           '3.16.0-4-amd64',
           '#1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02)',
           'x86_64',
           ''),
 'unpack_from': True}

I updated the bug description to include stack trace.

**Comment by svinota** [comment]
Thanks! Will be fixed today.

**Comment by svinota** [comment]
Could you please try the latest master? If the fix will work for you (I can not reproduce it on available kernels, but the error in the code is obvious), I'm to release 0.4.3, since the bug is critical.

**Comment by svinota** [comment]
Reproduced and verified on emulated netlink data. The 0.4.3 release is out, pls confirm if it works for you. Thanks a lot!

**Comment by petraki-boy** [comment]
It works, thank you for the quick response

**Comment by svinota** [comment]
Thousand thanks for the report.
