### ISSUE TITLE
problem with iproute2 - import AF_BRIDGE

### ISSUE THREAD

**Issue by ArashAll** [svinota/pyroute2#261]
while trying to run the code sample :

from pyroute2 import IPRoute
ip = IPRoute()
print([x.get_attr('IFLA_IFNAME') for x in ip.get_links()])

got the following error on OpenBSD and windows, python 2.7, python 3.4 and python 3.5 :

Traceback (most recent call last):
  File "ex.py", line 2, in <module>
    ip = IPRoute()
  File "C:\Python35\lib\site-packages\pyroute2__init__.py", line 122, in **new_
_
    cls.register(cls.registry['class'])
  File "C:\Python35\lib\site-packages\pyroute2__init**.py", line 102, in **geti
tem**
    [name], 0)
  File "C:\Python35\lib\site-packages\pyroute2\iproute.py", line 175, in <module

> ```
> from socket import AF_BRIDGE
> ```
> 
> ImportError: cannot import name 'AF_BRIDGE'

seems it's a issue, could not find a workaround for it ... !

**Comment by svinota** [comment]
I have bad news — pyroute2 is Linux-specific so far, as it is specified in the readme. It is an interface to the Linux netlink protocol.

I'm working on a platform-independent netlink implementation, that could work also on BSD and other UNIX systems, but it is far from complete right now.

**Comment by est** [comment]
Could we add a more user-friendly promotion saying we iproute2 is linux-only?
