### ISSUE TITLE
get_vlans() returns empty list

### ISSUE THREAD

**Issue by nesanton** [svinota/pyroute2#262]
upgrade to version 0.4.3 from 0.4.0 broke get_vlans() 

>>> from pyroute2 import IPRoute
>>> ipr = IPRoute()
>>> ipr.get_vlans() 
[]

same commands on 0.4.0 on the same machine return proper results

The following might be related as it also returns empty list after upgrade:
>>> import socket
>>> from pyroute2 import IPRoute
>>> ipr = IPRoute()
>>> links = [x.get_attr('IFLA_IFNAME') for x in ipr.get_links(family=socket.AF_BRIDGE, ext_mask=2)]
>>> links
[] 

(offtop: is the ext_mask described somewhere anyway?)

**Comment by svinota** [comment]
Confirm.

Thousand thanks. No idea how I missed that, there are functional tests for that, probably, there is a mistake in the tests.

Will be fixed immediately.

**Comment by svinota** [comment]
And no, there is only the Linux kernel code :) But thanks again for the hint, I will put some comments in the code.

**Comment by nesanton** [comment]
No worries, glad to help!

I see. My bad, I should have been doing 
`links = [x.get_attr('IFLA_IFNAME') for x in ipr.get_vlans()] `
instead. This drops the question about ext_mask=2

Thanks for prompt replies!

**Comment by svinota** [comment]
I hope the fix will help. If not, pls ping me.

Thanks again for the report.

**Comment by nesanton** [comment]
Works! thanks

**Comment by svinota** [comment]
0.4.4 is out and includes that fix also. The test for the case is added to CI.

Thanks for the feedback!
