### ISSUE TITLE
Commit does not update the IPDB cache

### ISSUE THREAD

**Issue by Thoth19** [svinota/pyroute2#279]
Based on the http://docs.pyroute2.org/ipdb.html we note that "So IPDB is updated asynchronously, but the commit() operation is synchronous."
As expected,
```python3 
import pyroute2
IFACE = pyroute2.IPDB()
IFACE.interfaces.eth1.up()
```
does not do anything according to ifconfig eth1 and later running

`IFACE.commit()` causes eth1 to come up.

However, the following causes assertion errors:
```python3
for i in range(100):                                                                                                       
    print(i)
    IFACE.interfaces.eth1.up()
    IFACE.commit()
    #1
    assert IFACE.interfaces.eth1.operstate == 'UP'
    IFACE.interfaces.eth1.down()
    IFACE.commit()
    #2
    assert IFACE.interfaces.eth1.operstate == 'DOWN'
```
If we add IFACE.interfaces.eth1.reload() at 1 and 2, the failures continue. It we add IFACE.initdb() at 1 and 2, the failures continue. If we try to rebuild the IFACE object with IFACE = pyroute2.IPDB() at 1 and 2 the failures continue. However, if we replace the asserts with 
`assert 'UP' in subprocess.check_output('ifconfig eth1')` and `assert 'UP' not in subprocess.check_output('ifconfig eth1')` the failures disappear. This implies that the changes are successfully sent to the kernel, but not being propagated back to the library's IPDB cache. This is corroborated by pausing using pdb and checking the output of `ifconfig eth1` and `IFACE.interfaces.eth1.operstate` until the later updated.

Is there an intended workaround? We have been able to get away with using subprocess, but this seems like an unintended behavior.

**Comment by svinota** [comment]
The `operstate` parameter is provided by the kernel, and the library does not interfere with it at all. E.g., this is how it works for dummy interfaces:
```
>>> print(ip.interfaces.dummy0.operstate)
'DOWN'
>>> ip.interfaces.dummy0.up().commit()
>>> (ip.interfaces.dummy0.operstate)
'UNKNOWN'
```

Actually, to check the up/down state you can use `flags & 1` (`IFF_UP` from `ifinfmsg`):
```
>>> print(ip.interfaces.dummy0.flags & 1)
1
>>> ip.interfaces.dummy0.down().commit()
>>> print(ip.interfaces.dummy0.flags & 1)
0
```

There is also a static function to get flags names, though not public:
```
>>> from pyroute2 import IPRoute
>>> from pyroute2.netlink.rtnl.ifinfmsg import ifinfmsg
>>> ipr = IPRoute()
>>> print(ifinfmsg.flags2names(ipr.get_links()[0]['flags']))
['IFF_RUNNING', 'IFF_UP', 'IFF_LOOPBACK', 'IFF_LOWER_UP']
```

Or the same with IPDB:
```
>>> from pyroute2 import IPDB
>>> from pyroute2.netlink.rtnl.ifinfmsg import ifinfmsg
>>> ipdb = IPDB()
>>> print(ifinfmsg.flags2names(ipdb.interfaces.lo.flags))
['IFF_RUNNING', 'IFF_UP', 'IFF_LOOPBACK', 'IFF_LOWER_UP']
```

Why this way? 'Cause the the RTNL works so.

**Comment by svinota** [comment]
Maybe it's a good reason to make the up/down state more… visible? don't know. Right now we're almost directly providing what comes from the kernel.

**Comment by Thoth19** [comment]
In the code snippet I provided, I can replace the calls to pyroute2 with calls to the standard ip commands. So does this mean that the standard ip commands are doing something strange to get the "wrong," answer?
Thanks.

**Comment by Thoth19** [comment]
Is there a way to do other queries, like IP address (for example) using these flags? I haven't done the same testing for other fields of an interface, but I figure I will run into the same problem if I use .ip as .operstate.

**Comment by svinota** [comment]
> So does this mean that the standard ip commands are doing something strange to get the "wrong," answer?

No, the `ip` command works in the very same way:
```
[root@localhost ~]# ip link show dev dummy0
16: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 5e:cd:78:07:2f:18 brd ff:ff:ff:ff:ff:ff
[root@localhost ~]# ip link set dev dummy0 up
[root@localhost ~]# ip link show dev dummy0
16: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 5e:cd:78:07:2f:18 brd ff:ff:ff:ff:ff:ff
```

Pls notice `BROADCAST,NOARP,UP,LOWER_UP` — **flags**; and `state UNKNOWN` — **operstate**

The `ifconfig` command also shows the **flags**, but not the **operstate**:
```
[root@localhost ~]# ifconfig dummy0
dummy0: flags=195<UP,BROADCAST,RUNNING,NOARP>  mtu 1500
        inet6 fe80::5ccd:78ff:fe07:2f18  prefixlen 64  scopeid 0x20<link>
        ether 5e:cd:78:07:2f:18  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 420 (420.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by svinota** [comment]
> Is there a way to do other queries, like IP address (for example) using these flags? I haven't done the same testing for other fields of an interface, but I figure I will run into the same problem if I use .ip as .operstate.

No. Flags are just flags. The only issue with the flags is that they're not the operstate and vice versa.

**Comment by Thoth19** [comment]
I see. So flags and operstate can both be used to check if an interface is UP, but the flags show what is actually the case and operstate lags behind that.

**Comment by svinota** [comment]
Actually, the operstate is defined in RFC2863 [1] and it has to be set up by the administrator to be read by SNMP and so on:

```python
from pyroute2 import IPRoute
with IPRoute() as ipr:
    # this will NOT bring the interface up, but MARK it as up:
    ipr.link('set', index=ipr.link_lookup(ifname='dummy0'), operstate='UP')
```

```python
from pyroute2 import IPDB
with IPDB() as ipdb:
    with ipdb.interfaces.dummy0 as i:
        i.operstate = 'UP'
```

Pls notice, that it doesn't bring the interface up, it **marks** it as up. If you will try to set the operstate == 'UP' on an interface that is really down, the `commit()` will fail.

[1] http://www.rfc-base.org/txt/rfc-2863.txt
