### ISSUE TITLE
pass BRIDGE_FLAGS_SELF to vlan_filter

### ISSUE THREAD

**Issue by nesanton** [svinota/pyroute2#284]
Hi,

Is it possible to do something like the following?

``` bash
bridge vlan add dev br0 vid 20 pvid untagged self
```

The `self` thing seems to be out of BRIDGE_VLAN_INFO_ scope. Apparently it's set with BRIDGE_FLAGS_SELF, but I can't figure out how to do it.

`br0` is bridge itself here

Thanks!

**Comment by nesanton** [comment]
To explain what I'm trying to achieve (perhaps It should be done differently):

E.g eth0 is a physical port of my switch br0. If the physical upstream switch has it's port set with PVID 20, I'd like the eth0 to have the same PVID, so there is no confusion when reading configuration of the physical and 'vurtual' switches. 
In most cases I'd like the br0 interface to have the same PVID (arbitrary vlan tags on br0 are good to have though). This is easy to do with the `self` flag of `bridge vlan` command. 

With pyroute2 the only thing I can manage to do it to pass `master` flag when setting PVID on eth0, so BRIDGE_VLAN_INFO_MASTER is set, which as it's hinted  [here](http://www.spinics.net/lists/netdev/msg292753.html) does these two things:
```
bridge vlan add dev eth0 vid 20 pvid untagged master
bridge vlan add dev br0 vid 20 pvid untagged self
```
Could be good enough, but it does not remove the default PVID 1 from br0

[here](https://github.com/nesanton/kvmvlan#vlan-management-for-kvm) there's a diagram of br0 

Thanks!

**Comment by svinota** [comment]
Pls look here: http://docs.pyroute2.org/iproute.html#pyroute2.iproute.IPRouteMixin.vlan_filter

Maybe it will fit. If not, pls let me know.

**Comment by nesanton** [comment]
Yeah, but this is not exactly what I'm after. I managed to to do what I wanted with:
```python
ipr.link('set', index=7, IFLA_AF_SPEC={'attrs': [['IFLA_BRIDGE_VLAN_INFO', {'flags': 6, 'vid': 20}],['IFLA_BRIDGE_FLAGS', 2]]}, family=socket.AF_BRIDGE, kwarg_filter=IPBridgeRequest)
```
cannot do it thru `vlan_filter` because **flags** keyword argument won't make it to [name2nla](https://github.com/svinota/pyroute2/blob/e2b4f0c266ef540002c95ef6b6c7485eef7f0426/pyroute2/netlink/rtnl/req.py#L272) mapping as it's already stripped off by [link()](https://github.com/svinota/pyroute2/blob/c99963ef2dbbc70c11449e8a3740351b19fc9923/pyroute2/iproute.py#L1218)'s UP/DOWN shortcut 

renaming one of the `flags` would solve it. E.g BRIDGE_FLAGS_ can be passed to link() as `bridge_flags` and then renamed back to `flags` in [IPBridgeRequest](https://github.com/svinota/pyroute2/blob/e2b4f0c266ef540002c95ef6b6c7485eef7f0426/pyroute2/netlink/rtnl/req.py#L272). 
I can try fixing it if you like

**Comment by svinota** [comment]
Yes, I've got your point and you're totally right. Thanks. Will be fixed tonight.

(sorry for delays, I've ot some urgent taks on other project right now, but this weekend I promise to return and review the issues list)

**Comment by nesanton** [comment]
Hi Peter,

Did you get a chance to look at it?
Thanks.

**Comment by svinota** [comment]
Oops. My apologies.

Pls checkout the branch «vlan_flags», it should support the following syntax:

```
from pyroute2 import IPRoute

with IPRoute() as ip:
    ip.vlan_filter("add",
                   index=ip.link_lookup(ifname="br0")[0],
                   vlan_info={"vid": 40, "flags": 6},
                   vlan_flags="self")
```

If it will help, I would merge it into the master.

The reason behind such trick with nla names is that I try to make it compatible with all the subsystems, like IPDB, and it's much easier to maintain such changes in one place (nla definitions).

**Comment by svinota** [comment]
Cool. So I merge it then.
