### ISSUE TITLE
failed to add a port to a bridge while no error report

### ISSUE THREAD

**Issue by xning** [svinota/pyroute2#285]
I tried the 0.3.x branch (manually download and install it by setup.py), 0.3.15 (yum install), and 0.4.16 (it works in python 2.6, that's cool), but adding a port to a bridge by the following function,  while there is not any errors report, but the function doesn't add the *ifname* to the *bridge*.

    def add_ifname_to_bridge(ifname, bridge):
        ipr = IPRoute()
        ipr.link('set', index=ipr.link_lookup(ifname=ifname)[0],
                     master=ipr.link_lookup(ifname=bridge)[0])
        ipr.close()

The function works well on CentOS 7, Fedora 24, Ubuntu 16.04, and Ubuntu 14.04.

**Comment by svinota** [comment]
Yes, the CentOS support is going to be fixed soon (now pyroute2 has some serious issues on the old kernels)

Meanwhile, you can try version 0.3.22, the latest compat-version for now.

**Comment by xning** [comment]
@svinota sorry. I don't know where to download pyroute2-0.3.22?  Clone the 0.3.x branch and install by *setup.py*? I'm interested in trying such version.

**Comment by svinota** [comment]
A stable branch for LTS distros:

```
$ sudo pip install git+git://github.com/svinota/pyroute2.git@0.3.x
```

or

```
$ git clone https://github.com/svinota/pyroute2.git
$ cd pyroute2
$ git checkout 0.3.x
$ sudo make install
```

Also, shortly, the compat code will be back in the 0.4.x branch, so we'll see, how it goes there.

**Comment by xning** [comment]
@svinota the LTS distros works. Does this distros is ready to replace 0.3.15 that is available in RHEL and Fedora yum repo?

**Comment by xning** [comment]
@svinota no. I make some wrong. I have replace the * add_ifname_to_bridge* function by a ip cli wrapper.

**Comment by xning** [comment]
@svinota I have test the 0.3.x branch and the issue is still there.

**Comment by svinota** [comment]
It is strange that the 0.3.x didn't help. But anyways.

Checked the branch «compat» now on RHEL6.5 and looks like working:

```
$ uname -r
2.6.32-431.el6.i686

$ cat /etc/redhat-release 
CentOS release 6.5 (Final)

$ git describe
0.4.6-19-gd57b9f7

$ git branch 
* compat
  master
```

The code:
```
from pyroute2 import IPDB
with IPDB() as ipdb:
    ipdb.create(ifname='tbr0', kind='bridge').commit()
    ipdb.create(ifname='tp0', kind='dummy').commit()
    ipdb.interfaces.tbr0.add_port('tp0').commit()
```

The branch «compat» will be merged into the «master» these days and will be released as 0.4.7 on Friday.

**Comment by svinota** [comment]
Please check the latest master, or 0.4.8 from pypi

**Comment by xning** [comment]
Wow, could install 0.4.8 from pypi,  that's cool.
Yes, @svinota the function _add\_ifname_to\_bridge_ function works. Thanks.

**Comment by xning** [comment]
@svinota  is it OK that usint the 0.4.X version on CentOS 6? Does that the official plan to support 0.4.X on CentOS 6?

**Comment by svinota** [comment]
May I close the issue, if the code works now?

**Comment by xning** [comment]
Sure. Thanks so much.

**Comment by svinota** [comment]
@xning el7 updates queued: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-8cb0e76cc6 (as well as f23, f24, and f25)
