### ISSUE TITLE
faild to add a macvtap  to a netns on CentOS7

### ISSUE THREAD

**Issue by xning** [svinota/pyroute2#286]
The following simple function works on RHEL6, Fedora 24, Ubuntu 14.0.4, and Ubuntu 16.04, but on CentOS 7 failed, even disable SELinux. Report errors are  "(22, 'Invalid argument')". BTW I use pyroute2-0.4.16 installed by _pip_.

```
 def create_macvtap(ifname=None, link=None, mode=None, **kwargs):
      ipr = IPRoute()
      ipr.link('add', ifname=ifname, kind='macvtap', link=index, macvtap_mode=mode)
      ipr.close()
```

**Comment by svinota** [comment]
Thanks, investigating.

**Comment by xning** [comment]
Sorry, I forget something. The *create_macvtap* fail only when the *link* is a bridge.

**Comment by xning** [comment]
On CentOS 7, we can reproduce the issue by following steps, seems this is a kernel issue

    [nerd@localhost procszoo]$ ifconfig macvtap2993
    macvtap2993: flags=4098<BROADCAST,MULTICAST>  mtu 1500
            ether c6:e7:19:40:1f:5a  txqueuelen 500  (Ethernet)
            RX packets 0  bytes 0 (0.0 B)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 0  bytes 0 (0.0 B)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
    
    [nerd@localhost procszoo]$ ip netns
    richard_parker4291
    [nerd@localhost procszoo]$ pip3 list | grep pyroute2
    pyroute2 (0.4.6)
    [nerd@localhost procszoo]$ sudo python3
    Python 3.4.3 (default, Aug  9 2016, 17:10:39) 
    [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pyroute2 import IPRoute
    >>> ipr = IPRoute()
    >>> ifindex = ipr.link_lookup(ifname='macvtap2993')[0]
    >>> ifindex
    9
    >>> ipr.link('set', index=9, net_ns_fd = 'richard_parker4291')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.4/site-packages/pyroute2/iproute.py", line 1239, in link
        msg_flags=msg_flags)
      File "/usr/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 786, in nlm_request
        return do_try()
      File "/usr/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 765, in do_try
        ret = self.get(msg_seq=msg_seq, terminate=terminate)
      File "/usr/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 633, in get
        raise msg['header']['error']
    pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')
    >>>

**Comment by svinota** [comment]
Please check the latest master, published now as 0.4.8

**Comment by xning** [comment]
@svinota bad news. Seems not work. I have changed the _add\_ifname\_to\_ns_ function as follows


    def add_ifname_to_ns(ifname, ns):
        '''add a interface to the ns net namespace'''
         ipr = IPRoute()
        ifindex = ipr.link_lookup(ifname=ifname)[0]
        try:
             ipr.link('set', index=ifindex, net_ns_fd=ns)
         except NetlinkError:
            raise NetworkSettingError('failed to add %s to netns' % ifname)
        except Exception as e:
            printf(e)
             raise NetworkSettingError('failed to add %s to netns' % ifname)
        finally:
    ipr.close()

And when running got following errors

    [nerd@localhost bin]$ sudo ./richard_parker --network --no-maproot
    failed to add macvtap8322 to netns richard_parker3129
    [nerd@localhost bin]$ sudo ./richard_parker --network --no-maproot
    failed to add macvtap7036 to netns richard_parker3147
    [nerd@localhost bin]$

**Comment by xning** [comment]
@svinota perhaps this is a kernel bug. Will add comment after the kernel team response.

**Comment by svinota** [comment]
That's really strange, since it works for me even on CentOS6.5. Thanks for the feedback, will continue to play. Maybe I miss something.

**Comment by xning** [comment]
The kernel bug is [here|https://bugzilla.redhat.com/show_bug.cgi?id=1368830].

**Comment by svinota** [comment]
```
You are not authorized to access bug #1368830.
Most likely the bug has been restricted for internal development processes and we cannot grant access.
```

Ooops.

**Comment by xning** [comment]
@svinota I will track that bug and record its progress here.

**Comment by svinota** [comment]
@xning thank you.
