### ISSUE TITLE
Cannot add IPv6 link local address to IPDB interface

### ISSUE THREAD

**Issue by jta** [svinota/pyroute2#288]
While debugging some test results I ran into the following:

https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/interface.py#L342-L345

I'm not entirely sure why this block exists, since it's perfectly reasonable for a user to want to add multiple IPv6 link addresses to an interface. Is there some limitation in how this ends up being conveyed over netlink?

**Comment by svinota** [comment]
It's an old hack, that should be fixed. The reason was that the system adds an LL address authomatically while bringing the interface up and it confused the IPDB. But I agree, it's a limitation that should not exist — the proper way is to fix the IPDB commit routine.

Will try to do that.

**Comment by svinota** [comment]
Please check the `link_local` branch (you may find the commit by the reference up there ^^^).

Looks like working. If it will work for you, I'll merge it into the master (and will have to fix snapshots then, but I believe, we can do it somehow)

**Comment by svinota** [comment]
Fixed. Feel free to reopen the issue, if it doesn't help.
