### ISSUE TITLE
NetNS assumption about /var/run/netns path could be relaxed

### ISSUE THREAD

**Issue by salv-orlando** [svinota/pyroute2#290]
In some cases (Docker & friends) the network namespace is not bound to an entry in /var/run/netns

The NetNS constructor might allow for specifying an absolute path (e.g.: /proc/xxxx/ns/net) or a fd to that path. This will spare the need for creating a symlink.

This should be a fairly easy patch, even if I haven't yet tried doing that.
Please let me know if there is a workaround that I've not been able to find by myself.

**Comment by svinota** [comment]
One can change `pyroute2.netns.NETNS_RUN_DIR` prior to operate with network namespaces.

But I agree, it may be not the best API, and maybe it would be also not bad to provide explicit path specification in the constructor, as you expected.

**Comment by salv-orlando** [comment]
Indeed changing NETNS_RUN_DIR is the hack I did so far.
However, as I have pyroute2 installed across several nodes, I would have to do some scripting to patch pyroute2 everywhere, which is not really practical.

I agree this is far from being a serious issue. If I have some time today I will put together a patch and create a PR.

**Comment by svinota** [comment]
Pls notice, one can change NETNS_RUN_DIR in the runtime, there is no need to change the module code itself, but as it is a global variable, it affects all the calls:
```python
from pyroute2 import netns
from pyroute2 import NetNS
netns.NETNS_RUN_DIR = "/var/run/my_service"
ns = NetNS("my_netns")
```

**Comment by salv-orlando** [comment]
good point. I think I can do that too.

**Comment by svinota** [comment]
I think, maybe it's a good idea to provide it as an optional argument to all the calls in `pyroute2.netns` and to the `NetNS` constructor, and the argument would default to NETNS_RUN_DIR, if nothing else is specified.

You may play with that or wait for the weekend, I'll do.

**Comment by svinota** [comment]
Closing this ticket as fixed. If there will be issues with the feature, pls reopen it.
