### ISSUE TITLE
Error from doing up() on a veth

### ISSUE THREAD

**Issue by mbanikazemi** [svinota/pyroute2#297]
Using pyroute2 in the OpenStack Kuryr project, I run into the following problem on *some* of the systems I use; I first noticed the problem while using an old version of pyroute2 and after updating to the latest, the problem was resolved. However, I see the same problem on a different system even after using the latest pyroute2 and cannot figure out what may be going wrong.

Here is the simple info on the machine that still generates the error:

bash-4.3# python -V
Python 2.7.12
bash-4.3# uname -a
Linux host-01 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 Linux
bash-4.3# pip list | grep pyroute
pyroute2 (0.4.8)

and here is the error:

...
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork   File "/usr/lib/python2.7/site-packages/kuryr/lib/binding.py", line 146, in port_bind
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork     peer_veth.up()
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork   File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/transactional.py", line 194, in __exit__
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork     self.commit()
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork   File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/interface.py", line 905, in commit
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork     raise error
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork NetlinkError: (22, 'Invalid argument')
2016-10-03 16:57:11.226 22 ERROR kuryr_libnetwork
[2016-10-03 16:57:11,230] ERROR in utils: Unexpected error happened: (22, 'Invalid argument')
2016-10-03 16:57:11.230 22 ERROR kuryr_libnetwork [-] Unexpected error happened: (22, 'Invalid argument')

Please let me know if/what additional information is needed. Thanks.

**Comment by svinota** [comment]
Investigating, thanks.

**Comment by mbanikazemi** [comment]
@svinota just checking to see if you have had a chance to look into this issue. Thanks.

**Comment by svinota** [comment]
Excuse me for the delay. Still trying to understand, what's going wrong here.

**Comment by svinota** [comment]
Can not reproduce it on my platform. Could you please point me the kuryr code, where the issue happens?

**Comment by mbanikazemi** [comment]
@svinota https://github.com/openstack/kuryr/blob/master/kuryr/lib/binding/drivers/veth.py#L66

**Comment by svinota** [comment]
No signs of the issue, when I run in parallel several cycles of veth create/up/remove. Now trying the same, moving veth between netns.

And is it possible that the trace comes from the kuryr code that differs much from the git master?

**Comment by mbanikazemi** [comment]
@svinota thanks for looking into this issue; I can run the code without any problem in most of my setups. It's only with a particular kernel that I see the error. As mentioned above:

# uname -a
Linux host-01 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 Linux

Seeing some earlier pyroute2 issues with older kernels I was wondering if that is the source of the problem here as well. Did you use Ubuntu 14.04 for your tests?

**Comment by svinota** [comment]
@mbanikazemi , yep, my bad, I ran Debian. Trying with that kernel + Ubuntu, thanks.

**Comment by mbanikazemi** [comment]
MY colleagues are reporting that with removing the line in our code where mtg is being set, the problem is resolved. It looks like this bug may be a result of the issue #280 

https://github.com/svinota/pyroute2/issues/280

**Comment by svinota** [comment]
Yep, that's it. And not only #280 , but probably #301 as well. Thanks again for the help.

**Comment by svinota** [comment]
Closing it as the setting of MTU < 68 on veth is not allowed

**Comment by mbanikazemi** [comment]
The problem above turned out to be due to setting the mtu to zero in our code and as mentioned above, this is not allowed. Thanks for looking into the problem.
