### ISSUE TITLE
"CommitException: target flags is not set" when interface.up().commit() in IPDB transaction

### ISSUE THREAD

**Issue by xiesheng211** [svinota/pyroute2#301]
Sometimes I randomly got error:CommitException('target %s is not set' % key). Some are for setting MTU, some for bring up an interface. 

The traceback for bringing up interface:

File "/tmp/sxie/network_v2.py", line 649, in bring_up_interface
    IFACE.interfaces['eth0'].up().commit()
  File "/usr/lib/python3/dist-packages/pyroute2/ipdb/interface.py", line 905, in commit
    raise error
  File "/usr/lib/python3/dist-packages/pyroute2/ipdb/interface.py", line 745, in commit
    transaction.wait_all_targets()
  File "/usr/lib/python3/dist-packages/pyroute2/ipdb/transactional.py", line 468, in wait_all_targets
    raise CommitException('target %s is not set' % key)
pyroute2.ipdb.exceptions.CommitException: target flags is not set

**Comment by svinota** [comment]
@xiesheng211 could you please specify the kernel and the Linux distro? Is there NetworkManager running on the system at that moment?

**Comment by xiesheng211** [comment]
I am using Ubuntu 14.04.4 LTS. 
I think there is no NetworkManager running. There was only a ifplugd running on eth0. But I met that problem when I tried to bring up eth1. 
I also meet CommitException('target %s is not set' % key) when setting MTU sometimes. But these happens very randomly when I run tests and I haven't find a way to reproduce these failures.

**Comment by svinota** [comment]
@xiesheng211  the last question — what the pyroute2 version do you use? Does it fail on the master branch from the git as well?

**Comment by xiesheng211** [comment]
I am using 0.4.5. I haven't tried to use the latest version. Maybe I need to use the latest version to see if that also happens.

**Comment by svinota** [comment]
If it is possible — that would be cool, there are some changes since 0.4.5. Thanks a lot.

**Comment by xiesheng211** [comment]
Got it once again after I upgrade to 0.4.10 which is the newest release version. Do you have any hint for me that possible cause for this failure?

Backtrace:
File "/tmp/sxie/network_v2.py", line 893, in bring_up_interface
    IFACE.interfaces['vir1'].up().commit()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/interface.py", line 905, in commit
    raise error
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/interface.py", line 745, in commit
    transaction.wait_all_targets()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/transactional.py", line 468, in wait_all_targets
    raise CommitException('target %s is not set' % key)
pyroute2.ipdb.exceptions.CommitException: target flags is not set

After this "ifconfig vir1" got:
vir1      Link encap:Ethernet  HWaddr 3a:ee:2b:a2:b9:2b  
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::38ee:2bff:fea2:b92b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:20452 errors:0 dropped:5772 overruns:0 frame:0
          TX packets:502 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1428675 (1.4 MB)  TX bytes:37364 (37.3 KB)

**Comment by xiesheng211** [comment]
Got it once again after I upgrade to 0.4.10 which is the newest release version. Do you have any hint for me that possible cause for this failure?

Backtrace:
File "/tmp/sxie/network_v2.py", line 893, in bring_up_interface
IFACE.interfaces['vir0'].up().commit()
File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/interface.py", line 905, in commit
raise error
File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/interface.py", line 745, in commit
transaction.wait_all_targets()
File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/transactional.py", line 468, in wait_all_targets
raise CommitException('target %s is not set' % key)
pyroute2.ipdb.exceptions.CommitException: target flags is not set

After this "ifconfig vir0" got:
vir0      Link encap:Ethernet  HWaddr 92:6f:3b:cb:81:ac  
          inet6 addr: fe80::906f:3bff:fecb:81ac/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:124875 errors:0 dropped:27334 overruns:0 frame:0
          TX packets:4639 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:8946407 (8.9 MB)  TX bytes:374206 (374.2 KB)

IPDB seems already brings up the interface.

**Comment by svinota** [comment]
Would I like to have a hint myself to debug it… Pls wait two days more, the next week I will be able to debug it rigorously. Pls excuse for delays last weeks, I'm really sorry.

**Comment by xiesheng211** [comment]
I looked into the process and find out this maybe a real timeout problem because it is very often to take 3-4 sec to make configuration applied to kernel. Then I changed "SYNC_TIMEOUT" in transactional.py from 5 sec to 10 sec and that never happened since then. 

Is there any API to set this SYNC_TIMEOUT in this library? Do you have any reason that you think kernel should finish applying config within 5sec?

**Comment by svinota** [comment]
> Is there any API to set this SYNC_TIMEOUT in this library?

    from pyroute2.ipdb import transactional
    transactional.SYNC_TIMEOUT = …

> Do you have any reason that you think kernel should finish applying config within 5sec?

Just a heuristic expectation. Probably, we have to increase it.

**Comment by svinota** [comment]
Yep, let's increase the timeout. The question is, what the timeout there should be — and there must be some, not to hang forever in the case of errors. Ten seconds, more? What would you expect from your experience?

**Comment by xiesheng211** [comment]
Currently 10sec is enough, but I will write more tests to test what the proper timeout is. After that I will comment here. Thank you very much for your help.
