### ISSUE TITLE
Inconsistent IPv4/IPv6 list order from interfaces 'ipaddr' value

### ISSUE THREAD

**Issue by jonathanelscpt** [svinota/pyroute2#302]
Hi

**Goal**: 

Determine IPv4 address(es) and netmask(s) assigned to an interface.

I am using the following:

```
>>> ipdb_namespace.interfaces['dummy1']['ipaddr']
['192.168.100.1/27', 'fe80::54c8:c2ff:fef3:d2ba/64']

```

The object type is a list, but I am unable to rely on the list index, as I find that is not consistent between multiple script executions.  I then face errors where the IPv6 address is returned unexpectedly:

```
Traceback (most recent call last):
  File "./ipdb_example.py", line 663, in <module>
    main()
  File "./ipdb_example.py", line 656, in main
    public_network=tbed["public_network"])
  File "./ipdb_example.py", line 281, in assign_iface
    assert iface['ipaddr'][1]['address'] == str(self.private_network.ip)
AssertionError
```

Ideally, I'd like a mechanism similar to how the netifaces library allows you to specify family:
- netifaces.AF_INET
- netifaces.AF_INET6
- netifaces.AF_LINK

[https://pypi.python.org/pypi/netifaces](https://pypi.python.org/pypi/netifaces)

Is this a bug, or is there a better way to do this?

Thanks,
Jonathan

**Comment by svinota** [comment]
I would name it a «bad design» rather than a bug. Yep, the requirement sounds reasonable, I will try to implement it.

**Comment by jonathanelscpt** [comment]
Excellent!  Thank you for the quick response.  This is a fantastic library.

**Comment by svinota** [comment]
Sorry for delay, the API is being changed right now. It will be ready/tested tomorrow at night, I believe. I will post here the branch to look at.
