### ISSUE TITLE
flush_routes leaking memory

### ISSUE THREAD

**Issue by jimfunk** [svinota/pyroute2#316]
I noticed an issue running on a system with full table BGP where calling flush_routes on a separate routing table takes a long time and consumes nearly 6G of RAM which is never released.

Here's a quick way to replicate:

```
pip install pyasn
pyasn_util_download.py --latest
pyasn_util_convert.py --single rib.20161128.2200.bz2 theinternet  # Adjust for the file it downloaded
gateway=$(ip r show exact 0.0.0.0/0 | cut -d " " -f 3)
interface=$(ip r show exact 0.0.0.0/0 | cut -d " " -f 5)
while read prefix ; do ip r add $prefix via $gateway dev $interface ; done < <(awk '{print $1}' < theinternet)
python3 -c 'import pyroute2; pyroute2.IPRoute().flush_routes(table=1000)'
```

**Comment by svinota** [comment]
Looks serious. Thanks, fixing.

**Comment by svinota** [comment]
Uhhh… So far I broke only the kernel :) Still investigating.

Could you please confirm that
```
import gc
gc.collect()
```
doesn't help?

**Comment by jimfunk** [comment]
It helped a little bit. It went down to about 4G RSS after the collect().

**Comment by svinota** [comment]
Not much better, though. Ok, thanks.

**Comment by svinota** [comment]
Investigated the leak — and it is not a leak, but the malloc pool, that shrinks not fully (I debugged the python process with meliae before and after running `flush_routes()`)

But the speed in that case and the total amount of the required memory are a serious issue that I will try to fix this week — there is a way to do it, though it requires some architecture hacks.

**Comment by svinota** [comment]
The nemory issue looks to be fixed. The performance issue is harder to fix, though; but we'll try.
