### ISSUE TITLE
Inconsistent handling of network namespaces

### ISSUE THREAD

**Issue by ivc** [svinota/pyroute2#317]
Since a recent update "pyroute2.NetNS" allows namespaces specified as "/proc/PID/ns/net" in addition to "named" namespaces. But "IPDB().interfaces.<ifname>.net_ns_fd" is still limited to "named" namespaces only.

Use-case: we are implementing CNI driver [1] for Kubernetes and we are following CNI's [2] approach where the VETH pair is initially created inside the container and one end is then moved to the host namespace. The task seems impossible using 'net_ns_fd' with the current pyroute2 implementation (we can not use real FD as it is closed when NetNS server Popen's and there's no 'named' namespace exists in our case). Note: in our case it is possible to use 'net_ns_pid' instead of 'net_ns_fd', so the issue is not critical for us.

[1] https://review.openstack.org/#/c/404038/4/kuryr_kubernetes/cni/binding/bridge.py@35
[2] https://github.com/containernetworking/cni

**Comment by svinota** [comment]
Please take a look, if that will work for you.

**Comment by svinota** [comment]
@ivc , pardonnez-moi, but does it mean «works» or «not» ? :)

**Comment by ivc** [comment]
@svinota, means "thanks, works great!" :)

  from pyroute2 import IPDB, NetNS
  from os import getpid
  
  with IPDB(NetNS('testme')) as ipdb:
    with ipdb.create(ifname='testme0', peer='testme1', kind='veth') as iface:
      iface.up()
    with ipdb.interfaces.testme1 as iface:
      iface.net_ns_fd = '/proc/%(self)s/ns/net' % {'self': getpid()}

**Comment by svinota** [comment]
using `/proc/self/` here hangs the `IPDB(nl=NetNS(…))`, so reopen until fixed

**Comment by svinota** [comment]
Fixed.
