### ISSUE TITLE
ValueError: too many values to unpack (iproute.py)

### ISSUE THREAD

**Issue by pavlix** [svinota/pyroute2#319]
The following code looks wrong. The default value seems to be the string command which cannot be unpacked as a 2-tuple.

 (command, flags) = commands.get(command, command)

  * https://github.com/svinota/pyroute2/blob/master/pyroute2/iproute.py#L807
  * https://github.com/svinota/pyroute2/blob/master/pyroute2/iproute.py#L958
  * https://github.com/svinota/pyroute2/blob/master/pyroute2/iproute.py#L1222
  * https://github.com/svinota/pyroute2/blob/master/pyroute2/iproute.py#L1312
  * https://github.com/svinota/pyroute2/blob/master/pyroute2/iproute.py#L1447
  * https://github.com/svinota/pyroute2/blob/master/pyroute2/iproute.py#L1634
  * https://github.com/svinota/pyroute2/blob/master/pyroute2/iproute.py#L1763

    Traceback (most recent call last):
      File "tools/connectivity-check", line 17, in <module>
        main()
      File "tools/connectivity-check", line 13, in main
        result = ip.route("show")
      File "/usr/lib64/python3.4/site-packages/pyroute2/iproute.py", line 1621, in route
        (command, flags) = commands.get(command, command)
    ValueError: too many values to unpack (expected 2)

**Comment by svinota** [comment]
```python
# ip.route("dump"[, …])
# ip.get_routes([…])
#
# e.g.:
ip.route("dump")
ip.route("dump", table=100)
```

**Comment by svinota** [comment]
But we can have there `show` as well, no problems :)

**Comment by pavlix** [comment]
No specific opinion and I will get back to experimenting with pyroute2 later.
