### ISSUE TITLE
ERROR: "File exists" when add IPV6 address using add_ip()   [IPDB]

### ISSUE THREAD

**Issue by xiesheng211** [svinota/pyroute2#322]
(Pdb) IFACE.interfaces['eth1'].add_ip('2001:21:21:21::/64').up().commit()
*** pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')

**Get error "NetlinkError: (17, 'File exists')" when trying to add IPV6 address to 'eth1' which is DOWN and no ip address configured. However, when I check "ifconfig eth1", it shows 'inet6 addr: 2001:21:21:21::/64' already there**
'''
eth1      Link encap:Ethernet  HWaddr 00:50:56:83:32:4b
          inet6 addr: 2001:21:21:21::/64 Scope:Global
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:11982 errors:0 dropped:578807 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:804177 (804.1 KB)  TX bytes:886 (886.0 B)
'''

**Then I looked into the "pyroute2/tests/general/test_ipdb.py" test "test_routes_ipv6()" and find it bring up interface when adding ipv6 address.** 
'''
        i = self.ip.create(ifname=uifname(), kind='dummy')
        with i:
            i.add_ip('2001:4c8:1023:108::39/64')
            i.up()
'''

**Then I tried myself, it works.**
 
(Pdb) IFACE.initdb()
(Pdb) IFACE.interfaces['eth1'].add_ip('2001:21:21:21::/64').up().commit()
{'broadcast': 'ff:ff:ff:ff:ff:ff', 'carrier': 1, 'ipdb_priority': 0, 'promiscuity': 0, 'vlans': [], 'num_rx_queues': 4, 'operstate': 'UP', 'address': '00:50:56:83:32:4b', 'neighbours': ['fe80::21c:73ff:fe00:1400'], 'txqlen': 1000, 'group': 0, 'flags': 69699, 'num_tx_queues': 4, 'ipdb_scope': 'system', 'family': 0, 'linkmode': 0, 'proto_down': 0, 'ifname': 'eth1', 'ifi_type': 1, 'qdisc': 'mq', 'ports': [], 'ipaddr': ['2001:21:21:21::/64', 'fe80::250:56ff:fe83:324b/64'], 'index': 3, 'mtu': 1500, 'carrier_changes': 11}

**Is there any reason why we must bring up a interface when adding IPV6 address? I tried to use "ip addr add ..." command and it doesn't require that.**

**Comment by svinota** [comment]
Indeed, a bug. Thanks, fixing.

**Comment by svinota** [comment]
Confirmed on eth-interfaces (dummy interfaces behave differently). Thanks again, it's an important issue.

**Comment by svinota** [comment]
Should be fixed, pls check if it works for you.
