### ISSUE TITLE
Error message is not intuitive in case error is due to vlan device has more mtu than parent port

### ISSUE THREAD

**Issue by vikaschoudhary16** [svinota/pyroute2#332]
>>> ipdb.interfaces['eth0']
{'family': 0, 'txqlen': 1000, 'ipdb_scope': 'system', 'index': 2, 'operstate': 'UP', 'num_tx_queues': 1, 'group': 0, 'carrier_changes': 2, 'ipaddr': ['15.0.0.6/24', 'fe80::f816:3eff:fe7b:6f9d/64'], 'neighbours':
 ['15.0.0.4', '15.0.0.5', '15.0.0.1', '15.0.0.2'], 'ifname': 'eth0', 'promiscuity': 0, 'linkmode': 0, 'broadcast': 'ff:ff:ff:ff:ff:ff', 'address': 'fa:16:3e:7b:6f:9d', 'vlans': [], 'ipdb_priority': 0, 'qdisc': '
pfifo_fast', **'mtu': 1400**, 'num_rx_queues': 1, 'carrier': 1, 'flags': 69699, 'ifi_type': 1, 'ports': []}

>>> with ipdb.create(ifname='dummy_name', link=ipdb.interfaces['eth0'],kind='vlan', vlan_id=110) as iface:
...     **iface.mtu=1450**
...     iface.up()
...     
... 
{'index': 0, 'kind': 'vlan', 'ipaddr': [], 'ports': [], 'link': 2, 'vlan_id': 110, 'ifname': 'dummy_name', 'vlans': [], 'ipdb_priority': 0, 'ipdb_scope': 'create'}
Traceback (most recent call last):
  File "<input>", line 3, in <module>
    iface.up()
  **_File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/transactional.py", line 194, in __exit__
    self.commit()
  File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/interface.py", line 916, in commit
    raise error
RuntimeError_**

>>> with ipdb.create(ifname='dummy_name2', link=ipdb.interfaces['eth0'],kind='vlan', vlan_id=110) as iface:
...     **iface.mtu=1300**
...     iface.up()
...     
... 
{'index': 0, 'kind': 'vlan', 'ipaddr': [], 'ports': [], 'link': 2, 'vlan_id': 110, 'ifname': 'dummy_name2', 'vlans': [], 'ipdb_priority': 0, 'ipdb_scope': 'create'}
>>>

**Comment by svinota** [comment]
Yep. Will be fixed.

**Comment by svinota** [comment]
IPDB returns now the `NetlinkError`, so I close it as outdated.
