### ISSUE TITLE
Managing a list:set with pyroute2

### ISSUE THREAD

**Issue by ti-mo** [svinota/pyroute2#334]
Hi, I'm trying to add subsets to a `list:set`, but this does not seem possible with the current ipset implementation.

```python
ips.create('superset', stype='list:set', family=socket.AF_UNSPEC)
ips.create('subset', stype='hash:ip', family=socket.AF_INET)

# This does not pass inet_pton
ips.add('superset', 'subset')

# And this raises TypeError('unknown family') on line 164 in _entry_to_data_attrs,
# because only AF_INET and AF_INET6 are supported
ips.add('superset', 'subset', family=socket.AF_UNSPEC)
```

Looking at the decoded messages, I cannot figure out what the family type does need to be for this one:

```
# ipset create superset list:set
# ipset create subset hash:net
# strace -e trace=network -f -x -s 4096 ipset add superset subset
```

Thanks in advance for your help!

**Comment by svinota** [comment]
thanks, will look into that

**Comment by ffourcot** [comment]
Hello,

First of all, you will need to pass a "etype" argument when you call the "add" method. But it sadly does not solve your issue. I'm working on it

**Comment by ffourcot** [comment]
Hello,

Fixed in the list of commits today. You can have a look on the tests if you want an example of how it works with "etype" option of add() method

**Comment by ti-mo** [comment]
@ffourcot Perfect, just what I needed, thank you! I was not aware of `etype`, will try to contribute some documentation when integrating this into my tool, was still just poking around with the ipset functionality. When would you be cutting 0.4.13?

**Comment by svinota** [comment]
@ti-mo 0.4.13 planned for this weekend — there are several important updates.
