### ISSUE TITLE
GVRP support

### ISSUE THREAD

**Issue by jimfunk** [svinota/pyroute2#336]
I can add an interface using kind='vlan', vlan_id=whatever, but there appears to be no way to enable GVRP.

In iproute2, I can do this:

    ip link add vlan300 link trunk type vlan id 300 gvrp on

I can see the flags attr where that would be if I load an existing interface via IPDB or IPRoute, but I can't seem to turn it on or have it on during creation.

**Comment by svinota** [comment]
Thanks, will be fixed asap

**Comment by svinota** [comment]
An experimental support is added on the low-level as well as in the IPDB, see commits.

There are issues still:
1. changing the vlan_flags from IPDB is not reflected properly in the database, so they stay the same — will be fixed asap
2. changing the vlan_flags from outside of IPDB is not reflected in the database — may ***not*** be fixed, as this change is not broadcasted by the kernel; still thinking on a workaround.

**Comment by jimfunk** [comment]
Sorry it took this long to test. I can't seem to get it to work, using pyroute2 from master.

Using IPDB:

    >>> interface = ipdb.create(kind='vlan', ifname='vlan302', link=7, vlan_id=302, vlan_flags=3)
    >>> interface.commit()
    {'vlan_id': 302, 'link': 7, 'carrier_changes': 0, 'address': '0c:c4:7a:0b:43:ff', 'linkmode': 0, 'num_tx_queues': 1, 'group': 0, 'index': 985, 'proto_down': 0, 'vlan_flags': 1, 'operstate': 'DOWN', 'neighbours': [], 'gso_max_size': 65536, 'family': 0, 'ipdb_priority': 0, 'ports': [], 'kind': 'vlan', 'flags': 4098, 'num_rx_queues': 1, 'carrier': 1, 'ipaddr': [], 'ifi_type': 1,'txqlen': 1000, 'ifname': 'vlan302', 'gso_max_segs': 65535, 'vlans': [], 'qdisc': 'noop', 'mtu': 1500, 'broadcast': 'ff:ff:ff:ff:ff:ff', 'ipdb_scope': 'system', 'promiscuity': 0}
    >>> interface.vlan_flags
    1

Using IPRoute:

    >>> ip.link('add', kind='vlan', ifname='vlan301', link=7, vlan_id=301, vlan_flags=3)
    [{'header': {'length': 36, 'flags': 0, 'type': 2, 'error': None, 'sequence_number': 259, 'pid': 4106116622}, 'event': 'NLMSG_ERROR'}]

    # ip -d l show dev vlan301
    984: vlan301@bond0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 0c:c4:7a:0b:43:ff brd ff:ff:ff:ff:ff:ff promiscuity 0
        vlan protocol 802.1Q id 301 <REORDER_HDR> addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535

**Comment by svinota** [comment]
```
ipdb.create(ifname='v101',
            kind='vlan',
            link=ip.interfaces.test,
            vlan_id=101,
            vlan_flags='gvrp').commit()

ipr.link('add',
         ifname='v101',
         kind='vlan',
         link=ip.interfaces.test,
         vlan_id=101,
         vlan_flags='gvrp')
```

Tested and working.

Possible syntax of the `vlan_flags`:
```
vlan_flags = int
vlan_flags = {'flags': int, 'mask': int}
vlan_flags = 'gvrp'
vlan_flags = ('gvrp', 'mvrp')  # <-- (flag, flag, …)
vlan_flags = (int, int)  # <-- (flags, mask)
```

Sorry for the delay.
