### ISSUE TITLE
strace-based netlink debug method doesn't work with strace >= 4.13

### ISSUE THREAD

**Issue by etene** [svinota/pyroute2#337]
Hello,
I'm running Debian Testing with strace 4.15
I tried to follow the instructions at [http://docs.pyroute2.org/debug.html](http://docs.pyroute2.org/debug.html).

It appears that the strace developers added some logic to decode netlink messages in [commit 2850f745](https://github.com/strace/strace/commit/2850f745ca49f52b4b1266a6a1b1ec0c58f77c66), which corresponds to version 4.13.
This is neat in itself, but it causes strace's output to leave out the message header, as detailed below.

Here's an excerpt from running `strace -e trace=network -x -s 16384 ip route show`:
`recvmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base=[{{len=52, type=0x18 /* NLMSG_??? */, flags=NLM_F_MULTI, seq=1488792959, pid=2658}, "\x02\x00\x00\x00\xfe\x03\x00\x01\x00\x00\x00\x00\x08\x00\x0f\x00\xfe\x00\x00\x00\x08\x00\x05\x00\x0a\x04\x01\x01\x08\x00\x04\x00\x06\x00\x00\x00"},`
As you can see, it prints some information such as the message length, type and flags but strips the message header in the hex dump (the length is supposed to be 52 but the printed hex output is only 36 bytes long). This behavior appears to be hardcoded.

As a result, copying and pasting strace's output in files and running decoder.py on them doesn't work anymore.

Could you mention it in the documentation ? I can open a pull request for this if you want.
Even better, do you have a workaround (other than using an older strace version, of course) ? I was thinking about something based on nlmon but I just stumbled upon this today and haven't had time yet to think this through.

**Comment by svinota** [comment]
Yep, thanks for the heads-up.

There is a nasty way — to reconstruct the header from «parsed» information back to the hex. Should work. Meanwhile, feel free to make pull request on the docs.

**Comment by etene** [comment]
Here's the pull request for the docs; tell me if anything's wrong with it.
I'm working on an alternate method based on nlmon instead, if you're interested I'll make a PR for it eventually. Cheers and thanks for your time !

**Comment by svinota** [comment]
Thanks for the contribution!
