### ISSUE TITLE
IPDB interfaces carries information about interfaces that failed to be created

### ISSUE THREAD

**Issue by vodik** [svinota/pyroute2#338]
Here's a snippet to reproduce the problem:

```python
import pyroute2

ipdb = pyroute2.IPDB()
vlan = ipdb.create(
    kind='macvlan',
    link=ipdb.interfaces['tun0'],
    ifname='macvlan0',
    mode='bridge'
)

try:
    vlan.commit()
except Exception:
    pass

print(ipdb.interfaces['macvlan0'])  # Expect KeyError
```

I would expect a `KeyError`, but instead I get this:

```
{'index': 0, 'kind': 'macvlan', 'ipaddr': [], 'ipdb_priority': 0, 'link': 3, 'mode': 'bridge', 'ifname': 'macvlan0', 'vlans': [], 'ports': [], 'ipdb_scope': 'create'}
```

Am I maybe doing something wrong?

Anyways, the complication I hit, then, is my macvlan wrapper is throwing exceptions on cleanup (`__del__` specifically), since it tries to delete a interface that isn't present on the system.

**Comment by vodik** [comment]
I realize you can't attach a macvlan onto a tunnel. You rightfully get EINVAL - I caught this in practice by accident trying to test something over our corporate VPN.

More succinctly, the EINVAL doesn't invalidate the `ipdb.interfaces` entry.

**Comment by svinota** [comment]
Yep, interfaces failed to be created stay in the DB with `ipdb_scope="create"` — that's to make it possible to fix the object and try to create it again. Probably, I have to mention it in the docs more clearly.

**Comment by vodik** [comment]
Aaah, okay, my bad. Feel free to close this issue.

**Comment by svinota** [comment]
I leave it open for a while, to fix the docs.
