### ISSUE TITLE
support for onlink routes

### ISSUE THREAD

**Issue by nickhuber** [svinota/pyroute2#343]
with iproute2 you can do something like `ip route add 192.168.0.0/24 via 10.100.0.1 onlink dev enp3s0` and get a route like `192.168.0.0/24 via 10.100.0.1 dev enp3s0 onlink`

I can't figure out if there is a way to set RTNH_F_ONLINK to achieve this right now

**Comment by svinota** [comment]
Indeed, it's missing. Thanks for heads-up.

**Comment by svinota** [comment]
Even worse, there is a bug in the library in that part. Thanks again. Fixing.

**Comment by svinota** [comment]
So, right now it is possible to create onlink routes just by passing `flags=4`, see examples here: deaf982dae85e104ffda53f6b39401751ef585ce Works both for normal and multipath routes.

Mnemonic flags support will be added a bit later.

**Comment by svinota** [comment]
Flags constants added into the module, refer to the code: 1c456cc78b3987a9164955ee3a59f5ea20e38bf6

**Comment by svinota** [comment]
String flags support added:
```
    ipr.route('add', dst=…, gateways=…, oif=…, flags=['onlink', …])
```

See also the code: 0bfa3e7fda437e0c4a5dae4e4042ff88f35897f3

**Comment by svinota** [comment]
Closing the issue. Will you have any questions/comments — feel free to add or reopen the ticket.
