### ISSUE TITLE
Package licensing

### ISSUE THREAD

**Issue by NicolasT** [svinota/pyroute2#347]
If I'm not mistaken, this package is licensed under the GPLv2+ license, as well as Apache2, given https://github.com/svinota/pyroute2/blob/5f1ec88a6061d3637a00183e3eb7d7166889992e/README.license.md

There seem to be at least 2 files not properly representing this:
- The `Makefile` at the root of this repository claims the package to be GPLv2+ (https://github.com/svinota/pyroute2/blob/f142ddca112fc50f83ca3bd3354b1cb22be37360/Makefile#L5)
- The RPM Spec file sets the package version to `GPLv2+` (https://github.com/svinota/pyroute2/blob/5f1ec88a6061d3637a00183e3eb7d7166889992e/packages/RedHat/python-pyroute2.spec#L10) whilst at the same time shipping `LICENSE` files for both GPL2 as well as Apache2 (https://github.com/svinota/pyroute2/blob/5f1ec88a6061d3637a00183e3eb7d7166889992e/packages/RedHat/python-pyroute2.spec#L55)

Is this intentional, or an oversight after dual-licensing the package? If it is intentional, could you clarify that the package, when built *without* using its `Makefile` or the provided `spec` file, *is* intended to be dual-licensed (or, licensed at choice from the list in `README.license.md`)?

**Comment by svinota** [comment]
That's just an oversight. To be fixed.

**Comment by svinota** [comment]
Fixed. As written in `README.license.md`: you are free to choose, under which license from these two will you use pyroute2 in your project.

**Comment by svinota** [comment]
Thanks for the heads-up, by the way. And if there are questions left — don't hesitate to ask.

Otherwise feel free to close the ticket, if you believe the issue is resloved.

**Comment by NicolasT** [comment]
Thank you for the quick feedback and fix! I assumed it was an oversight, but this is the kind of things that worries legal people (and rightly so).

Thank you for working on this package, and providing it as free software!

**Comment by svinota** [comment]
Thanks :) The fixed package will be provided with the next release.
