### ISSUE TITLE
Setting ifalias via IPdb causes an error, but does work.

### ISSUE THREAD

**Issue by tuxis-ie** [svinota/pyroute2#349]
I'm trying to set IFLA_IFALIAS using IPDB().

```
def Ifalias(iface, alias):
    print("Setting alias of interface %s to %s" % (iface, alias))
    global ip
    i = ip.interfaces[iface]
    i['ifalias'] = alias
````

If I run this, I get the following error:
```
Traceback (most recent call last):
  File "./ypconfig", line 60, in <module>
    Netlink.Todo(cur, new)
  File "/home/mark/src/ypconfig/lib/ypconfig/Netlink.py", line 148, in Todo
    ip.commit()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/main.py", line 909, in commit
    commit_mask=phase)
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/interface.py", line 925, in commit
    raise error
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/interface.py", line 743, in commit
    transaction.wait_all_targets()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/transactional.py", line 468, in wait_all_targets
    raise CommitException('target %s is not set' % key)
```

However, the ifalias is correctly set:
```
45: foobar@eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:02:b3:2b:a1:1d brd ff:ff:ff:ff:ff:ff
    alias Cust: DB0220
```

**Comment by svinota** [comment]
Thanks for the issue, fixing.

**Comment by tuxis-ie** [comment]
Is this also an issue for setting mtu the same way?

**Comment by svinota** [comment]
nope, setting mtu is not an issue:
```
In [22]: with ip.interfaces.vlan300 as i:
   ....:     i.mtu = 1400
   ....:     

In [23]: ip.interfaces.vlan300
Out[23]: {'family': 0, 'txqlen': 1000, 'ipdb_scope': 'system', 'index': 1102, 'operstate': 'DOWN', 'num_tx_queues': 1, 'group': 0, 'carrier_changes': 0, 'ipaddr': [], 'vlan_flags': 0, 'neighbours': [], 'vlan_id': 303, 'ifname': 'vlan300', 'promiscuity': 0, 'linkmode': 0, 'ifalias': 'bala', 'kind': 'vlan', 'broadcast': 'ff:ff:ff:ff:ff:ff', 'link': 6, 'address': '42:37:ef:8a:7d:51', 'vlans': [], 'ipdb_priority': 0, 'gso_max_segs': 65535, 'gso_max_size': 65536, 'qdisc': 'noop', 'mtu': 1400, 'num_rx_queues': 1, 'carrier': 1, 'flags': 130, 'ifi_type': 1, 'proto_down': 0, 'ports': []}
```

**Comment by tuxis-ie** [comment]
Ah, that was pebkac on my end.

It doesn't work with ```i['mtu']```, but is does work with ```i.mtu```.

**Comment by svinota** [comment]
Should work in both notations. Actually, `i.mtu` is transparently translated to `i['mtu']`, so they are equal; the same for all attributes, be it `i.address` or `i.whatever`. They should be available for setting/getting via `i['address']`, `i['whatever']` etc, and via `i.set_address(…)`, `i.set_mtu(…)` — these methods return the object itself, so the calls can b stacked, as `i.set_mtu(…).set_whatever(…)`.

If it doesn't work — pls report, it is a bug.

**Comment by svinota** [comment]
With mtu there may be an issue, if you're trying to set on a vlan interface mtu bigger than on the parent interface, btw. Not sure, if it's the case.

**Comment by svinota** [comment]
Setting ifalias fixed, though via a hack — but it's how it works in the kernel, unfortunately.

The way it is implemented may affect the performance. If you have any comments or issues with that feature — pls post them here.

**Comment by tuxis-ie** [comment]
I have seen the same issue with mtu, might it be related?

**Comment by svinota** [comment]
Should not be related, but let me check it first.

**Comment by svinota** [comment]
Can not confirm the MTU issue. Please file a separate ticket, if you encounter it — we'll try to investigate and fix.
