### ISSUE TITLE
Help needed: Changing interfaces

### ISSUE THREAD

**Issue by tuxis-ie** [svinota/pyroute2#350]
Hi,

I'm working on a python-script that configures a Linux system according to the Yaml-configuration file. Since this is meant to be running on routers, I'm using IPDB(), so that configuration errors can be catched, and we can implement a rollback.

However, while creating and removing interfaces/addresses works fine, ***changing*** interfaces seems to  be an issue. Changing a vlan id does not seem to be possible, so I tried to implement that as a delete and create, but that fails every now and then as well.

Should I not be using IPDB?

**Comment by svinota** [comment]
It is not possible to change the `vlan_id` on a vlan interface — and it's not an IPDB limitation, it's the nature of vlan interfaces in Linux.

But it must be possible to remove/create the interface. Would you mind to provide tracebacks for the interfaces removal/creation? Thanks a lot!
