### ISSUE TITLE
Extending the set of `kind`s is not possible

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#352]
We have a custom kernel driver that creates a new `kind` of netdevice (new `type` in the `ip link add` command). It is controlled over netlink and exposes its own set of attributes.

Command-line `iproute2` tool allows to create a shared object responsible for handling new types of interfaces, and we have such custom shared object, so our netdevice is controllable over standard `ip link` command, that, thanks to the said shared object, recognizes a few new custom keywords specific to our interface.

However, as far as I understand, `pyroute2` does not allow addition of such `kind`-specific modules. Therefore support for a custom `kind` cannot be introduced without modification of the "core" source code of the module.

It would be very useful to be able to write an extension module for a new `kind` of the interface, import it, register it with the core `pyroute2` and use all IPRoute/IPDB features with the custom interface.

**Comment by svinota** [comment]
Yep, you're right. The prototype will be ready the next week, I'll ping you here.

**Comment by svinota** [comment]
Sorry for the delay, it was too complicated change.

The prototype is in the master branch, I think to keep the API — and later extend it (add API versioning, etc). The docs are not ready yet, but you can take one of existing plugins to use as an example.

Again, thanks for the FR.

**Comment by svinota** [comment]
And to add a path with plugins, do before spawning any IPRoute/IPDB instances:
```python
from pyroute2 import config
config.data_plugins_path.append("/path/to/your/own/plugins/")
```

**Comment by crosser** [comment]
Thanks! I am on to try it, expect to provide feedback within a few days.

**Comment by svinota** [comment]
Will you have any questions or proposals — don't hesitate to bring it here. Thanks in advance.

**Comment by crosser** [comment]
What is the correct way to specify a character string of fixed size? Element line this:
```
        [IFLA_MYDEV_DEV]       = { .type = NLA_STRING,
                                   .len = DEVICE_NAME_MAX},
```
in `struct nla_policy`

**Comment by svinota** [comment]
There are three built-in string types in the library so far:
1) `asciiz` — encode → `str + '\0'`; decode → up to `'\0'`
2) `cdata` — take the string as is
3) `string` — UTF-8 encoded

There is no strict length limitation, so if you encode `"bala"`, NLA becomes
```
length = 12  # header + data + zero terminator + alignment
data = "bala\0"
```
or
```
length = 8 # header + data
data = "bala"
```

So if you wanna define NLA:
```python
from pyroute.netlink import nla

class mydev(nla):
    nla_map = (('IFLA_MYDEV_UNSPEC', 'none'),  # NLA type 0
               ('IFLA_MYDEV_DEV', 'asciiz'),  …)  # NLA type 1, …
```

And vice verse, upon decoding the library takes into account the real header value, and decodes up to `"\0"` (`asciiz`) or whole (`cdata`, `string`)

**Comment by crosser** [comment]
If (for initial testing) I place my module into pyroute2/netlink/rtnl/ifinfmsg/plugins/ directory, it should be picked up automatically, right? I created the file pyroute2/netlink/rtnl/ifinfmsg/plugins/mykind.py with the following content:
```
from pyroute2.netlink import nla

class mykind(nla):
    prefix = 'IFLA_MYKIND_'
    nla_map = (('IFLA_MYKIND_UNSPEC', 'none'),
               ('IFLA_MYKIND_MYPORT', 'uint32'),
               ('IFLA_MYKIND_MYDEV', 'asciiz'))
```
and I run this:
```
$ export PYTHONPATH=`pwd`
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import IPBatch
>>> from pyroute2.common import hexdump
>>> ipb = IPBatch()
>>> ipb.link('add', ifname='myif0', address='01:02:03:04:05:06', kind='mykind', myport='65535', mydev='aaaaaaaaa')
>>> hexdump(ipb.batch)
'48:00:00:00:10:00:05:06:00:00:00:00:20:23:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:0a:00:03:00:6d:79:69:66:30:00:00:00:0a:00:01:00:01:02:03:04:05:06:00:00:10:00:12:00:0b:00:01:00:6d:79:6b:69:6e:64:00:00'
>>>
```
Additional attributes `myport` and `mydev` are not included in the message. I later added explicit `config.data_plugins_path.append(...)`, but still no dice. What am I missing?

**Comment by svinota** [comment]
You're missing nothing. It's my fault — I forgot to fix one more thing. Will be fixed tomorrow.

Thanks.

**Comment by svinota** [comment]
Ok, it will take one more day to make it properly, not as a hack. Thanks for your patience.

**Comment by svinota** [comment]
Should be a bit better now. The only note: number values (as here `uint32`) should  be provided as numbers in Python, thus `myport="65535"`→`myport=65535`

**Comment by crosser** [comment]
I was able to add the interface with specified parameters. Looks good so far! Thank you!

**Comment by svinota** [comment]
So I close the ticket. Feel free to reopen it or to file another ticket in the case there will be any issues, I will try to fix the things asap.

**Comment by svinota** [comment]
And thanks again. While fixing the issue I managed to finally get rid of some really nasty code.

**Comment by svinota** [comment]
@crosser Pls take a look at https://github.com/svinota/pyroute2/pull/376 — we're going to change a bit the plugin API and it will affect your code.

And let me know, if the new approach will not work for you. Thanks!
