### ISSUE TITLE
Running Pyroute2 on a router will full routing tables renders it unusable

### ISSUE THREAD

**Issue by tuxis-ie** [svinota/pyroute2#354]
It tries to parse all routes, which is way too much. Eating all 8GB memory and using 100% CPU.

ignore_rttables does not help. Please advise.

**Comment by tuxis-ie** [comment]
'Fixed' it by inserting 'return' at https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/route.py#L927

**Comment by svinota** [comment]
Ok, got it. Do you think it may be useful to switch off the whole routes plugin in that case?

And another question, how many routes do you have in all the tables altogether? (I will use that in the stress testing)

**Comment by tuxis-ie** [comment]
I would by default not even load the routes, unless we start messing with them.

On the box at hand, I have this:
[mark@rtr1.bit1.tuxis.net:~] ip ro list | wc -l 
655229
[mark@rtr1.bit1.tuxis.net:~] ip -6 ro list | wc -l 
38542

**Comment by svinota** [comment]
The library already quite some time (from 0.4.2) doesn't load a view by default, but only after the view is requested by the user. So unless one doesn't touch `ipdb.routes`, the routes plugin is not loaded and routes are not parsed at all. The same for `ipdb.interfaces` and `ipdb.rules`.

About the routes number — wow. Quite impressive. And I will try to find a way to deal with it, thanks.

**Comment by tuxis-ie** [comment]
I can send you a full feed via BGP, that will give you the routes. :)
My code does nothing with adding routes, so I can't think of a reason why the routes are loaded.. I'm running 0.4.13.

**Comment by svinota** [comment]
But obviously it does, and the reason may be whichever… (e.g. `dir()` in some place) So let's do that way: I'll add a possibility to enforce plugins to be off. So you will not need to find the trigger in the code. I believe it's the easiest.

**Comment by svinota** [comment]
Not a solution, but may help to mitigate the issue:
```python
from pyroute2 import IPDB
with IPDB(plugins=("interfaces",)) as ipdb:
    …  # the code; ipdb.routes and ipdb.rules will not be available
```

Meanwhile I start the work to rewrite the DB to manage so many routes.

**Comment by svinota** [comment]
For the version 0.5.3 the NDB first release is planned. As for now NDB can handle up to millions of any objects (routes, links, neighbours, addresses, whatever else), so it will never be an issue again.
