### ISSUE TITLE
How do I control vfs of an interface?

### ISSUE THREAD

**Issue by teferi** [svinota/pyroute2#356]
I want  to set attributes of a VF of my PFs.
How do I reproduce something like `ip link set ifname vf 0 vlan 100`.

I've tried 
```
ipr = pyroute2.IPRoute()
ipr.link('set', index=ipr.link_lookup(ifname=ifname), vf=0, vlan=100)
```
But it did not do the trick. There is also no docs on the subject. Is this functionality available in pyroute2?

**Comment by svinota** [comment]
Unfortunately, just now I have no access to SR-IOV devices, so I can not debug it :| I'll try to understand, what's going on, from the kernel sources, but I'm not sure it will be easy.

**Comment by teferi** [comment]
I can share this link https://github.com/vishvananda/netlink/blob/58c32ae2d72285baf322aaff05213c2fba8fb8a2/link_linux.go#L330 I'll try to see if I can use a low level interface to replicate the command. Will also try to see if I can build a solution and contribute it back to pyroute2. It would probably require a separate interface I guess though.

**Comment by svinota** [comment]
Just to document what's done:
```python
ip.link('set', index=3, vf={'vf': 0, 'vlan': 100})
```
