### ISSUE TITLE
Can't set forward delay on bridge because of CommitException: target br_forward_delay is not set

### ISSUE THREAD

**Issue by blackwithwhite666** [svinota/pyroute2#357]
I try to run tests locally and `test_ipdb.TestExplicit.test_bridge_controls_add` fails with `CommitException: target br_forward_delay is not set`. In other words `set_br_forward_delay(500)` don't work.

The problem happens because kernel store forward delay in jiffies and when option CONFIG_HZ_300 is set (it's default for archlinux) there is some precision loss.
```
$ sudo brctl setfd testbr 500
$ sudo brctl showstp testbr  
 forward delay		 499.99			bridge forward delay	 499.99
```
```
$ zcat /proc/config.gz | grep HZ
CONFIG_HZ_300=y
CONFIG_HZ=300
```

jfyi: seems that tests aren't compatible with new eventlet version (since 0.18.0) because of http://eventlet.net/doc/changelog.html#id9 (no more select.poll after monkey patching).

**Comment by svinota** [comment]
Ough. Thanks, I'l try to fix it.

And thanks about the eventlet notice.

**Comment by blackwithwhite666** [comment]
Thank you for fast reply!

**Comment by blackwithwhite666** [comment]
Maybe it would be simpler to compare actual and expected values of forward delay like this: `|a - b| < epsilon` ?

**Comment by svinota** [comment]
Maybe, maybe. I try to keep the transaction code as generic as it is possible, so give me some time to make the prototype.
