### ISSUE TITLE
Readonly transactions require root

### ISSUE THREAD

**Issue by spanezz** [svinota/pyroute2#359]
Hello,

I just had to rewrite code that used ipdb to use IPRoute instead of ipdb, because I got an error in commit when not running as root.

Root should not be needed in this case, because I'm only enumerating interfaces and addresses. However, I did not find any way to tell ipdb transactions to be readonly. 

```py
        # Not using IPDB because it tries to write on commit on iproute2 0.4.*
        from pyroute2 import IPRoute
        ip = IPRoute()
        for addr in ip.get_addr(label="vlan0"):
            a = addr.get_attr("IFA_ADDRESS")
            if not a.startswith("10."):
                continue
            return a
        #with ipdb.interfaces.veth0 as interface:
        #    for addr in interface["ipaddr"]:
        #        if not addr[0].startswith("10."):
        #            continue
        #        return addr[0]
```

**Comment by svinota** [comment]
Yes, I've got it. Actually, the transaction is not needed here at all, but the syntax forces it to be started — a design mistake in the library, I would say.

Would it be ok for you with the syntax like that:
```
with ipdb.interfaces.veth0.ro as interface:
    …
```
(notice `.ro` after veth0)

If it's ok, I would introduce it in the library asap.

**Comment by spanezz** [comment]
Thanks, that'd be perfect. I'd also use it when running as root, if I only wanted to do inspection of the network configuration, to make sure I do not accidentally change things.

**Comment by svinota** [comment]
Should be fixed with the syntax as above, use the `.ro` property to get simple context manager from any transactional object — interface, route or rule. No transaction will be started by `with`, thus no `commit()`.

Please notice, `.ro` doesn't turn the object into the read-only state yet. Maybe, it should, what do you think about it?

**Comment by spanezz** [comment]
I'd say it depends how much work it is going to take: it's already good enough to know that if I use `.ro` I'm not going to accidentally tamper the system configuration.

**Comment by svinota** [comment]
Not so much work. Now the `.ro` property returns a read-only object copy, linked to the inteface data (so it reflects, e.g., ip address changes in the real time), not a dummy context manager.

I think to keep this API, maybe improve a bit, but no incompatible changes after the next release.
