### ISSUE TITLE
Setting an interface name via IPRoute.link("set", ... no longer works

### ISSUE THREAD

**Issue by johnsom** [svinota/pyroute2#365]
I have been using the following code to move an interface into a netns and rename it in the process:

        with pyroute2.IPRoute() as ipr:
            # Move the interfaces into the namespace
            idx = ipr.link_lookup(ifname='ens5')[0]
            ipr.link('set', index=idx, net_ns_fd='test-netns',
                     IFLA_IFNAME='eth1')

But this recently stopped working.  I am on a fully patched ubuntu 16.04.2 instance (Linux <hostname> 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

A sample script to show the problem:
import pyroute2

with pyroute2.IPRoute() as ipr:
    idx = ipr.link_lookup(ifname="ens5")[0]
    ipr.link('set', index=idx, IFLA_IFNAME='eth1')

I have tried using "name" instead of "IFLA_IFNAME" with no luck either.

However, when I do this via the command line it still works as expected:
ip link set ens5 name eth1
ip link set ens5 netns test-netns name eth1

Both work as expected.

**Comment by johnsom** [comment]
Version 4.13 works, 4.14 does not

**Comment by svinota** [comment]
Oh. Thanks for heads-up, fixing.

**Comment by svinota** [comment]
Fixed, rolled out 0.4.15 to have the fix in pypi.

The issue was that I tested only the «short» NLA notation in the `IPRoute` syntax, e.g.
```python
ipr.link('set', index=idx, ifname='new_name')
```
And occasionally dropped the «full» notation, since it wasn't neither tested, nor used in my code:
```python
ipr.link('set', index=idx, IFLA_IFNAME='new_name')
```

Now it should be fixed and both are tested and should work. Thanks again for the critical issue.

**Comment by johnsom** [comment]
Confirmed, this fixes the issue.

**Comment by svinota** [comment]
Thanks for the confirmation!
