### ISSUE TITLE
Can't close IPDB

### ISSUE THREAD

**Issue by cronnosli** [svinota/pyroute2#366]
My script return this exception when I run this code:

'IPDB' object has no attribute 'close'

 def removeDefaultRoute(self, gatewayToRemove):
    ip = IPDB()
    try:
      with ip.routes[{'gateway': gatewayToRemove}] as r:
        print "Will remove this gateway: " + gatewayToRemove
        r.remove()
    except:
      print "cant delete"
    ip.close()

  def addDefaultRoute(self, gatewayToAdd):
    ip = IPDB()
    spec = {'dst': 'default', 'gateway': gatewayToAdd}
    ip.routes.add(spec).commit()
    ip.close()

**Comment by svinota** [comment]
There are two methods to close the DB, and both are in docs:
* use `release()` method; the `close()` is reserved for socket objects (`IPRoute` etc.)
* use context managers:
```python
with IPDB() as ipdb:
    # do some stuff
    …
    …
# here the DB is closed automatically after exit from `with`
```
