### ISSUE TITLE
Not able to send big (more than 16384 bytes) message over netlink

### ISSUE THREAD

**Issue by saurabhsinghmaurya** [svinota/pyroute2#367]
I am trying to send a big message over Netlink but it's not getting transmitted. I am not getting any error message or exception.

Please tell me, how to send a big (more than 40k bytes) message (dict or list )  by using "send to".

example 
**nl_sock.sendto(req.buf.getvalue(), (port, 0))**
Here, The size of "req.buf.getvalue()" is more than 16384 bytes.

**Comment by svinota** [comment]
Strange. What's on the kernel side? Partial data, no data at all? Any warnings from the netlink subsystem? What is the message format? What is the netlink protocol? What's in the message headers?

**Comment by saurabhsinghmaurya** [comment]
Thanks for reply 
What's on the kernel side?  
   ** libnl** 
We are using genl_register_family(&cm_gnl_ops)) to to register Generic Netlink family.

Partial data, no data at all?
We are sending a list with very large number of elements.
temp_list   <= assume this is the list
msgpack.packb(temp_list) // using MessagePack lib

**Message format**
    req['cmd'] = CM_C_SET_CM  # CMD
    req['version'] = 1  # VERSION
    req['header']['type'] = nl_sock.prid  # MSG_TYPE
    req['header']['flags'] = pyroute2.netlink.NLM_F_REQUEST  # MSG_FLAGS
    req['header']['sequence_number'] = 1  # msg['header']['sequence_number']
    req['header']['pid'] = nl_sock.epid
    req['attrs'].append(['CM_A_BMSG', msgpack.packb(temp_list)])  // binary data
    req.encode()
    **nl_sock.sendto(req.buf.getvalue(), (port, 0))**

===================================
 _nla_map = (('CM_A_UNSPEC', 'none'),
               ('CM_A_MSG', 'asciiz'),  # text
               ('CM_A_BMSG', 'cdata'))_
Any warnings from the netlink subsystem?
**NO**

**We are thinking that the issue is happening because we are sending more than 16384 (2^14) bytes in a single "send to" function and send buffer or receive buffer (at kernel) is not more than 2^14. Is it a correct perception?**

**Comment by svinota** [comment]
The max NLA size should be `uint16 == 0xffff == 65535`; so  that should not be the cause.

The `SO_SNDBUF` right now is 32768. You may try to play with that by `setsockopt()`:
```python
from socket import SOL_SOCKET
from socket import SO_SNDBUF

nl_sock = GenericNetlinkSocket(…)
nl_sock.setsockopt(SOL_SOCKET, SO_SNDBUF, buffer_size)
```

Anyways that's really bad that the data is silently discarded without an error either from the kernel side or from the library, so I mark that as a bug. Give me some time until the next week to reproduce and play a bit with that.

Thanks for the issue.

**Comment by svinota** [comment]
Please look at the example:

https://github.com/svinota/pyroute2/tree/master/examples/generic
https://github.com/svinota/pyroute2/blob/master/tests/general/test_generic.py

I managed to send 65000 bytes w/o any issues and w/o any additional `setsockopt()`. The kernel version 4.11 (the example requires kernel 4.10+, but it matters only for the kernel module API — the kernel API was changed in 4.10). The protocol itself wasn't changed, the same userspace code works on earlier kernel version.

**Comment by svinota** [comment]
An attempt to send more data than the kernel can handle leads to an error:
```
error: [Errno 90] Message too long
```

So it looks like the code behaves correctly.

**Comment by svinota** [comment]
So, possible exceptions (see the test code above, https://github.com/svinota/pyroute2/commit/86e3f0cd5a9ffff8cfcdfdf73d438923e05db62d):
* `socket.error == 90` — either NLA or the whole message exceed netlink limits (they're slightly lower then the encoding format)
* `struct.error` — either NLA or the whole message exceed the encoding format limits (max length: uint16 for NLA and uint32 for the whole message)

`SO_SNDBUF` matters only if the kernel code works slower than the userspace (not the case with Python), and it doesn't affect one message, whatever big may it be.

If there is no error, that means that the data successfully passed the netlink API on the kernel side and was transmitted to the kernel module code. There should be the debugging directed.

**Comment by saurabhsinghmaurya** [comment]
Thanks for detailed answer

I am using kernel version is 2.6.32 and increased socket buffer size at kernel side by using "nl_socket_set_buffer_size" function. Now it's working fine for a higher message size (up to 65535 bytes).

Once again, thanks for help

**Comment by svinota** [comment]
Thanks a lot for the report — I will add the information into the docs.

**Comment by svinota** [comment]
Finally, simply increased the default `SO_SNDBUF` as `nl_socket_set_buffer_size` does the same.
