### ISSUE TITLE
iproute.flush_route deletes more than asked

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#378]
Hi Peter, long time to see !  :)

I've just hit the following bug in pyroute2:
```
>>> import pyroute2
>>> ipr = pyroute2.IPRoute()  # pylint: disable=no-member
>>> 
>>> for r in ipr.get_routes(table=254):
...    print r
... 
{'family': 2, 'dst_len': 24, 'proto': 2, 'tos': 0, 'event': 'RTM_NEWROUTE', 'header': {'pid': 6870, 'length': 60, 'flags': 2, 'error': None, 'type': 24, 'sequence_number': 261}, 'flags': 0, 'attrs': [('RTA_TABLE', 254), ('RTA_DST', '240.97.132.0'), ('RTA_PREFSRC', '240.97.132.200'), ('RTA_OIF', 374)], 'table': 254, 'src_len': 0, 'type': 1, 'scope': 253}
>>> ipr.flush_routes(family=pyroute2.common.AF_MPLS)
>>> for r in ipr.get_routes(table=254):
...        print r
... 
[nothing]
```

So, _ipr.flush_routes(family=pyroute2.common.AF_MPLS)_ deleted all the routes, the _family_ filter was not taken into account.  

I've observed the same issue with _proto_ as a filter to _flush_routes_.

I've had a look at the code, and nothing obvious stands out, flush_routes seems to rely on get_routes that *does* properly take into account kwargs to filter.

**Comment by svinota** [comment]
Bad bug. Will be fixed tonight. Thanks, Thomas!

**Comment by tmmorin** [comment]
Thanks for being so reactive.

I'm hitting this bug in a test that I'm pushing to the openstack CI of networking-bagpipe, solving it *and* doing a pyroute2 release would help having the jobs pass !  But if the timing isn't right for a release, this is absolutely ok for me to wait as well.

**Comment by svinota** [comment]
@tmmorin Thomas, pls check if it works for you now.

If it's ok, the release will be ready on Friday.

**Comment by tmmorin** [comment]
It seems that it's solved.
Many thanks!

**Comment by svinota** [comment]
0.4.17 is out
