### ISSUE TITLE
ipdb: ipdb.commit does not commit routes

### ISSUE THREAD

**Issue by badicsalex** [svinota/pyroute2#379]
The following commit:
5c6dcaf454 ipdb: mitigate ports/bridge removal issue 
Broke route commits, because route transactions don't have a 'kind' field, so they are removed from the transactions list.
I wonder why that "if kind:" line is there.

**Comment by svinota** [comment]
That's a mistake, not catched with tests. Thanks for the issue. Will be fixed tonight.

**Comment by svinota** [comment]
Shoud be fixed now. Thanks again for the bug record!

I believe it deserves a bugfix release, so I prepare it asap.

**Comment by badicsalex** [comment]
This was very fast, thank you :)

**Comment by svinota** [comment]
That was really critical :) Please check, if it works for you now.

**Comment by badicsalex** [comment]
It does work (well, at least our unit tests run again with your fix).

**Comment by svinota** [comment]
Many thanks!

(… and if you believe that some tests may be better to include in the library CI, you may either try to prepare a pull request, or write here an events/checks sequence so I will write a test myself)

**Comment by badicsalex** [comment]
We only have end-to-end tests of our internal networking component, and we use this library to set up or reset the whole networking of a whole server, basically. I'm not sure it's useful, but what we do is:

1. Set up ethernet interfaces (with IPs)
2. Set up vlans (with IPs)
3. Set up routing
4. ipdb.commit()

"set up" means delete everything and then recreate according to a settings file. We only noticed that routing was never set up, no matter how many ipdb.commit()-s we sprinkled in the code.

Actually we have ipdb.commit()-s at many places (e.g. between deleting and recreating routing, or between ethernet and vlan interface creation), because otherwise we got weird errors. I didn't file any bug reports about this, because we thought we are just using the lib wrong, but it would be nice to be able to do with only a single commit.

**Comment by svinota** [comment]
>  I didn't file any bug reports about this, because we thought we are just using the lib wrong, but it would be nice to be able to do with only a single commit.

Agree. Pls don't hesitate to file bugs. If you're using the library wrong — then it must be reflected in the library docs, how to use it correctly. If it's a bug in the code — it must be fixed. In any way it's better to record an issue against that.

Thanks for the feedback :)
