### ISSUE TITLE
ipdb: ipdb.commit() throws exception if interfaces plugin is disabled

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#380]
ipdb = IPDB(plugins=['routes'], mode='implicit')
ipdb.commit()

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 949, in commit
    in self.by_name.values() if x.local_tx.values()]
  File "/usr/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 775, in __getattribute__
    return super(IPDB, self).__getattribute__(name)
AttributeError: 'IPDB' object has no attribute 'by_name'

**Comment by svinota** [comment]
oops. Will be fixed asap. Thanks!

**Comment by PaulSD** [comment]
Awesome!  Thanks for the super fast response!

**Comment by svinota** [comment]
Should be fixed now.

**Comment by PaulSD** [comment]
Confirmed.  Working now.
Thanks!

**Comment by svinota** [comment]
Thank! Closing the issue.
