### ISSUE TITLE
ipdb: Exception on route commit triggers another exception

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#381]
ipdb = IPDB(mode='implicit')
ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='1.1.1.1')  # 1.1.1.1 is not a valid gateway, so this route will be rejected
ipdb.commit()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 979, in commit
    self.commit(transactions=snapshots, phase=2)
  File "/usr/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 975, in commit
    commit_mask=phase)
  File "/usr/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 462, in commit
    del route_index[route_key]
KeyError: RouteKey(dst='10.0.0.0/24', scope=0, table=2, priority=None, oif=None)

**Comment by PaulSD** [comment]
BTW, the docs don't show how to create a route in a non-default table.
This was my first guess, but it didn't work:
ipdb.routes.tables[2].add(dst='10.0.0.0/24', gateway='10.10.10.1')
This seems to be the right way?
ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='10.10.10.1')

**Comment by svinota** [comment]
> This seems to be the right way?
> ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='10.10.10.1')

Yep. You're right, it should be in the docs.

About the exception: agree. Expect the fix tomorrow.

**Comment by svinota** [comment]
The exception should be fixed now. Pls note, that the route continues to exist in the database even after the `add`+`commit` failure. The reason is that you're able to fix the failed record and commit it once again.

The docs are being fixed.

**Comment by PaulSD** [comment]
Confirmed, exception is fixed now!

However, if I make a bunch of changes to routes and one of those routes has an error, then I call ipdb.commit(), I hit three problems:
1) If I just want to drop all remaining changes and start over after an error, there is no ipdb.drop() ... It seems I have to manually loop through each route and call route.drop() ?
2) If I want to print out the remaining uncommitted changes so the user can figure out how to fix the problem, there is no ipdb.review() ... It seems I have to manually loop through the routes and call route.review() ?
3) It appears that ipdb.commit() simply loops through each pending transaction and applies it - it does not treat the series of pending changes as a single "transaction" to be committed.  For my specific use case, I would actually like to make related changes to multiple routes and roll back all changes if any of them fails.  Is there any way to do this, or is this simply out of scope?

Thanks!

**Comment by svinota** [comment]
1. True. I'll add that.
2. Same. Will be done.
3. Nope.

Each commit consists of two phases:
1. Apply the changes and wait for confirmations from OS
2. If there is an exception, run `commit()` recursively with the initial snapshot as the transaction — so all the applied changes in the erroneous transaction will be rolled back.

Each global commit does the same, it loops through all the transactions, but in that way:
1. Collects snapshots
2. Runs *only* phase 1 for all the transaction
3. If there is an error, runs phase 2 with collected snapshosts — rolling back all the applied changes.

So all the applied successful transactions in the global `commit()` should be also rolled back, if there is an exception in one of the transaction. If it is not so, it is a bug. Sorry for so many issues in the global commits, and really many thanks for the feedback — thus it becomes more polished.

**Comment by PaulSD** [comment]
Sorry, I was mis-interpreting the results of my test of a global commit() with multiple changes, and I also mis-understood the phase 1 / phase 2 part when I read through the code to try to understand the test results I thought I was seeing ... After some additional testing, I can confirm that it does actually roll back all changes if any of them fails.

No worries on these issues - I'm more than happy to do testing and provide feedback.  Thanks for all your work on this code, and for being so responsive to feedback!

**Comment by svinota** [comment]
Just now pushed to the master another feature. From now on the interface commit traces the dependent routes and restores the in the case of the failure. That means, that even routes not participating in the transaction will be restored upon exception. The test code: https://github.com/svinota/pyroute2/commit/e0bf4a418a296e3b407a5b0666736f6bbc384000#diff-9936dcf1e586ec12c9fd7855ba838f02R1738

The docs will be ready the next week.

**Comment by svinota** [comment]
Global `review()` and `drop()` done.

**Comment by PaulSD** [comment]
> The exception should be fixed now. Pls note, that the route continues to exist in the database even after the add+commit failure. The reason is that you're able to fix the failed record and commit it once again.

This part doesn't seem to be working right:
```
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> r = ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='1.1.1.1')
>>> r.review()
{'dst': '10.0.0.0/24', 'ipdb_priority': 0, 'metrics': {}, 'encap': {}, 'scope': 0, 'table': 2, 'multipath': (), 'gateway': '1.1.1.1', 'ipdb_scope': 'create'}
>>> ipdb.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 1214, in commit
    commit_mask=phase)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/routes.py", line 478, in commit
    raise error
pyroute2.netlink.exceptions.NetlinkError: (1, 'Operation not permitted')
>>> r.review()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/transactional.py", line 381, in review
    raise TypeError('start a transaction first')
TypeError: start a transaction first

**Comment by svinota** [comment]
That's true. But it wasn't an issue because of the broken `add()` logic. And now it is. Yep, will be fixed tomorrow.

The global calls `review()/drop()/load()/dump()`, introduced recently, highlighted a lot of issues, not all of them are catched by the tests. Thanks for the patience :) And many thanks for the feedback.
