### ISSUE TITLE
fr: ipdb.review()

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#384]
Add global review.

Related: https://github.com/svinota/pyroute2/issues/381

**Comment by PaulSD** [comment]
>>> ipdb = IPDB(plugins=['routes'], mode='implicit')
>>> ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='1.1.1.1')
{'dst': '10.0.0.0/24', 'ipdb_priority': 0, 'metrics': {}, 'encap': {}, 'scope': 0, 'table': 2, 'multipath': (), 'gateway': '1.1.1.1', 'ipdb_scope': 'create'}
>>> ipdb.review()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/main.py", line 1084, in review
    rlist[ifname] = self.routes.tables[table][key].review()
UnboundLocalError: local variable 'ifname' referenced before assignment
>>>

**Comment by svinota** [comment]
Oh Jesus. How did it pass. 

Thanks!

**Comment by PaulSD** [comment]
Looks good now.  Thanks!
