### ISSUE TITLE
ImportError: No module named readline

### ISSUE THREAD

**Issue by vodik** [svinota/pyroute2#387]
So, importing `pyroute2` now attempts to re-exports `Console` from `pyroute2.cli`. The problem here is that then, in turn, imports `readline`.

Which normally is part of a python installs, but its *technically* optional.

Now I don't expect you to work around my intentionally stripped down environment, but is there any chance we could make it optional?

**Comment by svinota** [comment]
Yep sure, let's make it optional. Sorry for the issue, I had to foresee the problem.

Just give me some time to provide a proper fix.

**Comment by vodik** [comment]
Awesome, thanks!

Technically, all you really need to handle the import error on readline and continue without using it. Everything else should continue to work sans completer. The trick I personally like to do is something like:

```python
def _setup_readline(completer):
    import readline
    readline.set_history_length(100)
    readline.parse_and_bind('tab: complete')
    readline.set_completer(completer)
    readline.set_completer_delims(' \t\n.')
```

And just ignore import errors.

**Comment by svinota** [comment]
Could you pls take a look, is it better now?

**Comment by vodik** [comment]
Sorry for the lateness. 👍 works.

Thanks again!
