### ISSUE TITLE
Error when using IPv6 address with leading zero

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#388]
Example with no leading zero (works fine):
```
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> interface = ipdb.create(ifname="test0", kind="dummy")
>>> interface.add_ip("1234::1/64")
{'index': 0, 'kind': 'dummy', 'ipaddr': (), 'ipdb_priority': 0, 'ifname': 'test0', 'vlans': (), 'ports': (), 'ipdb_scope': 'create'}
>>> interface.up()
{'index': 0, 'kind': 'dummy', 'ipaddr': (), 'ipdb_priority': 0, 'ifname': 'test0', 'vlans': (), 'ports': (), 'ipdb_scope': 'create'}
>>> interface.commit()
{'family': 0, 'txqlen': 1000, 'ipdb_scope': 'system', 'index': 52, 'operstate': 'UNKNOWN', 'num_tx_queues': 1, 'group': 0, 'carrier_changes': 0, 'ipaddr': (('1234::1', 64),), 'neighbours': (), 'ifname': 'test0', 'promiscuity': 0, 'linkmode': 0, 'gso_max_size': 65536, 'broadcast': 'ff:ff:ff:ff:ff:ff', 'address': 'd6:fd:2b:94:15:68', 'vlans': (), 'ipdb_priority': 0, 'gso_max_segs': 65535, 'kind': 'dummy', 'qdisc': 'noqueue', 'mtu': 1500, 'num_rx_queues': 1, 'carrier': 1, 'flags': 65603, 'ifi_type': 1, 'proto_down': 0, 'ports': ()}

Example with leading zero (fails):
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> interface = ipdb.create(ifname="test0", kind="dummy")
>>> interface.add_ip("0100::1/64")
{'index': 0, 'kind': 'dummy', 'ipaddr': (), 'ipdb_priority': 0, 'ifname': 'test0', 'vlans': (), 'ports': (), 'ipdb_scope': 'create'}
>>> interface.up()
{'index': 0, 'kind': 'dummy', 'ipaddr': (), 'ipdb_priority': 0, 'ifname': 'test0', 'vlans': (), 'ports': (), 'ipdb_scope': 'create'}
>>> interface.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/ipdb/interfaces.py", line 1057, in commit
    raise error
RuntimeError

**Comment by PaulSD** [comment]
BTW, ipdb/main.py line 990 has a typo:
logging.warning("shutdown error: %s", e)
should be:
log.warning("shutdown error: %s", e)

**Comment by svinota** [comment]
Fixed for interfaces. Fixes for routes/rules will follow later.

**Comment by svinota** [comment]
… or will not. I need your opinion here. An attempt to detect IPv6 addresses among all the attrs (route prefixes, rule attrs etc etc) leads to significant performance penalty. How crucial is this feature in IPDB? So far I think to leave only a warning in the docs that such addresses are not supported, so it's up to developer to «normalize» them.

**Comment by PaulSD** [comment]
Hmmm...

I'm surprised that detecting IPv6 addresses is expensive, especially since ipaddr() in netlink/__init__.py already does it...  Shouldn't the `Transactional` target logic simply match on the encoded inet_pton() values used by netlink rather than the decoded string values for each attribute?  I guess the problem is that the encoded value isn't accessible from `Transactional` and it would be hard to make it available without calculating it twice?  Could the netlink code stash the encoded attrs somewhere temporarily so that `Transactional` can match on them when reading incoming netlink messages?

For my purposes, I would be OK with explicitly normalizing IP addresses ... however, if this is required, it probably would make sense to provide a function to do this rather than requiring the developer to figure out how to properly normalize addresses on their own.  This normalization function should probably just call inet_pton() then inet_ntop() to guarantee that the normalized address will always match the format used when decoding netlink messages.

BTW: This fix for interfaces is incomplete - zeros in octets other than the first octet still cause problems, for example "1234:0100::", and uppercase letters also cause problems, for example "123A::"

Thanks!

**Comment by svinota** [comment]
The issue is that the `Transactional` class is completely agnostic about the attribute's nature. It just compares what is set during the transaction by the user to the feedback from the OS. If the values match each other, OK, otherwise transaction fails.

In some cases it is required to engage some custom match functions, like here: https://github.com/svinota/pyroute2/blob/0.4.18/pyroute2/ipdb/interfaces.py#L77

The approach I tried first in the patch above was too expensive, let alone it wasn't complete, as you mentioned. I'll revert the patch and will try to use this custom match functions. Thanks for the feedback!

**Comment by svinota** [comment]
Maybe not the final variant, but some approximation to the solution. Related tests: https://github.com/svinota/pyroute2/commit/f90be3309481fcb1123d28032ce49e0bdfa246ae#diff-9936dcf1e586ec12c9fd7855ba838f02R141

**Comment by svinota** [comment]
Please take a look, if it will work for you.

**Comment by PaulSD** [comment]
Works for me! Thanks!

I added a few comments on the commit, although the issues I commented on don't affect functionality.

**Comment by svinota** [comment]
Thanks for the review! I really appreciate that.
