### ISSUE TITLE
ipdb: setting the mtu to the current value fails

### ISSUE THREAD

**Issue by badicsalex** [svinota/pyroute2#389]
The following code
```
interface = ipdb.by_name['dummy0']
interface.set_mtu(interface.mtu)
ipdb.commit()
```
Fails with the following message, after 2 seconds: pyroute2.ipdb.exceptions.CommitException: target mtu is not set.

**Comment by svinota** [comment]
Thanks! Right now I'm away from any terminal, so will be fixed tomorrow.

**Comment by svinota** [comment]
Oops. Can not reproduce. Could you pls elaborate more on the platform? The kernel, distro?

**Comment by badicsalex** [comment]
Oh, I'm awfully sorry, it's only present in an older version, and it was not updated in the test framework. I promise to double check on 'master' before reporting again.

**Comment by svinota** [comment]
Np at all. Just a reason to add one more test :)) (https://github.com/svinota/pyroute2/commit/2061d9881170632461a7341d597f48fd89815691)
