### ISSUE TITLE
Changing a route priority (metric)

### ISSUE THREAD

**Issue by chelliwell** [svinota/pyroute2#390]
Tying off my comments in https://github.com/svinota/pyroute2/issues/65, and starting a new thread instead:
I'm looking to change the metric of a (default) route on a particular network interface. I've explored pyroute2, and been able to figure out:

```
>>> import os
>>> os.system('route -n')
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.10.254  0.0.0.0         UG    100    0        0 eth0
0.0.0.0         10.67.240.32    0.0.0.0         UG    700    0        0 ppp0       <- the route metric I want to change
10.67.240.32    0.0.0.0         255.255.255.255 UH    700    0        0 ppp0
192.168.10.0    0.0.0.0         255.255.255.0   U     100    0        0 eth0
0
>>> from pyroute2 import IPRoute
>>> ip = ip = IPRoute()
>>> ifidx = ip.link_lookup(ifname='ppp0')[0]
>>> ip.route("get",dst="0.0.0.0",RTA_OIF=ifidx)
[{'family': 2, 'dst_len': 32, 'proto': 0, 'tos': 0, 'event': 'RTM_NEWROUTE', 'header': {'pid': 1262, 'length': 96, 'flags': 0, 'error': None, 'type': 24, 'sequence_number': 293}, 'flags': 2147484160L, 'attrs': [('RTA_TABLE', 254), ('RTA_DST', '0.0.0.0'), ('RTA_OIF', 1), ('RTA_PREFSRC', '10.67.240.32'), ('RTA_CACHEINFO', {'rta_error': 0, 'rta_id': 0, 'rta_expires': 0, 'rta_ts': 0, 'rta_lastuse': 0, 'rta_tsage': 0, 'rta_used': 0, 'rta_clntref': 1})], 'table': 254, 'src_len': 0, 'type': 2, 'scope': 0}]
```

Hopefully the above is correct!
Struggling now to figure out how to alter the Priority (700) of this route. Can I just 'change' it somehow, or do I need to add a new route and delete the old? If so, is there a quick way to read in the existing, modify just the Priority, and write it all back?

BTW - still wondering if the debugger (pdb module) is required for using pyroute2?

Thanks

**Comment by svinota** [comment]
Using high-level functions like `IPRoute.route()`, it's enough to write arguments like `ipr.route("set", ..., oif=idx, priority=...)`.

Please notice that what the iproute utility calls for metrics, the kernel calls for `priority`, and this library follows the kernel naming scheme. And you will see that the utility also shows the priority after some calculation, while the library shows the "raw" value -- that's done intentionally.

(more details a bit later, when I'm back -- that's a bit tough to manage that from a mobile)

**Comment by svinota** [comment]
The issue with the pdb module should be fixed now.
