### ISSUE TITLE
Only one default route is shown, when both ipv4 and ipv6 is used

### ISSUE THREAD

**Issue by badicsalex** [svinota/pyroute2#391]
If I have an ipv4 default route, and an ipv6 default route, I can only see one of them, as 'default'.
I guess the problem is that RouteKey does not contain family (I put 'family' there, and now I can see both my default routes, but I have no idea what it breaks).

**Comment by svinota** [comment]
True. Will be fixed tomorrow, I have to run tests first. Thanks a lot!

**Comment by dagmoller** [comment]
If i have two or more default routes (not multipath), ipdb only shows one and remove("default") only delete the first one.

**Comment by svinota** [comment]
@dagmoller In the modern Linux kernels two or more IPv4 non-MP default routes should not work anyways since really long time ago (I can look in the logs). It means, that the record is still visible in the table (just not to break old utilities), but doesn't affect anything.

**Comment by svinota** [comment]
@badicsalex fixed. To reference the records:
```python
ipdb.routes[{'dst': 'default', 'family': AF_INET}]
ipdb.routes[{'dst': 'default', 'family': AF_INET6}]
```

Or, if the record is in some other table than the default:
```python
ipdb.routes.tables[tnum][{'dst': 'default', 'famliy': AF_INET}]
ipdb.routes.tables[tnum][{'dst': 'default', 'famliy': AF_INET6}]
```

Simple reference `ipdb.routes['default']` in such cases will return only one of the records, and it's impossible to predict, will it be IPv4 or IPv6.

**Comment by badicsalex** [comment]
Thanks, this is good for us (we reference the routes via the full route entry for deletion anyway). BTW, I love the autodetection, very helpful.
