### ISSUE TITLE
interface.down() issue :  'int' object has no attribute 'table'

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#392]
I see this, since 0.4.18 (was ok in 0.4.17):
```
 File "/opt/stack/new/networking-bagpipe/networking_bagpipe/bagpipe_bgp/vpn/ipvpn/mpls_linux_dataplane.py", line 222, in vif_unplugged
    i.down()
  File "/opt/stack/new/networking-bagpipe/.tox/dsvm-fullstack/local/lib/python2.7/site-packages/pyroute2/ipdb/transactional.py", line 209, in __exit__
    self.commit()
  File "/opt/stack/new/networking-bagpipe/.tox/dsvm-fullstack/local/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 670, in commit
    if record['key'].table != 255:
AttributeError: 'int' object has no attribute 'table'
```

The triggering code is:

```python
with self.ip.interfaces[interface] as i:
    i.down()
```

where `interface` is a string with the name of an interface and `self.if = pyroute2.IPDB()`

( full code at https://github.com/openstack/networking-bagpipe/blob/master/networking_bagpipe/bagpipe_bgp/vpn/ipvpn/mpls_linux_dataplane.py#L222 )

**Comment by svinota** [comment]
Sorry for the delay, I'm a bit, well, overseas from a normal terminal :) the fix will be ready tomorrow, once I'm back.

**Comment by svinota** [comment]
@tmmorin , does it work like that on the master? Is there any mocking in the tests that could affect?

Right now I see no reason there to have an integer, so I'm a bit puzzled :|

**Comment by tmmorin** [comment]
This is not a unit test, but a functional test where no mocking is done.
I haven't tested master, and can't easily do it (also away from a real box&keyboard)

**Comment by tmmorin** [comment]
After some more digging, I've now a better idea about what triggers this error: the route for which record['key'] is not a RecordKey but an int is an mpls route, created by this piece of code [1]:

```
        ip = pyroute2.IPDB()

        req = {'family': pyroute2.common.AF_MPLS,
               'oif': self.ip.interfaces[interface].index,
               'dst': label,  # FIXME how to check for BoS?
               'via': {'family': socket.AF_INET,
                       'addr': ip_address}
               }

        req.update({'proto': RT_PROT_BAGPIPE})
        ip.routes.add(route).commit()
```
[1] https://github.com/openstack/networking-bagpipe/blob/master/networking_bagpipe/bagpipe_bgp/vpn/ipvpn/mpls_linux_dataplane.py#L192-L200

**Comment by tmmorin** [comment]
I believe the issue is that for an MPLS route, the key is never a RouteKey:

https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/routes.py#L728

**Comment by svinota** [comment]
Oh. Ok, will fix it asap. Thanks!

**Comment by tmmorin** [comment]
I see the 'waiting-for-input' flag on this one.
Is there something missing in the analysis of the issue, or where I could help ?

**Comment by svinota** [comment]
No, it was my mistake. Sorry for it takes so long time.

**Comment by svinota** [comment]
Pls check if it is better now. If it is, I backport it to 0.4.x and cut a hotfix release today.

**Comment by tmmorin** [comment]
I'm testing right now.

**Comment by tmmorin** [comment]
It does indeed solve the issue.
Thanks!

**Comment by svinota** [comment]
Tonight will be the next release.

**Comment by svinota** [comment]
0.4.20 uploaded to pypi.
