### ISSUE TITLE
ipdb: routes with same prefix and different priority not handled properly

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#394]
The kernel allows multiple routes for the same prefix with different priorities:
```
# ip route add 10.0.0.0/24 via 10.1.1.1 table 2
# ip route add 10.0.0.0/24 via 10.1.1.1 table 2 metric 10
# ip route add 10.0.0.0/24 via 10.1.1.1 table 2 metric 11
# ip route show table 2
10.0.0.0/24 via 10.1.1.1 dev eth0 
10.0.0.0/24 via 10.1.1.1 dev eth0 metric 10 
10.0.0.0/24 via 10.1.1.1 dev eth0 metric 11 
```

pyroute2 doesn't handle this situation properly:
```
>>> from pyroute2 import IPDB
>>> ipdb = IPDB()
>>> ipdb.routes.tables[2]
[{'metrics': {}, 'oif': 3, 'dst_len': 24, 'family': 2, 'proto': 3, 'tos': 0, 'dst': '10.0.0.0/24', 'flags': 0, 'ipdb_priority': 0, 'priority': 11, 'scope': 0, 'encap': {}, 'src_len': 0, 'table': 2, 'multipath': (), 'type': 1, 'gateway': '10.1.1.1', 'ipdb_scope': 'system'}]
```

(IPDB only sees one of the three routes.)

It looks like the issue is that the 'priority' field in 'RouteKey' is not marked as 'required' ... In other words, I think 'RouteKey._required' in ipdb.route.py should be 4 instead of 3.

The reason this is a problem for me is that I need to change the route priority with zero downtime.  If I change the priority of a route in pyroute2, this is handled around line 410 of ipdb/route.py, which checks whether RouteKey will change, and if so it deletes the old route first then adds the new route.  Unfortunately, this means there is a brief period of time where the route doesn't exist, and that is a problem for me.

My first thought was "maybe there is a way to modify pyroute2 so that it will actually change the existing route rather than deleting and re-adding it".  However, it turns out that the kernel itself doesn't support that: http://lkml.iu.edu/hypermail/linux/net/0504.3/0017.html

So, my second thought was "maybe I can manually add then remove the route", but this doesn't work either due to the bug described above:
```
>>> ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='10.1.1.1', priority=10)
>>> ipdb.commit()
>>> ipdb.routes.add(table=2, dst='10.0.0.0/24', gateway='10.1.1.1', priority=11)
>>> ipdb.commit()
>>> for r in ipdb.routes.tables[2]:
...  if r.priority == 10:
...    r.remove()
```
(This `for` loop never finds the route with priority=10)

Is there a better way to solve this problem?  For example, is there any good way to change pyroute2 this so that the new route will be added before the old route is deleted when the priority is changed?

**Comment by svinota** [comment]
Actually, the way you tried should work, and I believe that's a bug that it doesn't. Let me play a bit with the issue, I believe we can manage that in either way.

**Comment by svinota** [comment]
Pls try the latest master. It may help a bit.

To refer routes:
```python
# get only one route by prefix, regardless of the priority (only table 254)
ipdb.routes['10.0.0.0/24']
# get the route using the priority (only table 254)
ipdb.routes[{'dst': '10.0.0.0/24', 'priority': 10}]
# iterates through all the tables:
ipdb.routes.filter({'dst': '10.0.0.0/24', 'priority': 10})
# get the route from a specific table
ipdb.routes.tables[tnum][{'dst': '10.0.0.0/24', 'priority': 10}]
# iterates only through the specified table:
ipdb.routes.tables[tnum].filter({'dst': '10.0.0.0/24', 'priority': 10})
```

**Comment by PaulSD** [comment]
This fixes my issue.  Thanks!

However, shouldn't the default IPv6 priority be 1024, not 256?
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/route.c?h=v4.12#n1877
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/ipv6_route.h#n60

**Comment by svinota** [comment]
Indeed. Fixed too. Thanks!
