### ISSUE TITLE
ipdb: error adding route with src address

### ISSUE THREAD

**Issue by dagmoller** [svinota/pyroute2#395]
ipdb.routes.add(src = "10.5.1.1", dst = "10.5.1.0/24", oif = 0, table = 101)
ipdc.commit()

Traceback (most recent call last):
  File "./fwconfig.py", line 144, in <module>
    ipdb.commit()
  File "/usr/lib64/python2.7/site-packages/pyroute2/ipdb/main.py", line 1178, in commit
    commit_mask=phase)
  File "/usr/lib64/python2.7/site-packages/pyroute2/ipdb/routes.py", line 478, in commit
    raise error
pyroute2.ipdb.exceptions.CommitException: target src is not set

**Comment by svinota** [comment]
pls use `prefsrc`:
```
ip.routes.add(prefsrc = "10.5.1.1", dst = "10.5.1.0/24", oif = 0, table = 101).commit()
```

**Comment by dagmoller** [comment]
using prefsrc works...

**Comment by svinota** [comment]
Thanks! I have to check the docs then.

**Comment by svinota** [comment]
Updated docs will be published asap.

The «src» NLA exists, actually, but it's used in another scenarios. What is called «src» by iproute2, is RTA_PREFSRC, thus it's reflected as «prefsrc» in the library.

**Comment by dagmoller** [comment]
Thanks...
