### ISSUE TITLE
Support for the vlan action for TC

### ISSUE THREAD

**Issue by maelk** [svinota/pyroute2#399]
Hello,

The vlan action for TC filters is not currently supported. I have added support for this. The file comes as pyroute2/netlink/rtnl/tcmsg/act_vlan.py and need to be imported from pyroute2/netlink/rtnl/tcmsg/common_act.py  . The plugins dictionnary needs to be extended to to include this new plugin. Could you please give some feedbacks on this ?

I unfortunately could not attach the files directly, so I added the .txt extension to the filename
[act_vlan.py.txt](https://github.com/svinota/pyroute2/files/1183456/act_vlan.py.txt)
[common_act.py.patch.txt](https://github.com/svinota/pyroute2/files/1183457/act_vlan.patch.txt)

Thank you!

**Comment by svinota** [comment]
Thanks a lot, I'll take a look on the weekend!

Meanwhile, could you pls prepare a pull request, so your contribution will be reflected in the project's log as your commit(s)?

**Comment by svinota** [comment]
Closing the ticket as #402 is merged.
