### ISSUE TITLE
Feature request: improve netns support

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#404]
It would be nice if `NetNS` support was better isolated from the underlying nuts and bolts, and more in line with the rest of `pyroute2`/`IPRoute` design:

1. Namespace creation "in exclusive mode" requires import of `os` for `O_CREAT` and `O_EXCL` (by the way, there is an error in the documentation: it mentions `O_EXIST` flag. There is no such flag, `O_EXCL` must be used). In my opinion, it should use an own kwarg for that.
2. On attempt to create (exclusively) existing / remove non-existent namespace, `OSError` is raised. It should better be transposed into a `NetlinkError`.
3. `link('set',...)` accepts `Int` or `String` (netns name) for `net_ns_fd` kwarg. It would be logical if it could _also_ accept a ref to a `NetNS` object.

And somewhat related: it should be documented how does one move an interface out of a namespace back into the "default" namespace. I understand that one needs `link('set, ..., net_ns_fd=0)`, correct?

**Comment by svinota** [comment]
As far as I understand, `net_ns_fd=0` should not work.

To move an interface to a netns, one should open corresponding `/proc/<pid>/ns/net` and pass it to `net_ns_fd`.

The easiest way is to start a process  in the «default» netns, open `/proc/self/ns/net` and save the fd, change the netns to the one that contains the interface and pass the saved fd to `net_ns_fd`.

**Comment by svinota** [comment]
The changes will be done in a few days as soon as I'm back to the normal terminal :)

**Comment by PaulSD** [comment]
Use net_ns_pid=1 (init should always be PID 1 and should always be in the default namespace)

**Comment by svinota** [comment]
Indeed.
