### ISSUE TITLE
IPDB add_ip fails for IPv6 netmask kwarg

### ISSUE THREAD

**Issue by celebdor** [svinota/pyroute2#405]
How to reproduce:

from pyroute2 import IPDB

ip = IPDB()
ip.interfaces[1].add_ip('fd10:0:0:1::5', mask='ffff:ffff:ffff:ffff::')

Expected result:
Address gets added (not yet commited)

Actual Result:
/home/celebdor/.venvs/k8s/lib/python2.7/site-packages/pyroute2/common.pyc in dqn2int(mask)
    286     IPv4 dotted quad notation to int mask conversion
    287     '''
--> 288     return bin(struct.unpack('>L', socket.inet_aton(mask))[0]).count('1')
    289 
    290 

error: illegal IP address string passed to inet_aton

Workaround:

ip.interfaces[1].add_ip('fd10:0:0:1::5/64')

**Comment by svinota** [comment]
Indeed. Will be fixed asap.
