### ISSUE TITLE
Create a team interface without teamd

### ISSUE THREAD

**Issue by vincentbernat** [svinota/pyroute2#406]
Hey!

I would like to create a team interface but not spawn teamd. My usecase is that I only need the interface for some tests and I am in an environment where teamd cannot be spawned (no new processes are authorized due to an odd combination of namespaces). I don't know what's the best way to do that. Maybe a special "kind" of interface ("raw-team")?

**Comment by svinota** [comment]
Will that work for you?

```python
from pyroute2 import RawIPRoute
rp = RawIPRoute()
rp.link("add", ifname="test0", kind="team")
```

**Comment by svinota** [comment]
The `RawIPRoute` class is already available, and the only difference from the `IPRoute` class is that it doesn't even try to launch helpers when creating team, bridge, bonds etc. The `IPRoute` class tries helpers if the platform doesn't support native bridge & bonds creation, and always launches teamd for team interfaces.

**Comment by vincentbernat** [comment]
Thanks! This works fine for me.
