### ISSUE TITLE
Feature request: ipdb: add new route before removing old route when changing priority

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#411]
I recognize this is a special case that would add complexity to the code, so feel free to tell me this is not worth supporting.  However, it would be nice if pyroute2 could change route priorities without introducing a brief window of time where the route does not exist.

pyroute2 currently changes the route in-place if RouteKey doesn't change, and deletes then re-adds the route if RouteKey does change:
https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/routes.py#L440
Since 'priority' is part of RouteKey, the route is deleted then re-added when 'priority' is changed, which introduces a brief window of time where the route does not exist.

Unfortunately, the kernel does not support changing the priority of a route in-place, so the route actually does have to be deleted and re-added: http://lkml.iu.edu/hypermail/linux/net/0504.3/0017.html
Note that there are other cases where the route is currently deleted and re-added but could instead be changed in-place (for example, 'oif' could be changed in-place, but pyroute2 deletes and re-adds the route because 'oif' is part of RouteKey) ... however, I don't personally have a need for non-disruptive changes in those cases and my only concern at the moment is 'priority' changes.

In most cases, two routes for the same prefix cannot exist at the same time, so the current pyroute2 behavior is usually correct: If the route must be deleted and re-added, then in most cases the old route must be deleted before the new route can be added, and there is no way to avoid having a brief window of time where the route does not exist.

However, two routes for the same prefix can exist at the same time if they have different priorities, so to avoid introducing a window of time where the route doesn't exist, it is technically possible for pyroute2 to add the new route with the new priority before removing the old route with the old priority.

This can currently be accomplished by users of pyroute2 using something like:
>>> r = ipdb.routes['123.0.0.0/24']
>>> r['priority'] = 200
>>> ipdb.routes.add(r).commit()
>>> r.remove().commit()
However, this requires the use of two separate transactions, which prevents changing the priorities of multiple routes in an all-or-none fashion using a single transaction.

Could a special case be added around https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/routes.py#L440 to delete the old route after adding the new route if the 'priority' field has changed?

**Comment by PaulSD** [comment]
I was thinking about this some more, and realized that a generic and clean solution is simple.  I will submit a PR.

**Comment by svinota** [comment]
Yep, I see. Sorry for the delay these days.

And thanks for the PR!

**Comment by PaulSD** [comment]
For reference, PR was: https://github.com/svinota/pyroute2/pull/412
