### ISSUE TITLE
link("add", kind="tuntap", ...) leaks pipe descriptors

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#424]
Every time after a tap link is created with the above command (using persistent IPRoute object), there are two more entries in the /proc/&lt;pid&gt;/fd directory, looking like this:

```
lr-x------ 1 root root 64 Sep 19 15:09 14 -> pipe:[432107]
l-wx------ 1 root root 64 Sep 19 15:09 15 -> pipe:[432107]
```
and eventually file descriptor ulimit is exhausted.

Latest checked version 0.4.21

**Comment by crosser** [comment]
I tried to use a separate instance of the IPRoute object, and call close() on it, but it does not seem to work: pipe descriptors still leak.

**Comment by svinota** [comment]
The leak found, the fix will be committed after testing.

**Comment by svinota** [comment]
Should be fixed now, please check. I'm sorry for the issue.

The fix is in the master.

**Comment by crosser** [comment]
Today's master fixes the problem that I observed. Thanks! :+1:

**Comment by svinota** [comment]
Thank you for pointing the issue.
