### ISSUE TITLE
Sed command in Makefile for docs does not work on BSD derivatives

### ISSUE THREAD

**Issue by marchon** [svinota/pyroute2#426]
This sed command does not work on osx for building the docs. :( 

sed -i '1{s/.*docs\//.. image:: /;s/\ ".*/\n\ \ \ \ :align: right/}' docs/general.rst

A link to the type of error is here, but I am not sure how to fix it, so I thought I would bring it to your attention, otherwise it looks like you have a very interesting library.

**Comment by svinota** [comment]
Thanks! I'll try to reproduce it on FreeBSD.

The library is not tested on BSD systems, as the platform-independent netlink engine is not ready (yet).

So thanks for the feedback.

**Comment by marchon** [comment]
Yes, I saw that it does not work on either BSD or Windows, but I thought that reviewing the docs might give me some ideas on trying to make something work on the other two. :) 

Are you working on a platform-independent netlink engine? 

are you familiar with netifaces - I did not write it but I have been reviewing it? 

https://github.com/stephica/netifaces

Description
"
1. What is this?

It's been annoying me for some time that there's no easy way to get the address(es) of the machine's network interfaces from Python. There is a good reason for this difficulty, which is that it is virtually impossible to do so in a portable manner. However, it seems to me that there should be a package you can easy_install that will take care of working out the details of doing so on the machine you're using, then you can get on with writing Python code without concerning yourself with the nitty gritty of system-dependent low-level networking APIs.

This package attempts to solve that problem."

**Comment by svinota** [comment]
> but I thought that reviewing the docs might give me some ideas on trying to make something work on the other two. :)

http://docs.pyroute2.org/

> Are you working on a platform-independent netlink engine?

Not as intensively as I wish, but the feature is planned.

> are you familiar with netifaces

Not familiar, but I know about it. These two libraries, pyroute2 and netifaces, are made with different purposes. As I understand, netifaces tries to provide a simple platform-independent way to represent a simple network-related info. While pyroute2 is a netlink library, so it's limited to the netlink protocols, whatever it may provide (iSCSI, nl80211, disc quotas, RTNL, nftables etc).

…

It is doable to write an RTNL engine that could work on BSD in almost the same way as it is provided by the kernel on Linux. But there is a serious question — how to get async updates on BSD, e.g., when one adds an address on an interface, creates an interface, a route, and so on. And to do it without polling the system. I tried to look on the kqueue, but didn't succeed much yet. If you could help with that, I would thank you very much.

**Comment by svinota** [comment]
As from now on the IPRoute module supports BSD platforms (not to the full extent, but somehow), I'm closing the issue.
