### ISSUE TITLE
IPDB: Adding route destined for "0.0.0.0/0" raises CommitException

### ISSUE THREAD

**Issue by audeoudh** [svinota/pyroute2#428]
I try to add a default route with IPDB (release 0.4.21). Instead of using the alias "default", I use the explicit "0.0.0.0/0" designation :

    from pyroute2 import IPDB
    ipdb = IPDB()
    rte = ipdb.routes.add(dst="0.0.0.0/0", gateway="172.18.0.4")
    rte.commit()

The last line raises a CommitException :

      File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/routes.py", line 506, in commit
        raise error
      File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/routes.py", line 457, in commit
        transaction.wait_all_targets()
      File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/transactional.py", line 507, in wait_all_targets
        raise CommitException('target %s is not set' % key)
    pyroute2.ipdb.exceptions.CommitException: target dst is not set

Use `.add(dst="0.0.0.0", dst_len=0, …)` leads to the same.

Surprisingly, the route correctly is created :

    # ip route show
    default via 172.18.0.4 dev eth0 proto static 
    172.18.0.4 dev eth0 proto lrp scope link 

Use `.add(dst="default", …)` instead works correctly, without exception.

**Comment by svinota** [comment]
Yep, I hope to fix it today.
