### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by fessoga5** [svinota/pyroute2#430]
Hello guys, I've detected memory leak in pyroute2 module. Here is a code I'm testing it with:

```
#!/usr/bin/env python2

from pyroute2 import netns, NetNS, IPDB, IPRoute
import time

while True:
    with IPDB() as a:
        a.release()
        time.sleep(0.2)
        print("...")
```
When I use ps to check memory usage I see that it constantly increases:
```
akaramy+ 12186  5.2  0.2 214836 20320 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 214972 20356 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 214972 20648 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 215228 20688 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 215228 20796 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 215228 20796 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 215228 20796 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.0  0.2 215228 20796 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.0  0.2 215228 20796 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 215360 20800 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.1  0.2 215360 20836 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.0  0.2 215360 20876 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.0  0.2 215496 21168 pts/14   S+   17:04   0:01 python2 ./test.py
akaramy+ 12186  5.0  0.2 215752 21212 pts/14   S+   17:04   0:01 python2 ./test.py
```

P.S.
pyroute2 (0.4.21)
ubuntu 16.04
Python 2.7.12

**Comment by fessoga5** [comment]
Up!

**Comment by svinota** [comment]
Sorry, was out about a week. Investigating

**Comment by svinota** [comment]
The issue confirmed.

**Comment by fessoga5** [comment]
Thanks!

**Comment by itdaniher** [comment]
This issue caught my eye, so I took a look at it on Python3. Bad news, is I was able to reproduce, even after adding a `gc.collect()` call to my mainloop. 

Good news is the memleak is quite slow, leaking a few bytes every iter, at most.

```python
import gc
from pyroute2 import netns, NetNS, IPDB, IPRoute
import time
import resource

while True:
    with IPDB() as a:
        a.release()
    time.sleep(0.2)
    gc.collect()
    print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
```

prints:

```
17072
17140
17140
17140
17140
17140
17140
17140
17144
17144
17148
```

python3.5.2, linux 4.4.77, ubuntu xenial

**Comment by svinota** [comment]
Trying to trace the root cause with meliae, but it takes time. Thanks for the patience.

**Comment by fessoga5** [comment]
Hello! What did you find out?

**Comment by svinota** [comment]
I was outta the network for several weeks, returning to the project now. Sorry for delays

**Comment by fangzhen** [comment]
I also run into the bug, and seems to caught the root cause. In [https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/main.py#L836](url),
`        atexit.register(self.release)
`
It will hold references to IPDB instance which prevents garbage collection.
The code comes in at https://github.com/svinota/pyroute2/commit/947163bd60ffc4c72866743a0a345781cb0e49f9
I'm afraid I don't fully understand the patch, and not sure is it safe to remove it. Or use a weakref for that?

**Comment by celebdor** [comment]
@svinota: It definitely looks like @fangzhen got the culprit with the atexit. As @fangzhen a weakref should fix it.

**Comment by srijnair-cisco** [comment]
Even with this patch and netns patch fro memory leak, I see some leaks and mostly with the cleanup
SUMMARY AFTER RUN  190
                       types |   # objects |   total size
============================ | =========== | ============
                        dict |       14219 |      6.74 MB
                         str |       30641 |      2.44 MB
                       tuple |       26717 |      1.85 MB
          function (cleanup) |       11592 |      1.33 MB
                     weakref |       12756 |      1.07 MB
                        list |        8017 |    947.90 KB
                        type |         909 |    795.04 KB
                        code |        5396 |    674.50 KB
                     unicode |         185 |    199.04 KB
  builtin_function_or_method |        1646 |    115.73 KB
          wrapper_descriptor |        1377 |    107.58 KB
                         int |        2859 |     67.01 KB
                         set |         257 |     64.73 KB
           method_descriptor |         789 |     55.48 KB
           getset_descriptor |         742 |     52.17 KB
DIFF SUMMARY
                                                  types |   # objects |   total size
======================================================= | =========== | ============
                                                   dict |          61 |     28.68 KB
                                                  tuple |         122 |      8.58 KB
                                     function (cleanup) |          61 |      7.15 KB
                                                weakref |          61 |      5.24 KB
                              function (getNameByQName) |           0 |      0     B
                                function (addLevelName) |           0 |      0     B
                                       function (alloc) |           0 |      0     B
                                  function (raw_decode) |           0 |      0     B
                                   _ctypes.PyCArrayType |           0 |      0     B
                                     datetime.timedelta |           0 |      0     B
  function (_dispatchStoragePoolEventLifecycleCallback) |           0 |      0     B
                       function (is_gateway_configured) |           0 |      0     B
                                  function (isreadable) |           0 |      0     B
                     function (config_static_ip_bridge) |           0 |      0     B
                             function (network_cleanup) |           0 |      0     B
