### ISSUE TITLE
ipdb: route `family` must be specified when `gateway` is `None`

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#434]
Routes for directly-attached networks have `gateway` set to `None`.  If `family` is not specified when adding/updating a directly-attached IPv4 route, then an exception is thrown by https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/routes.py#L998 because `.find(':')` cannot be called on None.  I think this needs to be changed to something like:
            if (spec.get('dst', '').find(':') > -1) or \
                    (spec.get('gateway', '') is not None and spec.get('gateway', '').find(':') > -1):

**Comment by svinota** [comment]
Tried to fix that. Pls tell if it works. Thanks!

**Comment by PaulSD** [comment]
Looks good now.  Thanks!
