### ISSUE TITLE
:functionality status: socket stats

### ISSUE THREAD

**Issue by cherusk** [svinota/pyroute2#447]
Any specific plans to progress on completing the socket stats core? Only rudiments perceivable so far.

**Comment by svinota** [comment]
Yep. Thanks for reminder

**Comment by cherusk** [comment]
I understand: perceive it as a prereq for https://github.com/cherusk/fleutan. Might come round sparking it off myself: simply too many disincentives for investing in iproute2.

**Comment by cherusk** [comment]
Have decided  to at least shape the TCP spin of it. Incepting in https://github.com/svinota/pyroute2/pull/464

Closing therefore.
