### ISSUE TITLE
setns leaks FDs

### ISSUE THREAD

**Issue by itdaniher** [svinota/pyroute2#448]
minimal test script: https://gist.github.com/itdaniher/5308c0905ed76189381861964ac974aa

prints:

``` python
Traceback (most recent call last):
  File "test.py", line 7, in <module>
  File "/home/username/.virtualenvs/venv/lib/python3.5/site-packages/pyroute2/netns/__init__.py", line 225, in setns
  File "/home/username/.virtualenvs/venv/lib/python3.5/site-packages/pyroute2/netns/__init__.py", line 132, in listnetns
OSError: [Errno 24] Too many open files: '/proc/1/ns'
1021
```

expected result: no limit to number of times pyroute2.netns.setns can be called with the same path.

actual result: each invocation of setns with a string creates an FD which is not cleaned, limiting the number of setns calls to the number of available FDs for the process (1024 or so on most systems)

potential solution: cache FDs in a mapping of {path: fd_int} in pyroute2.netns, using existant FDs for future calls to setns if possible.

**Comment by itdaniher** [comment]
I worked around this issue using `functools.lru_cache` to cache the results of `os.open`.

This gist behaves as expected: https://gist.github.com/itdaniher/b16e09a1f247790b111e1ce2bf99a69b

If this solution is deemed appropriate / meritorious, I'd be happy to rework this solution as a patch for [pyroute2.netns](https://github.com/svinota/pyroute2/blob/master/pyroute2/netns/__init__.py).

Cheers!

**Comment by svinota** [comment]
Thanks! Testing

**Comment by svinota** [comment]
The issue is that `setns()` by design opens a file and returns the FD.

A good question, is it a bad design. Probably.

Another question is if we fix it now, how many projects will be broken.
