### ISSUE TITLE
failed to add IPv6 address (veth

### ISSUE THREAD

**Issue by landgraf** [svinota/pyroute2#450]
Haven't checked with newest version (if any) but python2-pyroute2-0.4.13-1.fc26.noarch gives me the error.

Code:
```
from pyroute2 import IPDB, NetNS

db = IPDB(nl = NetNS("test"))

db.create(ifname="veth1", kind='veth', peer="veth2").commit()

with db.interfaces.veth1 as iface:
    iface.add_ip("2001:DB8::2:2/64")
    iface.up()
```
Error:

> Traceback (most recent call last):
>   File "./repro.py", line 11, in <module>
>     iface.up()
>   File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/transactional.py", line 194, in __exit__
>     self.commit()
>   File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/interface.py", line 925, in commit
>     raise error
>   File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/interface.py", line 803, in commit
>     **kwarg if kwarg else {})
>   File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/interface.py", line 463, in _run
>     raise error
>   File "/usr/lib/python3.6/site-packages/pyroute2/ipdb/interface.py", line 458, in _run
>     return cmd(*argv, **kwarg)
>   File "/usr/lib/python3.6/site-packages/pyroute2/iproute.py", line 1363, in addr
>     terminate=lambda x: x['header']['type'] ==
>   File "/usr/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 805, in nlm_request
>     return do_try()
>   File "/usr/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 784, in do_try
>     callback=callback)
>   File "/usr/lib/python3.6/site-packages/pyroute2/netlink/nlsocket.py", line 649, in get
>     raise msg['header']['error']
> pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')

**Comment by svinota** [comment]
Can not reproduce, unfortunately. If you can, pls feel free to reopen the issue.
