### ISSUE TITLE
Add support for creation veth and put peer in separate namespace in one call

### ISSUE THREAD

**Issue by slawqo** [svinota/pyroute2#463]
Using "ip" tool in linux I can do something like:

`ip link add veth type veth peer veth netns test-e40d1523-d29b-413e-bfff-91bf32dd042a`

which will create me 2 veth devices (pair) with same names "veth" but one will be in "test-e40d1523-d29b-413e-bfff-91bf32dd042a"

Similar operation is not possible with pyroute2 as I need to do veth pair first and then put one of devices in namespace.

Such feature is necessary to switch "add_veth" method from OpenStack Neutron to pyroute2: https://github.com/openstack/neutron/blob/master/neutron/agent/linux/ip_lib.py#L173

**Comment by svinota** [comment]
@slawqo Sorry, I didn't realize it's already done. Actually, it is there from the beginning of the veth support.

```python
with IPRoute() as ipr:
    ip.link("add",
            **{"ifname": "vt1",
               "kind": "veth",
               "peer": {"ifname": "vt2",
                        "net_ns_fd": "test"}})
```

**Comment by svinota** [comment]
I have to reflect that in the docs.

**Comment by slawqo** [comment]
Thx a lot @svinota for checking that and for updating docs. I will get back to work on adopting it in Neutron when I will have some time for that :)

**Comment by svinota** [comment]
@slawqo thanks!

will you have any questions — pls ping me
