### ISSUE TITLE
wrong rtnl group flags constant names

### ISSUE THREAD

**Issue by rjarry** [svinota/pyroute2#470]
Hi,

I have noticed that the rtnetlink multicast group flags (to use with `bind()` for kernels before 2.6.14) are declared with the names of the multicast group ids (to be used with `setsockopt(NETLINK_{ADD,DEL}_MEMBERSHIP)` since kernel 2.6.14). They should have a `RTMGRP_` prefix instead of `RTNLGRP_`.

https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/rtnl/__init__.py#L39
https://github.com/torvalds/linux/blob/master/include/uapi/linux/rtnetlink.h#L606

This is confusing and when trying to subscribe to a specific multicast group using the constants defined in `pyroute2.netlink.rtnl` with `setsockopt`, we get a `errno=22 invalid argument` error.

I know that renaming those constants would break the API but I feel this is necessary. I'll submit a PR with a draft patch for review.

**Comment by svinota** [comment]
Yep, I already thought about it but didn't find it too serious — and looks like I may be wrong. 

Thanks, I'll wait for the PR and I believe we fix the issue in some way.
