### ISSUE TITLE
Some typo in existing package ip.nl.get_neighbors / ip.nl.get_neighbours

### ISSUE THREAD

**Issue by hetii** [svinota/pyroute2#487]
It seams some typo exist in IPDB, both return the same result.
ip = IPDB()
ip.nl.get_neighbors()
ip.nl.get_neighbours()
Or is it just there for some compatibility?

**Comment by svinota** [comment]
It's for compatibility. And it's a good reminder to put the `deprecated` warning in the former one.

**Comment by svinota** [comment]
Oh, wait, it's already there. So the method will be removed asap :)

**Comment by svinota** [comment]
Raising `DeprecationWarning()`, the method will be removed in the coming release.
