### ISSUE TITLE
Some example needed how to control ARP table by pyroute2.

### ISSUE THREAD

**Issue by hetii** [svinota/pyroute2#489]
For linux ip tool is possible to control ARP table.
We need some example how to do it by pyroute2.

```
root@refactor:~# ip neigh show
192.168.1.1 dev wlan0 lladdr 00:1b:da:29:3a:87 REACHABLE
root@refactor:~# ip neigh add 192.168.1.2 dev wlan0 lladdr 00:1b:da:29:3a:89
root@refactor:~# ip neigh show
192.168.1.2 dev wlan0 lladdr 00:1b:da:29:3a:89 PERMANENT
192.168.1.1 dev wlan0 lladdr 00:1b:da:29:3a:87 REACHABLE
```

**Comment by svinota** [comment]
ok, tbd asap

**Comment by hetii** [comment]
Btw here is how I clear arp cache for single ipv4, but I believe by pyroute2 it can be done better. 

    def clear_arp_entry(ip, ifname=''):
        while True:
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)    
                ip_bytes = int(ipaddress.IPv4Address(ip)).to_bytes(4, byteorder='big')
                fcntl.ioctl(
                    sock.fileno(),
                        0x8953, # SIOCDARP
                        struct.pack('hh48s16s', socket.AF_INET, 0, ip_bytes, ifname[:15].encode())
                    )
            except OSError as e:
                break
            finally:
                sock.close()

**Comment by svinota** [comment]
Updated info on the doc pages:

http://docs.pyroute2.org/iproute.html#pyroute2.iproute.IPRouteMixin.neigh
