### ISSUE TITLE
No RX/TX Pckts & Bytes counters 

### ISSUE THREAD

**Issue by blietaer** [svinota/pyroute2#493]
Dear Svinota,
Is there a way in Pyroute2 to retrieve same information than psutil.net_if_stats() ?

Typically, I am looking for basic stats like RX/TX counters (pckt, bytes, errors,..) but also the Link status (note that Link in psutil is related to interface status but not carrier link status itself... :/ )

I can find the MTU in the IPDB.dump()["interfaces"] but not thoses...not in NETLINK ?
I could not find their trace in the pyroute2 doc...

I wish I could drop psutil, especially because I use namespaces and this net_if_stats() behaves poorly in namespace contextes (while other psutil calls don't...)

Thank you for your feedback,
Cheers,
Benoit
(Belgium)

**Comment by svinota** [comment]
You may retrieve all the possible stats via IPRoute:

```
from pprint import pprint
from pyroute2 import IPRoute

with IPRoute() as ipr:
    pprint(ipr.get_links())
```

In the case of the namespaces you can use `NetNS` as a drop-in for `IPRoute`, just change all the `IPRoute` in the code to `NetNS`:

```
from pyroute2 import NetNS

with NetNS('test') as ns:
    ns.get_links()
```

**Comment by blietaer** [comment]
Ah, my oversight.
Beautiful, thank you for your time.

**Comment by svinota** [comment]
Pls keep in mind that in this case you get netlink packets, though decoded, they are not so straightforward.

`get_links()` returns a list of messages, as most of methods do. There is a documentation how to work with messages: http://docs.pyroute2.org/iproute.html#how-to-work-with-messages

**Comment by blietaer** [comment]
Yes yes ! NETLINK packed and I read your description on how to parse them.
Though I am not sure the duplex and/or speed informations are part of NETLINK packed (at least not from ns.get_links()) Correct ?

**Comment by svinota** [comment]
IIRC, in the RTNL link info there is nothing about duplex/speed. One should use some other means (ioctl maybe?) to retrieve it.

**Comment by blietaer** [comment]
Ah. Interesting...
So I' ll have to stick to psutil and/or /sys/class/net and/or ethtool parsing just for the link mode values..? :/
Pitty since those three are not namespace friendly....

**Comment by ffourcot** [comment]
FYI, there is an experimental patch set to add netlink support for ethtool:

https://github.com/mkubecek/ethnl

But it's far away from merged in kernel I think (sadly).

This python project claims to support ethtool commands as well:

https://pypi.org/project/NetLink/

But it looks unmaintained, so I'm afraid that there is no real solutions today (but if you find one, I'm very interested as well).

**Comment by blietaer** [comment]
Thank you for these inputs, Florent.

Sadly, indeed and I have a hard time believing these 3 ethtool-related information (namely: duplex/speed/(real) link-status) are not available in the same place than the juicy NETLINK data pool....although I am no kernel hacker.

No real solution here neither, as I said, I'll stick to /sys/class/net files parsing (slow!) and/or psutil in a NetNS 'context', depending on what looks more 'stable' since I need to display these data in my GUI.
