### ISSUE TITLE
Supporting "name-less" network namespaces by identifying them via PID

### ISSUE THREAD

**Issue by TheDiveO** [svinota/pyroute2#495]
From the documentation as well as the source code in the netns/ subdirectory, I've got the impression that pyroute2 only supports "named" network namespaces that are somewhere registered in the filesystem (/var/run/netns).

However, when working with different container environments, these all tend to use "name-less" network namespaces. Would it be possible to support identifying such name-less network namespaces in the same way as, for instance, `nsenter` does: via the PID of any process using that network namespace?

**Comment by svinota** [comment]
Yep, sure. A good feature to implement, thanks.

**Comment by itdaniher** [comment]
Here's my implementation.

```python
@functools.lru_cache(maxsize=1024)
def get_fd_from_netnspath(netnspath):
    if '/' not in netnspath:
        netnspath = '/var/run/netns/%s' % netnspath
    return os.open(netnspath, os.O_RDONLY)


def set_ns(path): return pyroute2.netns.setns(get_fd_from_netnspath(path))


set_ns('/proc/1/ns/net')
````

**Comment by svinota** [comment]
Oops. Already implemented :)
```
>>> from pyroute2 import netns
>>> netns.setns('/proc/1/ns/net')
```
