### ISSUE TITLE
IPDB: OOM when receiving too many connections

### ISSUE THREAD

**Issue by soyking** [svinota/pyroute2#507]
version: 0.4.13

I am using pyroute2 to get interface state and control interface up/down. It may cause OOM when I try to make a lots of connections from different IP. Error message:

```
[2018-05-21 14:24:11] - [ERROR] - [pyroute2.ipdb.main:951]  - Restarting IPDB instance after error:
Traceback (most recent call last):
  File "site-packages/pyroute2/ipdb/main.py", line 939, in serve_forever
  File "site-packages/pyroute2/netlink/nlsocket.py", line 708, in get
  File "site-packages/pyroute2/netlink/nlsocket.py", line 944, in recv_plugin
  File "site-packages/pyroute2/netlink/nlsocket.py", line 512, in async_recv
OSError: [Errno 105] No buffer space available
```

It seems that `get` function in `NetlinkMixin` can't allocate more spaces. And it seems that IPDB will hold all arp info in memory? In my case I just want to control interfaces, so is there any way to fix this problem? Thanks.

**Comment by svinota** [comment]
The same issue with routes — the current IPDB implementation consumes too much memory.

I'm fixing that, but it requires some architecture change, so it may take up to one month to be fixed.

**Comment by crosser** [comment]
To clear things up: `OSError: [Errno 105] No buffer space available` does _not_ mean "we are using too much memory". It means "too many netlink events where issued by the kernel before userspace could consume them". Generally, there is not much hope to consume events faster than they are generated, so there are two possible strategies:
1. If you know that the total number of events is limited, allocate bigger SO_RCVBUF (upper limit in `/proc/sys/net/core/rmem_max`), or
2. allocate smaller SO_RCVBUF, detect ENOBUFS condition and restart processing from scratch after the storm subsides.

The second strategy seems to work well enough for me.

**Comment by svinota** [comment]
@crosser pls notice that I started a new branch — «ndb».

Nothing in particular (yet), but some drafts for a possible IPDB replacement. Any comments, discussions etc. are welcome.

**Comment by svinota** [comment]
@soyking if you provide me technical requirements for the module, I try to see if we can fit NDB for your task asap. It is still a read-only database of the network settings, but it's already enough to monitor the settings and run actions on events.

**Comment by soyking** [comment]
I used pyroute2 in a server which received thousands of connections. Since the `ip neigh` was so large and as time went by, it got OOM. I think old pyroute2 may keep the information in memory (not sure), but I just use IPDB to call interface up/down. So maybe there should be some options to make it not keep much information in memory when I just want to handle interface ?

**Comment by svinota** [comment]
Simple up/down could be done more easy with IPRoute:
```python
with IPRoute() as ipr:
    ipr.link("set", index=ipr.link_lookup(ifname="eth0"), state="up")
```

IPDB has some design issues that makes it not so useful in environments with hundreds of thousands of the network objects (be it neighbours, routes or interfaces). That why I'm working on it's replacement.
