### ISSUE TITLE
[announce] Important: netlink socket methods will return generators

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#516]
Starting with 0.5.3 (the next after the coming release) **all** netlink socket methods that return now lists of messages will return generators.

**UPD: as an option, not by default**

It is really important as the current design prevents from retrieving huge numbers of netlink objects. E.g. it is almost impossible now to get 500000 routes as the script will run out of memory.

The current master and 0.5.2 will allow **some** of the methods to return generators upon request. E.g., right now it is possible to run:
```python
with IPRoute() as ipr:
    for route in ipr.get_routes(nlm_generator=True):
        do_something_with(route)
```

But it is really tough to fit both approaches into one code, so starting with 0.5.3 the generators will be the only available alternative.

If you use constructions like `ipr.get_routes()[0]…`, please make sure you explicitly unfold generators like `tuple(ipr.get_routes())[0]…`

…

The same will affect **all** the netlink modules, like ipset, nl80211 etc, etc.

…

One more announce will come with 0.5.2.

Brace yourself. Generators are coming.

**Comment by svinota** [comment]
@ffourcot , @celebdor , @drzaeus77 , @etene , @plorinquer , @jpirko 

friends, ye warned.

if you have arguments against and/or you see ways to solve that in a fully backward compatible way, pls tell me.

**Comment by plorinquer** [comment]
Hello,

I am OK with this. Thanks for the warning !

**Comment by svinota** [comment]
The documentation to the feature will be here: https://github.com/svinota/pyroute2/blob/master/docs/generator.rst

**Comment by svinota** [comment]
Carefully reviewed several projects that use pyroute2. Looks like turning the option «on» by default will break too much code.

So for now leaving it «off» by default with possibility to turn on in the runtime by changing the config option.

Also introducing warning in the nlsocket code that will issue alert on too long result lists if `config.nlm_generator == False`.
