### ISSUE TITLE
Cannot import IPSet from other module

### ISSUE THREAD

**Issue by Vic063** [svinota/pyroute2#523]
Hi,

as part of my work of adding ematch/ipset filters, I wanted to use the IPSet module and import it from the ematch/ipset module I am writing.

Sadly, it does not work and crashes when simply doing:
from pyroute2 import IPSet
Is there any workaround available to do that?

Thanks!

**Comment by svinota** [comment]
Could you please send me (paste here or in IRC) the traceback from the script and the Linux kernel version? Thanks!

**Comment by Vic063** [comment]
root@debian:/home/vico/pyroute2/pyroute2/netlink/rtnl/tcmsg# uname -a
Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

Here is the traceback:
In [1]: from pyroute2 import IPRoute
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-0e3bd3498426> in <module>()
----> 1 from pyroute2 import IPRoute

/home/vico/pyroute2/pyroute2/__init__.py in <module>()
     17 from pyroute2.netlink.rtnl.req import (IPRouteRequest,
     18                                        IPLinkRequest)
---> 19 from pyroute2.iproute import (IPRoute,
     20                               IPBatch,
     21                               RawIPRoute)

/home/vico/pyroute2/pyroute2/iproute/__init__.py in <module>()
    128 '''
    129 from pyroute2 import config
--> 130 from pyroute2.iproute.linux import RTNL_API
    131 from pyroute2.iproute.linux import IPBatch
    132 

/home/vico/pyroute2/pyroute2/iproute/linux.py in <module>()
     52 from pyroute2.netlink.rtnl.req import IPRouteRequest
     53 from pyroute2.netlink.rtnl.req import IPRuleRequest
---> 54 from pyroute2.netlink.rtnl.tcmsg import plugins as tc_plugins
     55 from pyroute2.netlink.rtnl.tcmsg import tcmsg
     56 from pyroute2.netlink.rtnl.rtmsg import rtmsg

/home/vico/pyroute2/pyroute2/netlink/rtnl/tcmsg/__init__.py in <module>()
      7 from pyroute2.netlink.rtnl.tcmsg import cls_u32
      8 from pyroute2.netlink.rtnl.tcmsg import cls_matchall
----> 9 from pyroute2.netlink.rtnl.tcmsg import cls_basic
     10 from pyroute2.netlink.rtnl.tcmsg import sched_bpf
     11 from pyroute2.netlink.rtnl.tcmsg import sched_choke

/home/vico/pyroute2/pyroute2/netlink/rtnl/tcmsg/cls_basic.py in <module>()
      3 from pyroute2 import protocols
      4 from pyroute2.netlink import nla
----> 5 from pyroute2.netlink.rtnl.tcmsg.common_ematch import get_ematch_parms
      6 from pyroute2.netlink.rtnl.tcmsg.common_ematch import get_tcf_ematches
      7 from pyroute2.netlink.rtnl.tcmsg.common_ematch import nla_plus_tcf_ematch_opt

/home/vico/pyroute2/pyroute2/netlink/rtnl/tcmsg/common_ematch.py in <module>()
----> 1 from pyroute2.netlink.rtnl.tcmsg import em_ipset
      2 
      3 plugins = {
      4            #0: em_container,
      5            #1: em_cmp,

/home/vico/pyroute2/pyroute2/netlink/rtnl/tcmsg/em_ipset.py in <module>()
      2 from pyroute2.netlink import nla
      3 from pyroute2.netlink import nlmsg
----> 4 from pyroute2 import IPSet
      5 
      6 # see em_ipset.c

ImportError: cannot import name IPSet

**Comment by svinota** [comment]
Ough, it's not a pyroute2 issue, it's a cycle import dependency made by the patch you applied for ematch.

As I told, I'll look into the patch code tonight, we'll see.

**Comment by ffourcot** [comment]
@svinota, actually, this circular dependency is an issue to add "high-level" to the incoming tc-ematch filter. If you look this code:


```
    match = [{"index": 0, "mode": "src", "inverse": True}]
    ip.tc("add-filter", "basic", ifb0, em_kind="ipset",
            parent=0x10000, classid=0x10010, match=match) 
```

Our goal was to allow match using ipset names, instead of ipset index (hard to retrieve today, it's only possible with getsockopt). To do something like it:


```
    match = [{"name": "foo", "mode": "src", "inverse": True}]
    ip.tc("add-filter", "basic", ifb0, em_kind="ipset",
            parent=0x10000, classid=0x10010, match=match) 
   # some black magic in ematch-ipset module convert name to index
```


Do you have an idea for this feature?

**Comment by svinota** [comment]
S.c. "root signatures" — `from pyroute2 import <symbol>` — are made for the external usage, so the users can rely on a permanent module signature, that doesn't change when the module layout changes. They are implemented as re-export of ordinary modules from `pyroute2/__init__.py`.

But inside the library we have to avoid using them 'cause of possible import loops. So in that case we may do that:
```python
# file pyroute2/netlink/rtnl/tcmsg/em_ipset.py

# "root import" — wrong: from pyroute2 import IPSet
from pyroute2.ipset import IPSet  # correct — fully-qualified import
```

If you're going to open additional netlink sockets from within the `IPRoute` calls, please make sure that all the temporary sockets get closed even in the case of an exception — to avoid fd leaks. All the netlink socket objects must support the context manager protocol, so use `with IPSet(…) as …: …`.

Thanks!

**Comment by ffourcot** [comment]
Thank you @svinota, I'm closing it
