### ISSUE TITLE
Tests that import iproute are broken on OSX

### ISSUE THREAD

**Issue by rm-you** [svinota/pyroute2#529]
It seems that in this commit, some logic was added to `pyroute2/iproute/__init__.py` that causes an exception to be raised on anything besides Linux and BSD:
https://github.com/svinota/pyroute2/commit/7b88c812e8033b155aec5b7be0c91be1f2f8b737#diff-5ee5b4b3168b121a94de25048bc7f152

Unfortunately, many people run test suites on OSX, which should work if the appropriate pieces are mocked out -- but now this fails immediately upon import with `ImportError: no IPRoute module for the platform`.

**Comment by rm-you** [comment]
One easy example of this is checking out https://github.com/openstack/octavia/tree/master/octavia and running `tox -e py35`.

**Comment by rm-you** [comment]
Thanks! That will help, right now I have to pin to an older version for local testing, which works but isn't ideal. 👍

**Comment by svinota** [comment]
Pls check if it's better now. Not a solution, but a mocking class for not supported platforms I'll provide a bit later.

**Comment by rm-you** [comment]
Yes, that appears to resolve the issue for now. Thanks!

**Comment by svinota** [comment]
Cool. Thanks!

**Comment by rm-you** [comment]
Any word on this? It isn't critical still, but it is frustrating. T_T

**Comment by rm-you** [comment]
This appears to have released in 0.5.3 and works for me. Thanks!
