### ISSUE TITLE
Cannot change some GRE attributes

### ISSUE THREAD

**Issue by ThomasFaivre** [svinota/pyroute2#532]
Hello!

I haven't tried with other kind of interfaces, but when trying to set the TTL for instance, nothing happens. I traced it back to the type and flags used for the 'set' message:

```
import pyroute2

from pyroute2.netlink.rtnl import RTM_SETLINK
from pyroute2.netlink.rtnl import RTM_NEWLINK
from pyroute2.netlink import NLM_F_ACK
from pyroute2.netlink import NLM_F_REQUEST
from pyroute2.netlink import NLM_F_CREATE
from pyroute2.netlink import NLM_F_EXCL


flags_req = NLM_F_REQUEST | NLM_F_ACK
flags_create = flags_req | NLM_F_CREATE | NLM_F_EXCL

ip = pyroute2.IPRoute()
d = {'kind': 'gre', 'gre_local': '10.100.0.1', 'gre_remote': '10.100.0.2'}
ip.link('add', ifname='gre1', **d)
gre1 = ip.link_lookup(ifname='gre1')

def set_ttl(ttl, command, index, **d):
    print('Checking %s with ttl %d' % (command, ttl))
    try:
        ip.link(command, index=index, gre_ttl=ttl, **d)
        print(ip.get_links(index)[0].get_attr('IFLA_LINKINFO').get_attr('IFLA_INFO_DATA').get_attr('IFLA_GRE_TTL'))
    except:
        print('Exception')

set_ttl(50, 'set', gre1[0], **d)
set_ttl(52, (RTM_NEWLINK, flags_req), gre1[0], **d)
set_ttl(54, (RTM_NEWLINK, flags_create), gre1[0], **d)
set_ttl(56, (RTM_SETLINK, flags_req), gre1[0], **d)
# set equivalent
set_ttl(58, (RTM_SETLINK, flags_create), gre1[0], **d)
```

When executing this script, we see that TTL change only with (RTM_NEWLINK, flags_req) as command:

```
root@ubuntu1804:~# python3 test.py 
Checking set with ttl 50
0
Checking (16, 5) with ttl 52
52
Checking (16, 1541) with ttl 54
Exception
Checking (19, 5) with ttl 56
52
Checking (19, 1541) with ttl 58
52
```

I can make a patch for IPRouteMixin.link but I see that IPRouteMixin.brport is also using RTM_SETLINK (but with flags_req) and I don't really now what to do with it :/

Any advise?

Thanks!

**Comment by svinota** [comment]
In the worst case we may patch the `(command, msg_flags)` specifically for GRE interfaces, but maybe there is some other way. I'll try today.

**Comment by svinota** [comment]
Looks like all the link `set` operations in the current kernels actually should be done with `flags == 5 (NLM_F_REQUEST | NLM_F_ACK)` and the message `type == 16 (RTM_NEWLINK)`.

So I'm to try to get it working with the current code, as for now the tests are failing if I simply replace the value.

**Comment by svinota** [comment]
I'm to fix the syntax, old `link('set', …)` becomes `link('update', …)`, while `set` will be `RTM_NEWLINK` with `flags_req`, as it should be, and as it is in `iproute2` as well.

**Comment by svinota** [comment]
Pls check, if it works for you now. It should.

**Comment by ThomasFaivre** [comment]
It works! Thanks!

**Comment by svinota** [comment]
Cool. Thanks for the issue!
