### ISSUE TITLE
By using IPDB context manager he don`t close NetNS() instance.

### ISSUE THREAD

**Issue by hetii** [svinota/pyroute2#539]
Hi, I notice that context manager do not close NetNS() instance when exit.

    ns = NetNS("ns1")
    with IPDB(nl=ns) as ip:
        pass
    print(ns.closed) #==> False

Regards.

**Comment by svinota** [comment]
Yes, 'cause the ns object was opened not by IPDB, and we have no idea where it was opened and why. That's why it's not closed. One possible solution:
```
with NetNS("ns1") as ns:
    with IPDB(nl=ns) as ip:
        pass
```

**Comment by hetii** [comment]
@svinota Thx for this clarification.
Probably its a good idea to put this information as example in REDME, cause it can produce a lot trouble when build application based on namespaces.

Regards.

**Comment by svinota** [comment]
Agree. To be fixed in docs.
