### ISSUE TITLE
failed to open netns - s390x

### ISSUE THREAD

**Issue by andrewdmcleod** [svinota/pyroute2#542]
ARCH: s390x LPAR
OS: Ubuntu 18.04.1 with sources.list.d/cloud-archive.list:deb http://ubuntu-cloud.archive.canonical.com/ubuntu bionic-updates/rocky main

error:

~# python2.7
>>> pyroute2.NetNS("qdhcp-e6c8fb75-df0a-4e68-b8e7-05df38730b0e", flags=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pyroute2/netns/nslink.py", line 193, in __init__
    super(NetNS, self).__init__()
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 296, in __init__
    super(NetlinkMixin, self).__init__()
  File "/usr/lib/python3/dist-packages/pyroute2/remote/__init__.py", line 253, in __init__
    raise init['error']
OSError: [Errno 22] failed to open netns: 'qdhcp-e6c8fb75-df0a-4e68-b8e7-05df38730b0e'

The netns is functional:

~# ip netns
qdhcp-e6c8fb75-df0a-4e68-b8e7-05df38730b0e
~# ip netns exec qdhcp-e6c8fb75-df0a-4e68-b8e7-05df38730b0e bash
~# ip a
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
4: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff

I noticed another open issue with similar error was related to chroot and suggested 'different architectures' as a potentially related issue, but didn't seem pertinent to log it under the same issue as this does not involve chroot, containers, etc.

fwiw I am only seeing this on s390x, I don't see it with the same config. on amd, arm64, or ppc64el.

**Comment by andrewdmcleod** [comment]
More info:

[pid 51036] openat(AT_FDCWD, "/var/run/netns/qdhcp-ade593b1-153b-47b8-84a9-009fca692003", O_RDONLY) = 4
[pid 51036] tee(4, 1073741824, 17109518126325597131, 0xaa7bac30 /* SPLICE_F_??? */) = -1 EINVAL (Invalid argument)

**Comment by andrewdmcleod** [comment]
FWIW, this problem exists with 0.4.21-0.1ubuntu2, but cloning master and trying with that works ok.

**Comment by svinota** [comment]
So if I understand correctly, it does work on the latest master?

**Comment by andrewdmcleod** [comment]
@svinota correct, feel free to close

**Comment by svinota** [comment]
Thanks a lot.
