### ISSUE TITLE
Set kernel WiFi regulatory domain

### ISSUE THREAD

**Issue by tomkcook** [svinota/pyroute2#550]
Does pyroute2 provide a way to set the kernel's WiFi regulatory domain?

It looks to me like, if I was clever, I could construct a netlink packet using `NL80211_CMD_REQ_SET_REG` but wondering if there's an easier way before I go digging too deep.

**Comment by svinota** [comment]
Didn't dig into that. Let me try to play a bit with that, I believe we fix it in some way.

**Comment by tomkcook** [comment]
I've ended up with this, as yet untested:

    iw = pyroute2.IW()
    msg = nl80211.nl80211cmd()
    msg['cmd'] = nl80211.NL80211_CMD_REQ_SET_REG
    msg['attrs'] = [['NL80211_ATTR_REG_ALPHA2', country_code.upper()]]
    iw.nlm_request(msg, msg_type=iw.prid, msg_flags=netlink.NLM_F_REQUEST | netlink.NLM_F_ACK)

But it would be nice if there was a function for doing this.

**Comment by svinota** [comment]
Yep, thanks. To be done.
