### ISSUE TITLE
pyroute2 logs "shutdown in progress" warning after ipdb.release() is called

### ISSUE THREAD

**Issue by PaulSD** [svinota/pyroute2#553]
If ipdb.release() is called (as is specified in the [documentation](https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/main.py#L153)), and logging is configured, then pyroute2 always logs "WARNING:pyroute2.ipdb.main:shutdown in progress" when python exits:
```
#!/usr/bin/env python
import logging
logging.basicConfig(level=logging.INFO)
from pyroute2 import IPDB
ipdb = IPDB()
ipdb.release()
```
It looks like the problem is:
https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/main.py#L907
and
https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/main.py#L1150

Can cleanup() be updated to skip the call to release() if _stop is True to avoid this?

**Comment by jcnaud** [comment]
Hi, i have the same problem with this code (just get the default interface name).
```python
import pyroute2
import logging
logging.basicConfig(level=logging.INFO)

with pyroute2.IPDB() as ip:
    default_iface = ip.interfaces[ip.routes['default']['oif']]['ifname']

print(default_iface)
```

Have you some way to avoid this warning ?

**Comment by jcnaud** [comment]
Hacked without package modification
```python
import pyroute2
import logging
logging.basicConfig(level=logging.INFO)

ip = pyroute2.IPDB()
try:
    default_iface = ip.interfaces[ip.routes['default']['oif']]['ifname']
finally:
    if ip._stop:
        ip.release()

print(default_iface)
```
Now, i will wait the new version of pyroute2 :)

**Comment by PaulSD** [comment]
The work-around I have been using is to call `logging.getLogger().setLevel(logging.ERROR)` at the end of the script, so that the log message is suppressed when the script exits.  But your solution works too.

**Comment by svinota** [comment]
Fixed, thanks.
