### ISSUE TITLE
Type of NL80211_ATTR_WDEV is incorrect

### ISSUE THREAD

**Issue by tomkcook** [svinota/pyroute2#556]
At pyroute2/netlink/nl80211/__init__.py:365, NL80211_ATTR_WDEV is listed as type uint32.  However, this is incorrect; see eg line 346 of net/wireless/nl80211.c in the kernel source:

	[NL80211_ATTR_WDEV] = { .type = NLA_U64 },

This causes the 32 MSBs of the WDEV to be thrown away eg in the results of `IW.get_interface_by_ifindex`.

**Comment by svinota** [comment]
Thanks a lot! Fixed
