### ISSUE TITLE
IFLA_VXLAN_xxx definitions miss some newer elements

### ISSUE THREAD

**Issue by TheDiveO** [svinota/pyroute2#557]
`netlink/rtnl/ifinfmsg/plugins/vxlan.py` misses a few more recent Linux kernel definitions, in particular:
* `IFLA_VXLAN_LABEL` of type `NLA_U32`
* `IFLA_VXLAN_GPE` of type `NLA_FLAG`
* `IFLA_VXLAN_COLLECT_METADATA` of type `NLA_U8`

Sources:
* vxlan attributes: https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/if_link.h#L531
* data types: https://elixir.bootlin.com/linux/latest/source/drivers/net/vxlan.c#L2724

**Comment by svinota** [comment]
Fixed, thanks
