### ISSUE TITLE
Duplicated rule, no NetlinkError: (17, 'File exists') raisen

### ISSUE THREAD

**Issue by ralonsoh** [svinota/pyroute2#566]
When executing a test case in OpenStack Neutron, using pyroute2 to add IP rules, the following error occurs: the same IP rule is added without having an exception.

How to reproduce:
> import pyroute2
> ip = pyroute2.NetNS('ns')
> ip.rule('add', iifname='iif_device_1', priority=100, table=100)
> ip.rule('add', iifname='iif_device_1', priority=100, table=100) # No exception risen
> print ip.get_rules()
({'flags': 0, 'dst_len': 0, 'src_len': 0, 'tos': 0, 'res2': 0, 'res1': 0, 'action': 1, 'attrs': {'FRA_SUPPRESS_PREFIXLEN': 4294967295, 'FRA_TABLE': 255}, 'family': 2, 'header': {'flags': 2, 'error': None, 'pid': 23949, 'length': 44, 'type': 32, 'sequence_number': 255}, 'event': 'RTM_NEWRULE', 'table': 255}, {'flags': 0, 'dst_len': 0, 'src_len': 0, 'tos': 0, 'res2': 0, 'res1': 0, 'action': 1, 'attrs': {'FRA_SUPPRESS_PREFIXLEN': 4294967295, 'FRA_IIFNAME': 'iif_device_1', 'FRA_TABLE': 100, 'FRA_PRIORITY': 100}, 'family': 2, 'header': {'flags': 2, 'error': None, 'pid': 23949, 'length': 72, 'type': 32, 'sequence_number': 255}, 'event': 'RTM_NEWRULE', 'table': 100}, {'flags': 0, 'dst_len': 0, 'src_len': 0, 'tos': 0, 'res2': 0, 'res1': 0, 'action': 1, 'attrs': {'FRA_SUPPRESS_PREFIXLEN': 4294967295, 'FRA_IIFNAME': 'iif_device_1', 'FRA_TABLE': 100, 'FRA_PRIORITY': 100}, 'family': 2, 'header': {'flags': 2, 'error': None, 'pid': 23949, 'length': 72, 'type': 32, 'sequence_number': 255}, 'event': 'RTM_NEWRULE', 'table': 100}, {'flags': 0, 'dst_len': 0, 'src_len': 0, 'tos': 0, 'res2': 0, 'res1': 0, 'action': 1, 'attrs': {'FRA_SUPPRESS_PREFIXLEN': 4294967295, 'FRA_TABLE': 254, 'FRA_PRIORITY': 32766}, 'family': 2, 'header': {'flags': 2, 'error': None, 'pid': 23949, 'length': 52, 'type': 32, 'sequence_number': 255}, 'event': 'RTM_NEWRULE', 'table': 254}, {'flags': 0, 'dst_len': 0, 'src_len': 0, 'tos': 0, 'res2': 0, 'res1': 0, 'action': 1, 'attrs': {'FRA_SUPPRESS_PREFIXLEN': 4294967295, 'FRA_TABLE': 253, 'FRA_PRIORITY': 32767}, 'family': 2, 'header': {'flags': 2, 'error': None, 'pid': 23949, 'length': 52, 'type': 32, 'sequence_number': 255}, 'event': 'RTM_NEWRULE', 'table': 253})

Environment:
- OS Version: Ubuntu 16.04 xenial
- pyroute2==0.5.3

Logs:
- Test case execution: http://paste.openstack.org/show/735962/

**Comment by svinota** [comment]
Yes, 'cause such exception is not raised by the library itself. The library just translates `EEXIST` returned by the kernel into the `NetlinkError` exception. If the kernel doesn't return `EEXIST`, there will be no exception.

AFAIK, the latest kernels return here `EEXIST` as one may expect.
