### ISSUE TITLE
[Question] is there any way to use pyroute2 API for non-root user?

### ISSUE THREAD

**Issue by Xeite** [svinota/pyroute2#567]
Hi. 

We are trying to use pyroute2 IPRoute() API for OpenStack neutron plugin, and this service is running on 'neutron' user (non-root). I found neutron permission handled by sudoer, so that any normal ('neutron' user) user can execute 'ip' command which requires root permission. As far as I know, pyroute2 requires 0 EUID, I could not help change service script user from 'neutron' to 'root'.

Is there any way to specify root permission at API level so that sudo user can execute IPRoute command?

Thanks in advance.

**Comment by svinota** [comment]
Pyroute2 per se does not require any permission — you can run it under whichever user you want — but netlink does require CAP_NET_ADMIN, afair. So you have to grant CAP_NET_ADMIN to the user that runs pyroute2 in order to write changes to the kernel.
