### ISSUE TITLE
NetNS() is not capable to play with files.

### ISSUE THREAD

**Issue by hetii** [svinota/pyroute2#568]
Hi, I have such example:

    from pyroute2 import IPDB
    from pyroute2 import NetNS
    from pyroute2 import NSPopen

    def main(ns_name):
        with NetNS(ns_name) as my_ns:
            with IPDB(my_ns) as ip:
                # Up loopback interface.
                with ip.interfaces.lo as lo:
                    lo.up()
                with ip.create(ifname="veth0p0", peer="veth0p1", kind='veth') as veth_link:
                        veth_link.up()
                with ip.interfaces.veth0p0 as veth0p0:
                    veth0p0.up()
                with ip.interfaces.veth0p0 as veth0p1:
                    veth0p1.up()
            fh = open("/proc/sys/net/ipv4/conf/veth0p0/proxy_arp","w")
            fh.write("1")
            fh.close()

    if __name__ == '__main__':
        main("ns_xxx_test1")
but it raise:

    python bug.py 
    Traceback (most recent call last):
      File "bug.py", line 22, in <module>
        main("ns_xxx_test1")
      File "bug.py", line 17, in main
        fh = open("/proc/sys/net/ipv4/conf/veth0p0/proxy_arp","w")
    FileNotFoundError: [Errno 2] No such file or directory: '/proc/sys/net/ipv4/conf/veth0p0/proxy_arp'

but as we can see the file is there:

    ip netns exec ns_xxx_test1 cat /proc/sys/net/ipv4/conf/veth0p0/proxy_arp
    0

**Comment by svinota** [comment]
Interesting, let me debug it a bit.

**Comment by svinota** [comment]
Sorry for delay.

`NetNS()` objects provide only RTNL API towards the kernel.

To set the network namespace for the whole process use code like that:
```python
from pyroute2 import netns
netns.setns(nsname)
with open(…) as f:
    f.write(…)
```
