### ISSUE TITLE
tcmsg error appears on stdout when no logger setup

### ISSUE THREAD

**Issue by hetmankp** [svinota/pyroute2#573]
Currently when importing pyroute2 we get an error message being dumped out to stdout when no logger has been setup yet like this:
```
tcmsg: [Errno 2] No such file or directory: '/proc/net/psched'
the tc subsystem functionality is limited
```

I would suggest setting up the logging.NullHandler in the root \_\_init\_\_.py file before all the pyroute2 submodules are imported to prevent this.

**Comment by svinota** [comment]
Yep. A good idea, testing.
