### ISSUE TITLE
pkg_resources breaks some pyroute2 use case

### ISSUE THREAD

**Issue by ffourcot** [svinota/pyroute2#584]
Hello,

Since the commit 602295ff8532a6a (ref #576), pyroute2 cannot be used anymore without real installation. I used to run pyroute2 from sources, but it raises now this:

In [1]: import pyroute2
[...]
DistributionNotFound: The 'pyroute2' distribution was not found and is required by the application

When I revert the patch, it's working again.

I understand the need to provide a version number, but could we make this optional?

**Comment by svinota** [comment]
What if we run this code only when not in a git repo?

**Comment by svinota** [comment]
Another solution: add the code while `setup.py install` (hack but also could work)

**Comment by svinota** [comment]
And I would fix & close that today, since it annoys a bit.

**Comment by crosser** [comment]
I'd suggest to:

1. create the file with version from setup.py (so it works in packages *and* in pip etc.)
2. import the file with version under "try" and default the version to "unknown" or something

**Comment by svinota** [comment]
Ok, so do I.

**Comment by svinota** [comment]
Or maybe even simpler.

@crosser , @ffourcot look at the patch if you have some comments.

If you do not object, I merge it into the master.

**Comment by ffourcot** [comment]
@svinota: it's fine for me

**Comment by svinota** [comment]
Merged. Pls check if it works for you.

Thank you!
