### ISSUE TITLE
Operation not permitted and <defunct> process when call netns.remove()

### ISSUE THREAD

**Issue by hetii** [svinota/pyroute2#594]
In function https://github.com/svinota/pyroute2/blob/45a350dd47e803fa9a35afe0d92c3b0ce7abb460/pyroute2/netns/__init__.py#L207
We have call to os.unlink(), 
the problem can happen for eg in kubernetes (k8s.gcr.io/pause:3.1) where this can raise PermissionError: [Errno 1] Operation not permitted: b'/proc/17066/ns/net'

After that I see in process list, a python process in defunct state.

**Comment by svinota** [comment]
Any particular reason why it's closed?

**Comment by hetii** [comment]
@svinota Well I notice that probably I should not use direct path for network namespace that belong to some process and use on it a remove() method, this only might to work if pyroute2 will make some sort bind-mount to another place and work with it instead, but then the real namespace will not be removed.
So it`s look like my bad design, so sorry for probably false alarm.

**Comment by svinota** [comment]
Np, it's always useful to look at the code from some unexpected perspective, so thanks :)
