### ISSUE TITLE
IPRoute().get_routes(table=0) does not return any routes

### ISSUE THREAD

**Issue by jimfunk** [svinota/pyroute2#604]
Netlink allows for dumping routes in all tables by setting the table to 0. You can do this with iproute2:

    ip route show table 0

However, this is not possible with get_routes():

    >>> pyroute2.IPRoute().get_routes(table=0)
    ()

The code reveals a way to trick it, but it's non-obvious:

    >>> pyroute2.IPRoute().route('dump', match={}, table=0, family=255)
    ...all the routes...

**Comment by svinota** [comment]
The `get_routes()` arguments except of `family` work as filter.

Simply run `get_routes ()` without any arguments to fetch all the routes in the system.

**Comment by jimfunk** [comment]
Regardless of arguments , get_routes() only returns routes in table 254 (main). get_routes() always passes kwargs to the match parameter of route('dump'):

            return self.route('dump',
                              family=family,
                              match=match or kwarg)

and route() will set the table to 254, since kwarg is empty:

        table = kwarg.get('table', 254)
        msg['table'] = table if table <= 255 else 252

This means the table is always 254, and the table passed to get_routes() is later used as a filter. Therefore, passing a table argument to get_routes() that is anything other than 254 yields no results.

You can also simply compare the output of:

    ip route show table 0

and 

    pyroute2.IPRoute().get_routes()

and you will see that it only returns only the routes in table 254.

**Comment by svinota** [comment]
```
In [1]: from pyroute2 import IPRoute

In [2]: ipr = IPRoute()

In [3]: set([x['table'] for x in ipr.get_routes()])
Out[3]: {252, 254, 255}
```

Which pyroute2 version do you use?

**Comment by jimfunk** [comment]
Ah, you're right. The box I was testing on had an older version, but reading the code indicated it was putting table 254 in the message so I thought it would be the same behaviour. Seems the msg['table'] gets ignored. No matter what I set that to, I always get the same routes...

Sorry for the noise.

**Comment by svinota** [comment]
No-no, thank you for the heads-up. I have to review the code, there may be a hidden issue if something gets ignored. And even if there is nothing bad, the reivew is not a bad idea.
