### ISSUE TITLE
Cannot change interface namespace with NDB module.

### ISSUE THREAD

**Issue by gryf** [svinota/pyroute2#614]
I'm trying to move an interface using NDB module:

```python
    def move_iface_to_ns(veth, ns):
        with pyroute2.NDB() as ndb:
            ndb.sources.add(netns=ns)
            with ndb.interfaces[veth.tap] as dev:
                dev.update({'target': ns})
```

It freezes for couple of seconds, and gives me:

```
Exception: lost sync in apply()
```

moreover, it will create pair of veth in the namespace. Before calling the function:

```console
# ip netns exec ns1 ip l
 1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
 ```
After:

```console
# ip netns exec ns1 ip l
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
43: veth0@veth-1: <BROADCAST,MULTICAST,M-DOWN> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether da:f7:f1:8b:69:05 brd ff:ff:ff:ff:ff:ff
161: veth-1@veth0: <BROADCAST,MULTICAST,M-DOWN> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether ea:1a:98:d8:42:57 brd ff:ff:ff:ff:ff:ff
```

while I expected, that one end of veth pair will land in the namespace. Using IPRoute() object works.

**Comment by svinota** [comment]
Thanks! Investigating

**Comment by svinota** [comment]
There were two ways to move a veth peer to a netns:

1. upon creation
```python
(ndb
 .interfaces
 .create(ifname='v0p0', kind='veth', peer={'ifname': 'v0p1', 'net_ns_fd': nsname})
 .commit())
```

2. moving an existing interface
```python
(ndb
 .interfaces
 .create(ifname='v0p0', kind='veth', peer='v0p1')
 .commit())

with ndb.interfaces['v0p1'] as dev:
    dev['net_ns_fd'] = nsname
```

Now thanks to your ticket there are three ways :) The third one:
```python
(ndb
 .interfaces
 .create(ifname='v0p0', kind='veth', peer='v0p1')
 .commit())

with ndb.interfaces['v0p1'] as dev:
    dev['target'] = nsname
```

**NB**: it is **not** necessary to connect the netns source to move an interface.

**Comment by gryf** [comment]
Oh, nice! I didn't know that peer could be actually a dict :) Documentation for NDB module isn't very extensive. As for adding namespace to the source, I was unable to set the address for the iface inside netns, I've get the KeyError, until added to the source, that's why I done that that way. Probably it is also resolvable via passing right dictionary to right keyword…

**Comment by svinota** [comment]
NDB objects are used as `**kwarg` for IPRoute calls, so it's the same as described here: https://docs.pyroute2.org/iproute.html#pyroute2.iproute.linux.RTNL_API.link , see «add … veth»

The NDB docs aren't ready since the module is quite new and still «under construction». I'm to fix the docs asap.

**Comment by gryf** [comment]
Now it makes sense :) Maybe it's worth to mention how to use NDB objects by putting the one or two sentences and a link for IPRoute usage somewhere at the beginning of the NDB docs :)

**Comment by svinota** [comment]
Agree.

**Comment by svinota** [comment]
Docs updated (see the commit above), soon will be on the site.

**Comment by gryf** [comment]
Awesome! This issue can be closed now.
