### ISSUE TITLE
netns: make /var/run/netns bind-mount recursive

### ISSUE THREAD

**Issue by ralonsoh** [svinota/pyroute2#640]
Related bug: https://patchwork.ozlabs.org/patch/796300/

When ip netns {add|delete} is first run, it bind-mounts /var/run/netns on top of itself, then marks it as shared. However, if there are already bind-mounts in the directory from other tools, these would not be propagated. Fix this by recursively bind-mounting.

**Comment by ralonsoh** [comment]
https://github.com/svinota/pyroute2/pull/641

**Comment by svinota** [comment]
Fixed by: https://github.com/svinota/pyroute2/pull/641

Thanks, @ralonsoh
