### ISSUE TITLE
is it possible to define device on ip.route.add()?

### ISSUE THREAD

**Issue by phoracek** [svinota/pyroute2#65]
like in `ip` command: `ip route add default via fdb3:84e5:4ff4:55e3::ff dev name`

**Comment by chelliwell** [comment]
Hi,
Just resurrecting this thread, if I may. 
Re. the actual topic - how did you determine the value of 9 for oif? I guess there's another API call to discover it?
As a follow on, is it possible to just change a route's metric?

Sorry if this is newbie stuff, but I've only just started exploring pyroute2.... (pointers welcome!). In fact, when I try exploring your example above, I'm stuck on a 'no module named pdb' error - is it possible to fire it up without debugger?

Thanks.
