### ISSUE TITLE
Inconsistency in "magic attributes"

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#650]
"magic attributes" introduced in response to #621 mostly work very nicely.
But I've run into an inconsistency as I was dealing with conntrack table:

```
>>> l[0].CTA_TUPLE_ORIG
{'attrs': [('CTA_TUPLE_IP', {'attrs': [('CTA_IP_V4_SRC', '0.0.0.0'), ('CTA_IP_V4_DST', '255.255.255.255')]}, 32768), ('CTA_TUPLE_PROTO', {'attrs': [('CTA_PROTO_NUM', 17), ('CTA_PROTO_SRC_PORT', 68), ('CTA_PROTO_DST_PORT', 67)]}, 32768)]}
>>> l[0].CTA_TUPLE_ORIG.CTA_TUPLE_IP.CTA_IP_V4_SRC
{'attrs': [], 'header': {'type': 1, 'length': 8}, 'value': b'\x00\x00\x00\x00'}
>>> l[0].CTA_TUPLE_ORIG.CTA_TUPLE_IP.CTA_IP_V4_SRC.value
'0.0.0.0'
>>> l[0].CTA_TUPLE_ORIG.CTA_TUPLE_PROTO.CTA_PROTO_NUM
{'header': {'type': 1, 'length': 5}, 'value': 17}
>>> l[0].CTA_TUPLE_ORIG.CTA_TUPLE_PROTO.CTA_PROTO_NUM.value
<class 'pyroute2.netlink.NotInitialized'>
```

I would expect CTA_PROTO_NUM.value to return the number 17. Does it not work because there is no 'attrs' attribute in CTA_PROTO_NUM?

**Comment by crosser** [comment]
Since then and till now I am using something along the lines of:
```
def _value(attr):
    return attr["value"] if attr.value is NotInitialized else attr.value
```
and it seems to work, but...

**Comment by svinota** [comment]
Yep, got it. Thanks!

**Comment by svinota** [comment]
@crosser which version do you use?

**Comment by svinota** [comment]
The access to the attributes via exceptions in `__getattribute__()` was completely removed in February/March in version 0.5.15 due to a) performance penalty b) usage of `re`. 

See also: 3e485542722e3cdc58b1277b12366424a176fe23

I'm not really sure should we reintroduce it. Simple attr may be retrieved with `get_attr()`, nested attrs with `get_nested()`

**Comment by crosser** [comment]
Actually `get_nested()` works fine for me:
```
>>> ipr.link("get", index=619)[0].get_nested('IFLA_LINKINFO','IFLA_INFO_DATA','IFLA_VRF_TABLE')
400000000
>>> ipr.link("get", index=619)[0].get_nested('IFLA_LINKINFO','IFLA_INFO_KIND')
'vrf'
```
though I definitely would not be able to find it with documentation like this :wink: 
```
    def get_nested(self, *attrs):
        '''
        Return nested NLA or None
        '''
```

**Comment by svinota** [comment]
does `get_nested()` fit? or there is something that we can add there?

**Comment by crosser** [comment]
Yes, it works all right, and the changes are going to be mechanical. The problem will be to find all the places...

**Comment by svinota** [comment]
I can prepare a branch that will issue a warning every time when a «magic attribute» is accessed.

It will not be merged to the master branch due to the same performance issues, but may help to locate all or most of the places just by running the code.

**Comment by crosser** [comment]
No, thank you, I hope `grep -r IFLA_` in my home directory will suffice.
We would not be able to use a branch anyway, nor hope to catch all the error messages.

**Comment by svinota** [comment]
I'm really sorry for the disturbance.

**Comment by crosser** [comment]
It's OK, this one is manageable.
Closing it then.
