### ISSUE TITLE
Wireguard endpoint addresses not being set

### ISSUE THREAD

**Issue by stevekerrison** [svinota/pyroute2#668]
I've created a demonstration of my problem in https://github.com/svinota/pyroute2/pull/667 by extending the test case for wireguard.

In short: the `endpoint_addr` and `endpoint_port` are not being set.

Running in the following environment:

```
version: 0.5.7-57-g014e2af3
kernel: 5.3.0-28-generic
python: /usr/local/bin/python [Python 3.7.6]
flake8: /usr/local/bin/flake8 [3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.7.6 on Linux]
```

I get this as the output of `wg show ${interface}`:

```
interface: pr63c6d68f
  public key: FZ8nQlgAg7JIViZTAarlvMb9/e89jLdZ+mc3LBqAOmI=
  private key: (hidden)
  listening port: 2525
  fwmark: 0x1337

peer: TGFHcm9zc2VCaWNoZV9DJ2VzdExhUGx1c0JlbGxlPDM=
  allowed ips: 172.16.255.0/24, 172.16.254.0/24
  persistent keepalive: every 15 seconds
```

The last part should look more like:

```
peer: TGFHcm9zc2VCaWNoZV9DJ2VzdExhUGx1c0JlbGxlPDM=
  endpoint: 172.16.254.1:8888
  allowed ips: 172.16.255.0/24, 172.16.254.0/24
  persistent keepalive: every 15 seconds
```

So for whatever reason, the endpoint address and port aren't making their way through netlink set properly.

**Comment by svinota** [comment]
Thanks, investigating!

**Comment by svinota** [comment]
It may be a bit better now, pls check if it helped.

**Comment by stevekerrison** [comment]
Sorry for the slow reply, I'll test it today/tomorrow on my side.

**Comment by stevekerrison** [comment]
Seems to fix things! Thanks very much.
