### ISSUE TITLE
[ERROR]: No module named pyroute2

### ISSUE THREAD

**Issue by byteshiva** [svinota/pyroute2#672]
I'm using Ubuntu 19.10, I followed all the steps for installation. but still fails to execute the below program. Am i missing something here. I've install bcc etc;

```
pip install pyroute2
```

```
Traceback (most recent call last):
  File "./simple_tc.py", line 6, in <module>
    from pyroute2 import IPRoute
ImportError: No module named pyroute2

```

```
chmod 777 simple_tc.py
sudo ./simple_tc.py
```

**simple_tc.py**
```
#!/usr/bin/python
# Copyright (c) PLUMgrid, Inc.
# Licensed under the Apache License, Version 2.0 (the "License")

from bcc import BPF
from pyroute2 import IPRoute

ipr = IPRoute()

text = """
int hello(struct __sk_buff *skb) {
  return 1;
}
"""

try:
    b = BPF(text=text, debug=0)
    fn = b.load_func("hello", BPF.SCHED_CLS)
    ipr.link("add", ifname="t1a", kind="veth", peer="t1b")
    idx = ipr.link_lookup(ifname="t1a")[0]

    ipr.tc("add", "ingress", idx, "ffff:")
    ipr.tc("add-filter", "bpf", idx, ":1", fd=fn.fd,
           name=fn.name, parent="ffff:", action="ok", classid=1)
    ipr.tc("add", "sfq", idx, "1:")
    ipr.tc("add-filter", "bpf", idx, ":1", fd=fn.fd,
           name=fn.name, parent="1:", action="ok", classid=1)
finally:
    if "idx" in locals(): ipr.link("del", index=idx)
print("BPF tc functionality - SCHED_CLS: OK")

```

**Comment by svinota** [comment]
Please run these four commands and post here the output like that:
```
$ pip list | grep pyroute2
pyroute2         0.5.7  

$ python -c "import pyroute2; print(pyroute2.__file__)"
/usr/local/lib/python3.7/dist-packages/pyroute2/__init__.py

$ python -c "import sys; print(sys.path)"
['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages']

$ python -V
Python 3.7.2+
```

**Comment by byteshiva** [comment]
Here are the details.
```
$ pip list | grep pyroute2 
pyroute2               0.5.7.post67


$ pip3 list | grep pyroute2 
pyroute2               0.5.7.post67


$ python -c "import pyroute2; print(pyroute2.__file__)"
/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pyroute2/__init__.py

$ python -c "import sys; print(sys.path)"
['', '/home/xyz/.asdf/installs/python/3.8.0/lib/python38.zip', '/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8', '/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/lib-dynload', '/home/xyz/.local/lib/python3.8/site-packages', '/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages']

$ python -V
Python 3.8.0
```

> Please run these four commands and post here the output like that:
> 
> ```
> $ pip list | grep pyroute2
> pyroute2         0.5.7  
> 
> $ python -c "import pyroute2; print(pyroute2.__file__)"
> /usr/local/lib/python3.7/dist-packages/pyroute2/__init__.py
> 
> $ python -c "import sys; print(sys.path)"
> ['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages']
> 
> $ python -V
> Python 3.7.2+
> ```

**Comment by svinota** [comment]
Looks like the library is installed in the home directory or in a virtualenv. Thus, the script you're trying should be run under the same user and with the env set up properly. If you're running script under a different user, pls check `PYTHONPATH` and that the user has access to the installed files. Pls be aware that `sudo` resets the env variables, unless you change this behaviour with `visudo`.

**Comment by byteshiva** [comment]
> Looks like the library is installed in the home directory or in a virtualenv. Thus, the script you're trying should be run under the same user and with the env set up properly. If you're running script under a different user, pls check `PYTHONPATH` and that the user has access to the installed files. Pls be aware that `sudo` resets the env variables, unless you change this behaviour with `visudo`.

Thanks for the direction, I Got it, 

Unfortunately the `simple_tc.py` expects to run with `sudo` permission. all ebpf expects to be run with sudo permission. Also I use [asdf](https://asdf-vm.com/#/), its package manager for multiple run times(python golang , nodejs etc and many more).

I was using python3 for development but in sudo(root permission) its in python2 installed by default in OS and I installed pyroute2 in virualenv with wrapper `asdf-vm`.

Now its been fixed in short run but It would be good If I use some docker/ansible or something similar to maintain installations on Linux. 

now that I've just installed  `pyroute2` in sudo using `pip install pyroute2`, it started working. 

Excuse me for the lengthy explanation. Now it works, Thanks


Steps that I did to make it work, Adding it for any future reference.

````
@-desktop:~/tmp/ebpf$ sudo -s
[sudo] password for : 
root@-desktop:/home//tmp/ebpf# python 
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 9.2.1 20191008] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

root@-desktop:/home/tmp/ebpf# pip3 install pyroute2 
Collecting pyroute2
  Downloading https://files.pythonhosted.org/packages/6b/94/2a5f6c11369a21efd27a0b4cb92adf5012da7acdbce7e78055710986ca23/pyroute2-0.5.7.tar.gz (718kB)
    100% |████████████████████████████████| 727kB 875kB/s 
Building wheels for collected packages: pyroute2
  Running setup.py bdist_wheel for pyroute2 ... done
  Stored in directory: /root/.cache/pip/wheels/2a/0c/02/09e5981f7d5164fee9cae85f34b245141843c2cce5ead22bff
Successfully built pyroute2
Installing collected packages: pyroute2
Successfully installed pyroute2-0.5.7

root@-desktop:/home/tmp/ebpf# ./simple_tc.py 
Traceback (most recent call last):
  File "./simple_tc.py", line 6, in <module>
    from pyroute2 import IPRoute
ImportError: No module named pyroute2

root@-desktop:/home//tmp/ebpf# pip list | grep pyroute2

root@-desktop:/home//tmp/ebpf# pip3 list | grep pyroute2
pyroute2                0.5.7          
root@-desktop:/home//tmp/ebpf# pip install pyroute2 
Collecting pyroute2
  Using cached https://files.pythonhosted.org/packages/6b/94/2a5f6c11369a21efd27a0b4cb92adf5012da7acdbce7e78055710986ca23/pyroute2-0.5.7.tar.gz
Building wheels for collected packages: pyroute2
  Running setup.py bdist_wheel for pyroute2 ... done
  Stored in directory: /root/.cache/pip/wheels/2a/0c/02/09e5981f7d5164fee9cae85f34b245141843c2cce5ead22bff
Successfully built pyroute2
Installing collected packages: pyroute2
Successfully installed pyroute2-0.5.7


root@-desktop:/home//tmp/ebpf# pip list | grep pyroute2
pyroute2                           0.5.7          

root@-desktop:/home//tmp/ebpf# ./simple_tc.py 
BPF tc functionality - SCHED_CLS: OK



```
