### ISSUE TITLE
Cannot create bitmap:port ipset

### ISSUE THREAD

**Issue by resloved** [svinota/pyroute2#676]
I was trying to create a bitmap:port ipset and was receiving an unknown netlink error. So I tried the example shown in ipset.py: https://github.com/svinota/pyroute2/blob/8216d3f84738cf5cc77870a3410f779c60059e49/pyroute2/ipset.py#L398-L400

```
>>> import pyroute2
>>> ipset = pyroute2.IPSet()
>>> ipset.create("bar", stype="bitmap:port", bitmap_ports_range=(1000, 2000))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyroute2/ipset.py", line 143, in request
    msg_flags, terminate=terminate)
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 373, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 870, in nlm_request
    callback=callback):
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 707, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (4097, 'Unknown error 4097')
```

If I try to create the same ipset normally it works as expected:

```
root@l-bon:~# ipset create bar bitmap:port range 1000-2000
root@l-bon:~# ipset list
Name: bar
Type: bitmap:port
Revision: 3
Header: range 1000-2000
Size in memory: 200
References: 0
Members:
```

I'm using python3 and pyroute2 v0.5.7-1

**Comment by svinota** [comment]
Yep, I confirm the issue, thanks for notifying. To be fixed asap.

**Comment by svinota** [comment]
The fix is submitted to the master branch and will be included in the next release.

**Comment by ffourcot** [comment]
I'm surprised that the CI didn't detect it, since we have some tests for this kind of ipset. It looks like a kernel API change, when IPSet version 7 was added (https://lwn.net/Articles/769839/)

**Comment by svinota** [comment]
@ffourcot exactly. And I hope that the fix doesn't break anything on the old kernels.

**Comment by resloved** [comment]
My quick tests seem to be working on ipset v6.23. You'll probably want to confirm some things on your end, but LGTM :+1:

**Comment by svinota** [comment]
Good, thanks.
