### ISSUE TITLE
import pkg_resources can be very slow

### ISSUE THREAD

**Issue by charleseidsness** [svinota/pyroute2#677]
Running on a little imx6ul processor "import pkg_resources" can take 6 seconds or more. It looks like all it is doing is loading the __version__. I've patched it on my system to remove it, something you may want to consider.

**Comment by svinota** [comment]
Got it, thanks for the issue. I'll try to look what may be wrong there.

**Comment by svinota** [comment]
Related:

* https://github.com/svinota/pyroute2/issues/576
* https://github.com/svinota/pyroute2/pull/580
* https://github.com/svinota/pyroute2/issues/584

**Comment by svinota** [comment]
@ffourcot @celebdor 

Looks like `pkg_resources` seriously affects startup time on platforms like ARM, and I can confirm that after tests.

I'm going to drop `pkg_resources` and provide `__version__` by something like generating `__version__.py` file on `make dist`. Any objections?

**Comment by crosser** [comment]
Not an objection, just some considerations to keep: semantics will be slightly different.

At runtime, version from pkg_resources will show the version of _installed_ package, while version from a generated file will show the version of the package that _is currently running_. It may be different if you e.g. use an instance from the current directory. And in this case, generated file will show "more correct" information, but on the other hand, if you try to use an instance with not yet generated file, it may crash if import of this file is unconditional.

**Comment by ffourcot** [comment]
Not an objection at all, we don't use it and we internally avoid usage of pkg_resources for the same reasons.

@celebdor was author of the commit adding pkg_resources, it's probably a good idea to check with him if this semantic change is ok for him.

**Comment by celebdor** [comment]
Sounds good

**Comment by svinota** [comment]
So be it — `pkg_resources` import is dropped. The version file import is enveloped in try/except, should not fail on import errors.
