### ISSUE TITLE
question: is it posible to add, delete nftable rules

### ISSUE THREAD

**Issue by rakafo** [svinota/pyroute2#682]
Docs suggest there is some netfilter functionality, but other than this opaque lead I couldn't find any mode details. Would like to do the following - add, remove rules from nftables, accept packets queued in nftables to userspace for further processing (i.e. ... queue num 1)

Are these things possible?

**Comment by svinota** [comment]
You're right, I have to document it properly. There is some basic functionality, you can read this file:

https://github.com/svinota/pyroute2/blob/master/pyroute2/nftables/main.py

https://github.com/svinota/pyroute2/blob/08fc5dd8a83f88485fb965df9f1c6346e66bb969/pyroute2/nftables/main.py#L49

https://github.com/svinota/pyroute2/blob/08fc5dd8a83f88485fb965df9f1c6346e66bb969/pyroute2/nftables/main.py#L62-L70

https://github.com/svinota/pyroute2/blob/08fc5dd8a83f88485fb965df9f1c6346e66bb969/pyroute2/nftables/main.py#L90-L98

**Comment by rakafo** [comment]
Thanks for the reply. Looking at the examples helped me determine what I needed.
