### ISSUE TITLE
When can we expect the next release?

### ISSUE THREAD

**Issue by mawiegand** [svinota/pyroute2#685]
There are some bug fixes like eebf58da2f0a66c069ec293698311ec896568b07 or bc365a8a6949369cb6c0a21788ba0ed3c04206eb my software relies on.

Are there any plans for releasing the next version?

Thanks! :smile:

**Comment by svinota** [comment]
A good question. How about tonight?

**Comment by mawiegand** [comment]
Sounds good! :laughing:

**Comment by svinota** [comment]
0.5.10 is tagged

**Comment by mawiegand** [comment]
That's awesome! Thanks a lot! :grinning:
