### ISSUE TITLE
Unexpected error log message for NDB events

### ISSUE THREAD

**Issue by svet-b** [svinota/pyroute2#688]
I've started noticing a lot of log messages along the lines of
```
[ERROR] pyroute2.ndb.main:910: ({'family': 2, '__pad': (), 'ifindex': 2, 'state': 4, 'flags': 0, 'ndm_type': 1, 'attrs': [('NDA_DST', '192.168.1.X'), ('NDA_LLADDR', '00:40:ad:XX:XX:XX'), ('NDA_PROBES', 0), ('NDA_CACHEINFO', {'ndm_confirmed': 4125, 'ndm_used': 4345, 'ndm_updated': 0, 'ndm_refcnt': 1})], 'header': {'length': 76, 'type': 28, 'flags': 0, 'sequence_number': 0, 'pid': 0, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'RTM_NEWNEIGH'},)
```
(the "X"s are me anonymizing MAC/IP addresses)

These are issued by the following line of code: https://github.com/svinota/pyroute2/blob/0.5.10/pyroute2/ndb/main.py#L910, in what appears to be an event handler loop. If I'm not mistaken, these should be DEBUG-level messages, in case event info needs to be dumped to the log - but they are accidentally being issued at ERROR-level.

If my interpretation is wrong and they are indeed error messages, it would be good to understand the nature of the error in question.

**Comment by svinota** [comment]
Oh crap. I forgot to remove this :|

Such a shame.
