### ISSUE TITLE
Generic netlink protocol ethtool not found

### ISSUE THREAD

**Issue by alxvls** [svinota/pyroute2#691]
Hi,
Could you please help me understand what I'm missing:

Python 3.6.9
[GCC 8.3.0] on linux
>>> from pyroute2 import ethtool
>>> etht = ethtool.Ethtool()
ERROR:root:Generic netlink protocol ethtool not found
ERROR:root:Please check if the protocol module is loaded

and looks like this happens specifically in this place
>>> _with_nl.is_nlethtool_in_kernel()
ERROR:root:Generic netlink protocol ethtool not found
ERROR:root:Please check if the protocol module is loaded

If this is about kernel module I haven't been able to figure out its name.

Also example of using pyroute2 for disabling tx and rx checksum offloading would be highly appreciated.

**Comment by svinota** [comment]
The ethtool via generic netlink was added to the kernel recently and most probably your kernel hasn't it. It means that `Ethtool()` will continue to work on your system via ioctl instead of netlink. 

Regarding the examples — @inemajo , may I ask you to assist? Thanks

**Comment by inemajo** [comment]
Here is an example for disabling tx checksum offload, I will add it on examples of pyroute2.
All keys are the same like "ethtool -k eth0"

`from pyroute2.ethtool import Ethtool`
`ethtool = Ethtool()`
`features = ethtool.get_features("eth0")`
`features.features["tx-checksum-ip-generic"].enable = False`
`ethtool.set_features("eth0", features)`
`ethtool.close()`

You need to pull today's commits for having somes fixes on features

**Comment by ffourcot** [comment]
@svinota we should perhaps silent a little bit this logger for ethtool ? Since we have a fallback mode, that is not really an error

**Comment by svinota** [comment]
I will turn it into log.debug + link to the docs. I do that tonight.

**Comment by vlasov-alexandr89** [comment]
thanks for all the answers

**Comment by svinota** [comment]
@vlasov-alexandr89 now should be better with logging also

**Comment by pspacek** [comment]
I sense this could be closed, maybe?
