### ISSUE TITLE
Allow to pass the libc when opening a namespace context

### ISSUE THREAD

**Issue by ralonsoh** [svinota/pyroute2#702]
"netns.nslink.NetNS" calls "netns.setns". "setns" method allows to set explicitly the libc to be used. For example, instead of using CDLL, PyDLL could be used. This could help, when using eventlet, to make calls without releasing the GIL.

References:
- https://review.opendev.org/#/c/717017/
- https://docs.python.org/3.6/library/ctypes.html#ctypes.PyDLL

**Comment by svinota** [comment]
Reasonable, fixed.

Do you need a release to be tagged asap, or it can wait?

**Comment by ralonsoh** [comment]
Hi Peter:

No, there is no rush. We'll wait for a new release and then we'll bump the min version required in Neutron.

Regards!

**Comment by ralonsoh** [comment]
Sorry but in [1] you should pass the libc variable to setns. This should be:
  setns(self.netns, self.flags, libc=libc)

[1]https://github.com/svinota/pyroute2/commit/628381f43d7a0edf97c083588aaa99f4b7dd5c10#diff-dcc31244f805780321e3b09d4772a480R152

**Comment by svinota** [comment]
Ough, my bad. Thanks a lot.

**Comment by ralonsoh** [comment]
Thanks a lot!
