### ISSUE TITLE
IPRoute: add support for setting a host route

### ISSUE THREAD

**Issue by yegorich** [svinota/pyroute2#716]
AFAIK it is now not possible to set the host route like this:

    route add -host 192.168.0.50 dev wlan0

The following code throws `pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')`:

```python
from pyroute2 import IPRoute

ip = IPRoute()
ip.route("add", dst="192.168.0.50", gateway="192.168.0.3")
```

**Comment by svinota** [comment]
Ok, I'll look what can we do with that. Thanks!

**Comment by liske** [comment]
> The following code throws `pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')`:
> 
> ```python
> from pyroute2 import IPRoute
> 
> ip = IPRoute()
> ip.route("add", dst="192.168.0.50", gateway="192.168.0.3")
> ```

This has several issues:
- `dst` is not valid - netlink requires you to use CIDR notation
- you are trying to create a *static* route (providing a `gateway`) - using the legacy route command from above you tried to create a *connected* route

The corresponding *pyroute2* code should look like:

```python
from pyroute2 import IPRoute

ip = IPRoute()
ip.route("add", dst="192.168.0.50/32", oif=ip.link_lookup(ifname='wlan0'))
```

**Comment by yegorich** [comment]
@liske thanks, that helped.

**Comment by liske** [comment]
> @liske thanks, that helped.

Please consider to close this issue since it seems to be resolved.
