### ISSUE TITLE
ipr.addr() is asynchronous

### ISSUE THREAD

**Issue by rubasov** [svinota/pyroute2#721]
While working with OpenStack Neutron code using pyroute2 I came to a question and depending on the answer I may have found a bug.

The existing Neutron code seemingly assumed that pyroute2.NetNS().addr() is synchronous (that is it returns only after the requested address was actually configured). In older use cases this assumption seemed to be correct, but when I started to configure IPv6 link-local addresses with the same code (plus with a few more constraints, please see below) I started to see that it returns before the address got configured therefore a socket.bind() following it closely started to fail with EADDRNOTAVAIL.

So my question is: Is it supposed to be synchronous or not? (I did not find an answer clear to me in the docs.)

If not, is there a recommended way of synchronizing (blocking until the address gets configured) by the user of pyroute2?

If it is then here's how to reproduce the bug:

versions used:
pyroute2 0.5.12
Linux kernel 4.15.0
Open vSwitch 2.9.5
iproute2 ss180129
Python 3.6.9

The two scripts below should be placed in the same directory on a Linux system (with netns support) where python3, pyroute2, Open vSwitch and iproute2 are all installed (for example an OpenStack devstack VM, but devstack is not neccessary). Run the .sh as root.

This is the output on my system:
```
$ sudo ./pyroute-addr-async.sh
ip.addr() ; sleep(0) ; bind()
Traceback (most recent call last):
  File "./pyroute-addr-async.py", line 35, in <module>
    s.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

ip.addr() ; sleep(5) ; bind()
[no error printed]
```

I believe that proves that the address gets configured, but only several seconds after ipr.addr() returned.

```
pyroute-addr-async.sh

#! /bin/bash

# This script reproduces the following bug:
# ip.addr() of pyroute2 seems to be not synchronous at least when
# the address configured is an IPv6 link-local address put on an
# Open vSwitch port in a namespace.
# Therefore ip.addr() and socket.bind() in short succession may make
# socket.bind() fail, becaues the IP is not configured yet.
# So far I could not reproduce this without using an Open vSwitch port.

namespace="ns0"
bridge="br0"
interface="port0"

# with sleep(0) bind() fails with EADDRNOTAVAIL:
#     OSError: [Errno 99] Cannot assign requested address
# with sleep(5) bind() succeeds
for sleep in 0 5
do

    ovs-vsctl add-br "$bridge"
    ovs-vsctl add-port "$bridge" "$interface" \
        -- set Interface "$interface" type=internal

    ip netns add "$namespace"

    ip link set up dev "$interface" netns "$namespace"

    echo >&2 "ip.addr() ; sleep($sleep) ; bind()"
    ip netns exec ns0 ./pyroute-addr-async.py "$sleep"
    echo >&2

    ovs-vsctl del-port "$interface" 2>/dev/null
    ovs-vsctl del-br "$bridge" 2>/dev/null
    ip netns del "$namespace" 2>/dev/null

done
```

```
pyroute-addr-async.py

#! /usr/bin/python3

import pyroute2
import socket
import sys
import time

namespace = 'ns0'
address = 'fe80::a9fe:a9fe'
interface = 'port0'
port = 80

sleep = int(sys.argv[1])

ip = pyroute2.NetNS(namespace, flags=0)
idx = ip.link_lookup(ifname=interface)[0]
ip.addr(
    'add',
    index=idx,
    address=address,
    mask=64,
    family=socket.AF_INET6,
    scope=253, # cf. /etc/iproute2/rt_scopes
)

time.sleep(sleep)

s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
sockaddr = (
    address + '%' + interface,
    port,
    0,
    idx,
)
s.bind(sockaddr)
```

p.s. to Peter: No long time no see. I hope you're doing well.

**Comment by rubasov** [comment]
The underlying behavior seems more complex than what I originally thought.

If I try to synchronize by blocking until I can read back the configured address, like:

```
[snipped ip.addr()]

wait = 0
interval = 1
timeout = 5
while wait <= timeout:
    time.sleep(interval)
    wait += interval
    addresses = set(
        [(dict(record['attrs'])['IFA_ADDRESS'], record['index'])
         for record in ip.get_addr()])
    if (address, idx) in addresses:
        break

[snipped bind()]
```

The the address configured is found at the earliest attempt, so this piece of code no longer blocks, but bind() still fails after this for a few seconds.

I don't understand the root cause at the moment, just wanted to share the observation.

**Comment by crosser** [comment]
I did not look into the details of the process, but I have a hunch that this has something to do with IPv6 DAD. Quite often when you assign an address and immediately start an application that tries to tries to send something, you get an error along the lines of "local address is not available".

**Comment by rubasov** [comment]
This was a great hunch. I tested it and as soon as I disabled DAD, the problem went away. So there's no pyroute2 bug here, sorry for the false alarm. Thank you for your help!
