### ISSUE TITLE
IPRoute.link_lookup(address='fa:16:3e:92:6b:39') returns [] on 0.5.13

### ISSUE THREAD

**Issue by johnsom** [svinota/pyroute2#724]
On 0.5.13 link_lookup using an address only returns [] where on 0.5.12 the same lookup returns the proper index.

To reproduce on 0.5.13:
```
import pyroute2
ipr = pyroute2.IPRoute()
ipr.link_lookup(address='<valid MAC>')
```
Result:
[]

No matter what MAC I put in, I always get []

On 0.5.12:
```
import pyroute2
ipr = pyroute2.IPRoute()
ipr.link_lookup(address='<valid MAC>')
```
Result:
[14]

This issue has broken OpenStack Octavia.

**Comment by johnsom** [comment]
In this patch: https://github.com/svinota/pyroute2/commit/3e0b8bd2a34a188f41c465d5313a5dc9fee8db2f

if list(kwarg) <= ['index', 'ifname']:

evaluates to:
>>> ['address'] <= ['index', 'ifname']
True

Which then leads to this exception:
(22, 'Invalid argument')
and [] always being returned.

**Comment by ffourcot** [comment]
Since I'm filling a little bit guilty, I made a small proposal to fix this regression.

It's a side effect of https://github.com/svinota/pyroute2/issues/712

**Comment by johnsom** [comment]
I can confirm that this proposed patch resolves our use case.

If this is an acceptable patch for all, can we get a release that includes it soon?

**Comment by smurfix** [comment]
Shouldn't this issue be closed?

**Comment by johnsom** [comment]
I agree, 0.5.14 resolves the issue, so I will click the closed button. Apologies if I am not following the process on this project.
