### ISSUE TITLE
Support for OpenVPN?

### ISSUE THREAD

**Issue by rgrewe** [svinota/pyroute2#731]
Hi, 
is there any way to create and manage interfaces using OpenVPN?

Kind regards
Raphael

**Comment by liske** [comment]
Nope - OpenVPN implements most stuff in user space (encryption, decryption) and the tun/tap interfaces are just used to exchange non-encrypted packages with the kernel.

**Comment by rgrewe** [comment]
Alright!
Thank you for the answer :-)
