### ISSUE TITLE
NDB: `ip route replace …` support

### ISSUE THREAD

**Issue by mawiegand** [svinota/pyroute2#744]
Is there a way to replace a route with the `NDB` module like it can be done via `ip route replace …` with `iproute2`?
I know there is already support in the `IPRoute` module (see #111), but how can this be done with `NDB`?

Thanks!

**Comment by mawiegand** [comment]
Does anyone knew if there is a way to replace a route or if it is planned to support this operation in near feature?

@svinota maybe you can help me out here?

At least a short answer if nothing like that is planned would be great, so I could implement a workaround in my software.

Thanks!

**Comment by svinota** [comment]
Sorry for such long delay.

Technically, setting attributes on an existing route & committing the change will run `IPRoute.route('set', …)`, which means `NLM_F_REQUEST | NLM_F_ACK | NLM_F_REPLACE | NLM_F_CREATE`, and this should work exactly as `ip route replace …`

**Comment by mawiegand** [comment]
Thanks for your response. I tried to create a "new" route via pyroute which couldn't be created since it already existed.
It was probably related to a running `dhclient` process which created the same route dynamically.
After changing the `dhclient.conf` to ignore obtained routes everything worked as expected.
