### ISSUE TITLE
nftables using inet table show no chains or rules

### ISSUE THREAD

**Issue by cooperlees** [svinota/pyroute2#747]
I think the pyroute2 nftables API needs added way to get family tables, chains etc. - e.g. `inet`.
- Config using inet: https://pastebin.com/DRHgjreP

Sample code tried:
```python
from pyroute2.iproute import IPRoute
from pyroute2.nftables.main import NFTable

def test_nftables() -> None:
        nft = NFTables()
        tables = nft.get_tables()
        chains = nft.get_chains()
        rules = nft.get_rules()
        with IPRoute() as ipr:
            avail_interfaces = [
                link.get_attr("IFLA_IFNAME") for link in ipr.get_links()
            ]

        print("Tables:")
        print(tables)
        print("\nChains:")
        print(chains)
        print("\nRules:")
        for rule in rules:
            print(rule, type(rule))
        print(f"Interfaces:\n{avail_interfaces}")

test_nftables()
```

Output:

```shell
Tables:
()

Chains:
()

Rules:
Interfaces:
['lo', 'ens33']
```

OS: Ubuntu 20.10 groovy
nftables version: nftables v0.9.6 (Capital Idea #2)
Kernel: 5.8.0-28-generic

Am I just missing the way to pass / request inet filter table?

**Comment by inemajo** [comment]
Hello, you can see the inet table if you initialise NFTables class like: NFTables(nfgen_family=0)

**Comment by cooperlees** [comment]
> Hello, you can see the inet table if you initialise NFTables class like: NFTables(nfgen_family=0)

Thanks! Will give it a try, knew there would have to be a way. I’m a total netlink/nftables n00b.
