### ISSUE TITLE
pyroute2 NDB module is too instrusive for non-users

### ISSUE THREAD

**Issue by ffourcot** [svinota/pyroute2#750]
Hello,

On a server with code that does not use nor import NDB, with got very strange SQL behavior. We recently updated pyroute2 version on it, and before, our ORM was writing SQL request like:

```SQL
SELECT "a_lot_of_things" FROM "my_table" WHERE "column"."ips" @> ARRAY['46.193.255.0']::inet[]; args=(['46.193.255.0'],)
```

After a fresh pyroute2 installation, it looks now like it:

```SQL
SELECT "a_lot_of_things" FROM "my_table" WHERE "column"."ips" @> '["46.193.255.0"]'::inet[]; args=(['46.193.255.0'],)
```

This is buggy, postgresql cannot understand this request. ARRAY is not given anymore. After a lot of debug (pyroute2 was not the only one library to be updated), we bisected the bug to this code in ndb module:

```python3
if psycopg2 is not None:
    psycopg2.extensions.register_adapter(list, PostgreSQLAdapter)
    psycopg2.extensions.register_adapter(dict, PostgreSQLAdapter)
```

I think that it's a bug that this kind of side effect can happens for someone not using the module directly. You could perhaps ask for explicit adaptater registration, or register it at first call?

**Comment by svinota** [comment]
Yep, you're right. Fixing.

**Comment by svinota** [comment]
Should be fixed now, please check.

Would you like a new release to be tagged asap?

**Comment by ffourcot** [comment]
Thank you!

No need for a new release on my side, we are packaging pyroute manually.
