### ISSUE TITLE
NDB: Getting interfaces from `target` other than `localhost` no longer works

### ISSUE THREAD

**Issue by mawiegand** [svinota/pyroute2#793]
If I try to get an interface which exists in a `namespace` e.g. `ns1` via
```python
ndb.interfaces[{"ifname": "eth0"}]
```
it is no longer found with the latest `pyroute2` version `0.5.18`.
With version `0.5.12` this worked without problems.

The `NDB` is created with `auto_netns=True` and the `namespace` is added to it with
```python
ndb.sources.add(netns="ns1")
```

If I add the `namespace` as `target` argument like here
```python
ndb.interfaces[{"ifname": "eth0", "target": "ns1"}]
```
everything works as expected.

Even if I could add the `target` argument when querying for interfaces,
it would be nice not having to do so. Since it makes the handling much easier.

@svinota could you have a look into it? Thanks! :)

**Comment by svinota** [comment]
The question is what will be the semantics in that case and how do we resolve name conflicts.

By default NDB looks for object in the main namespace (aka `localhost`; by itself it may be an issue if someone creates a separate network namspace named `localhost`; but that's a topic for a separate issue), and any other namespace requires explicit declaration in the spec. Assume we have a layout:
```
namespace: main
    interface: lo
    interface: eth0
namespace: ns1
    interface: lo
    interface: eth0
namespace: ns2
    interface: lo
    interface: eth0
```

In that case `{'ifname': 'eth0'}` will return the first one, and let's assume that's ok. But if we have something like that:
```
namespace: main
    interface: lo
    interface: ens0
namespace: ns1
    interface: lo
    interface: eth0
namespace: ns2
    interface: lo
    interface: eth0
```
Now which interface should be returned by the spec?

As a possible solution I can add a property that will force NDB to treat `ns1` (or any other specific namespace) as the main ns, thus not requiring explicit target declaration.

**Comment by svinota** [comment]
Oh, and I forgot -- if you register namespaces with `ndb.sources.add()`, you don't need `auto_netns`.

I'm not really sure that this feature with `auto_netns` was a good idea.

**Comment by svinota** [comment]
@mawiegand corresponding change was committed to the branch (https://github.com/svinota/pyroute2/tree/separate_packages) that will become version 0.6.0 in a week or two, https://github.com/svinota/pyroute2/commit/9d9ef557842967aec8f6594905bcff6527e9df38

It works like that:
```python
ndb.sources.add(netns='ns1')
ndb.localhost = 'ns1'
assert ndb.interfaces['eth0'] == \
    ndb.interfaces[{'ifname': 'eth0'}] == \
    ndb.interfaces[{'ifname': 'eth0', 'target': 'ns1'}]
assert ndb.interfaces['eth0']['target'] == 'ns1'
```

I can backport the change to 0.5.x, or you can try `separate_packages` branch, but the docs are not ready yet for that. The main change there is that `pyroute2` package becomes a pure virtual package that installs a bunch of `pyroute2.xxxx` packages by deps. But `make install` still works as before (requires `twine` to build packages, though).

**Comment by mawiegand** [comment]
> Oh, and I forgot -- if you register namespaces with `ndb.sources.add()`, you don't need `auto_netns`.
> 
> I'm not really sure that this feature with `auto_netns` was a good idea.

Yeah, I know. I ttried to use `auto_netns` but it did not work in every situation. Therefore I added the namespaces with `ndb.source.add()` and forgot to remove `auto_netns` and since it does not harm it stayed that way.



> @mawiegand corresponding change ([9d9ef55](https://github.com/svinota/pyroute2/commit/9d9ef557842967aec8f6594905bcff6527e9df38)) was committed to the branch (https://github.com/svinota/pyroute2/tree/separate_packages) that will become version 0.6.0 in a week or two.
> 
> It works like that:
> 
> ```python
> ndb.sources.add(netns='ns1')
> ndb.localhost = 'ns1'
> assert ndb.interfaces['eth0'] == \
>     ndb.interfaces[{'ifname': 'eth0'}] == \
>     ndb.interfaces[{'ifname': 'eth0', 'target': 'ns1'}]
> assert ndb.interfaces['eth0']['target'] == 'ns1'
> ```
> 
> I can backport the change to 0.5.x, or you can try `separate_packages` branch, but the docs are not ready yet for that. The main change there is that `pyroute2` package becomes a pure virtual package that installs a bunch of `pyroute2.xxxx` packages by deps. But `make install` still works as before (requires `twine` to build packages, though).

If I got you right this allows configuring a default target, right?
I used `ndb.interfaces[{'ifname': 'eth0'}]` before to find the interface in all added namespaces. So it would not really fit my specific usecase.

I just added the specific `namespace` as `target` to my queries to solve this. So I don't think there is a need to backport those changes. But thanks for your assistance, @svinota! :slightly_smiling_face:

**Comment by svinota** [comment]
I'm not sure if it will be useful in your usecase, but it may:

```python
>>> from pyroute2 import NDB
>>> ndb = NDB()
>>> ndb.sources.add(netns='ns1')
[running] <NetNS {'netns': b'/var/run/netns/ns1', 'target': 'ns1'}>
>>> ndb.sources.add(netns='ns2')
[running] <NetNS {'netns': b'/var/run/netns/ns2', 'target': 'ns2'}>
>>> [(x['target'], x['IFLA_IFNAME']) for x in ndb.interfaces.getmany({'ifname': 'lo'})]
[('localhost', 'lo'), ('ns1', 'lo'), ('ns2', 'lo')]
```

Method `ndb.view.getmany()` accepts a dictionary of normalized NLA names, uses them to build an SQL request and runs the request against the corresponding DB table. It returns whatever the request returns, but the names of NLA:s follow the NLA definitions in the RTNL parser, thus `IFLA_IFNAME` and so on.

Another limitation — it does not fetch info related tables, like vlan or bridge info.

But it is still useful to locate objects in the main tables, and then use usual API to retrieve the object using the fetched basic info.

Actually, it is designed for the internal NDB usage, but it's a public method and I don't plan to change it unless a request from users comes.

**Comment by mawiegand** [comment]
Thanks for your hint. But I implemented my previously mentioned solution (by using `target`) which seem to be working at least for me. Therefore closing here. But feel free to re-open if required.
