### ISSUE TITLE
Missing routes on NDB.routes.dump()

### ISSUE THREAD

**Issue by luis5tb** [svinota/pyroute2#807]
It seems some routes are missing from the routes.dump().

I have a VRF with table id 1001 associated where the existing (ipv4) routes are:
$ ip route show vrf vrf-1001
unreachable default metric 4278198272
20.0.0.0/24 via 172.24.100.225 dev br-ex
172.24.100.225 dev br-ex scope link

If using the "show table ID" instead, the local kernel scope routes are also shown:
$ ip route show table 1001
unreachable default metric 4278198272 
20.0.0.0/24 via 172.24.100.225 dev br-ex 
local 20.0.0.82 dev lo-1001 proto kernel scope host src 20.0.0.82 
172.24.100.225 dev br-ex scope link
local 172.24.100.225 dev lo-1001 proto kernel scope host src 172.24.100.225 

If we pay attention to the routes with 172.24.100.225 destination, we see the next:
(pdb) [r for r in pyroute2.NDB().routes.dump() if r.table == 1001]
[('localhost', 0, 2, 0, 0, 0, 252, 3, 0, 7, 0, '', None, None, None, None, 4278198272, None, None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
('localhost', 0, 2, 24, 0, 0, 252, 3, 0, 1, 0, '20.0.0.0', None, None, 7, '172.24.100.225', 0, None, None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
('localhost', 0, 2, 32, 0, 0, 252, 2, 254, 2, 0, '20.0.0.82', None, None, 161, None, 0, '20.0.0.82', None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
('localhost', 0, 2, 32, 0, 0, 252, 2, 254, 2, 0, '172.24.100.225', None, None, 161, None, 0, '172.24.100.225', None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None)] <---

As it can be seen, only one route for it, which corresponds to the local one (scope 254). There is no reference to the route "172.24.100.225 dev br-ex scope link".

However, if we remove the local route:
$ ip ro del local 172.24.100.225 dev lo-1001 table 1001 

Then the previous command actually shows the other route for 172.24.100.225 (with scope 253):
(pdb) sudo ip ro del local 172.24.100.225 dev lo-1001 table 1001 
[r for r in pyroute2.NDB().routes.dump() if r.table == 1001]
[('localhost', 0, 2, 0, 0, 0, 252, 3, 0, 7, 0, '', None, None, None, None, 4278198272, None, None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
('localhost', 0, 2, 24, 0, 0, 252, 3, 0, 1, 0, '20.0.0.0', None, None, 7, '172.24.100.225', 0, None, None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
('localhost', 0, 2, 32, 0, 0, 252, 2, 254, 2, 0, '20.0.0.82', None, None, 161, None, 0, '20.0.0.82', None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),
('localhost', 0, 2, 32, 0, 0, 252, 3, 253, 1, 0, '172.24.100.225', None, None, 7, None, 0, None, None, None, 1001, None, '', '', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None),  <---

**Comment by svinota** [comment]
I managed to partly (not 1-to-1) reproduce the setup, but I'm not sure if the setup is correct:

```
# ip addr show vrf vrf-1001
8729: lo-1001: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue master vrf-1001 state UNKNOWN group default qlen 1000
    link/ether f2:f1:e2:ff:52:03 brd ff:ff:ff:ff:ff:ff
    inet 172.24.100.225/24 scope global lo-1001
       valid_lft forever preferred_lft forever
8730: br-ex: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue master vrf-1001 state UNKNOWN group default qlen 1000
    link/ether 1e:e9:92:08:d0:b7 brd ff:ff:ff:ff:ff:ff
    inet 172.24.0.1/24 scope global br-ex
       valid_lft forever preferred_lft forever
    inet6 fe80::1ce9:92ff:fe08:d0b7/64 scope link 
       valid_lft forever preferred_lft forever

# ip route show vrf vrf-1001
172.24.0.0/24 dev br-ex proto kernel scope link src 172.24.0.1 
172.24.100.225 dev br-ex scope link 

# ip route show table 1001
broadcast 172.24.0.0 dev br-ex proto kernel scope link src 172.24.0.1 
172.24.0.0/24 dev br-ex proto kernel scope link src 172.24.0.1 
local 172.24.0.1 dev br-ex proto kernel scope host src 172.24.0.1 
broadcast 172.24.0.255 dev br-ex proto kernel scope link src 172.24.0.1 
172.24.100.225 dev br-ex scope link 
local 172.24.100.225 dev lo-1001 proto kernel scope host src 172.24.100.225 
```

Now running NDB:
```python
>>> ndb.routes.dump().filter(dst='172.24.100.225').select('dst', 'table', 'scope', 'oif').format('json')
[
    {
        "dst": "172.24.100.225",
        "oif": 8730,
        "scope": 253,
        "table": 1001
    },
    {
        "dst": "172.24.100.225",
        "oif": 8729,
        "scope": 254,
        "table": 1001
    }
]
```

So it looks like both are in place. Which version of pyroute2 do you use? May I ask you for a shell script to reproduce the VRF setup?

Anyways, I didn't work with VRF so close yet, so NDB definitely will miss some VRF support. I will try to fix that asap.

**Comment by luis5tb** [comment]
Setup is slightly different as br-ex is not part of the vrf-1001:
7: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether f2:ff:65:5b:82:4f brd ff:ff:ff:ff:ff:ff
    inet 192.168.222.1/32 scope global br-ex
       valid_lft forever preferred_lft forever

228: vrf-1001: <NOARP,MASTER,UP,LOWER_UP> mtu 65536 qdisc noqueue master ovs-system state UP group default qlen 1000
    link/ether a6:9c:93:b9:65:bf brd ff:ff:ff:ff:ff:ff
229: br-1001: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master vrf-1001 state UP group default qlen 1000
    link/ether 02:4b:2f:87:33:a3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f889:4cff:fe95:5351/64 scope link 
       valid_lft forever preferred_lft forever
230: vxlan-1001: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-1001 state UNKNOWN group default qlen 1000
    link/ether 02:4b:2f:87:33:a3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::4b:2fff:fe87:33a3/64 scope link 
       valid_lft forever preferred_lft forever
231: lo-1001: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue master vrf-1001 state UNKNOWN group default qlen 1000
    link/ether a2:46:99:64:12:f8 brd ff:ff:ff:ff:ff:ff
    inet 172.24.100.225/32 scope global lo-1001
       valid_lft forever preferred_lft forever

So, the idea here is that I add the IP (172.24.100.225) on lo-1001 (so that the BGP configuration we have exposes it through EVPN, note evpn if configured by using the br-1001, vxlan-1001 and vrf-1001), but then I actually want to redirect the traffic (once it reaches the server) through the br-ex device. So, I have the vrf device added as a port on br-ex (ovs bridge). And I need a rule on the vrf-1001 to send the traffic instead of to lo-1001 to br-ex device (172.24.100.225 dev br-ex scope link). And therefore I want to delete the local route added when you add an IP to a device (lo-1001 in this case, local 172.24.100.225 dev lo-1001 proto kernel scope host src 172.24.100.225).

This may be somehow related to issue #806. Problem on #806 is that I cannot delete the local route, and the problem here is that only the local route appears on NDB.

For the kernel I'm using: 4.18.0-301.1.el8.x86_64

And for pyroute2 I was using master of a few days ago. This is the last commit:
commit ff08d69 (HEAD -> master, origin/master, origin/HEAD)
Merge: e51de8a 22ac32c
Author: Peter V. Saveliev peter@svinota.eu
Date: Wed May 19 15:54:16 2021 +0200
nl80211: merge pull request #799 from matshch/wifi-region
nl80211: allow to get and set regulatory rules
Bug-Url: #799

As for the script to recreate:
# Create resources
ip link add red type vrf table 1002
ip link set red up
ip link add vxlan1002 type vxlan id 1002 dstport 4789 local 172.30.1.1 nolearning
ip link set up dev vxlan1002
ip link add name br1002 type bridge stp_state 0
ip link set up dev br1002
ip link set br1002 master red
ip link set vxlan1002 master br1002
bridge link set dev vxlan1002 neigh_suppress on
ip link add name lo1002 type dummy
ip link set lo1002 master red
ip link set lo1002 up
# Set up ovs bridge
ovs-vsctl add-br br-ex2
ip link set br-ex2 up
ip a add 192.168.222.1/32 dev br-ex2
# Configue IPs/routes
ovs-vsctl add-port br-ex2 red
ip route add 11.11.11.11/32 dev br-ex2 table 1002
ip addr add 11.11.11.11/32 dev lo1002

Which generates:
# ip route sh table 1002
11.11.11.11 dev br-ex2 scope link 
local 11.11.11.11 dev lo1002 proto kernel scope host src 11.11.11.11

**Comment by luis5tb** [comment]
Seems it is about the ordering... If I first add the ip to lo1002 and then add the route pointing to the br-ex2, then the route gets updated/replaced. But if I do it the other way around (first the ip route, and then add the ip to lo1002), then I end up in the situation where both routes are there, and NDB cannot see the one pointing to br-ex2, and neither can remove the local one pointing to lo1002

**Comment by svinota** [comment]
Thanks, trying to reproduce

**Comment by luis5tb** [comment]
Maybe I was not using the pyroute2 version I thought... testing now with tag 0.6.4 and seems to work fine
