### ISSUE TITLE
Best way to install "from source"

### ISSUE THREAD

**Issue by ffourcot** [svinota/pyroute2#810]
Hello,

Since new packing layout, it looks harder than before to install pyroute2"from source". Previously, a simple git clone and symlink/copy (or PYTHONPATH update) for "pyroute2/pyroute2" was enough.

Now, it looks a little bit harder. Do you have any documentation on how to install the project without using pip?

Thanks

**Comment by svinota** [comment]
Build deps include twine and setuptools. Then simple `make dist` or `make install` should work, just run it within a virtualenv.

If it's an overkill — e.g. for an embedded environment — I can try to implement a separate make target that would prepare a simple tarball with a required directory structure.
