### ISSUE TITLE
Fixing old code - replacement for 'import IW' - 'iw.scan'

### ISSUE THREAD

**Issue by SecurityJon** [svinota/pyroute2#816]
Hi there!

Hopefully a quick solution, I'm fixing up some legacy code from the https://github.com/SecurityJon/audit-radius project and this utilises pyroute2. 

The code imports:

```
from pyroute2 import IW
```

And this throws:

```
ImportError: cannot import name 'IW' from 'pyroute2' (/usr/local/lib/python3.9/dist-packages/pyroute2/__init__.py)
```

It's using this for wifi scanning. 

I can't easily see in the docs (I'm not a python dev) the correct way of fixing this - was this functionality removed or accessed in a different way?

**Comment by SecurityJon** [comment]
Quick update - I've found `iwutils` which appears to import fine, and then I call this with `iwutils.IW()`.

Unfortunately the code still won't 'do' anything so I can't test if this was correct, but does it look right?

**Comment by SecurityJon** [comment]
In the same vein - another import appears to be missing now
```
import RawIPRoute
with RawIPRoute() as rawip:
```

Is there an equivalent?

**Comment by ralonsoh** [comment]
Hi @SecurityJon:

Import the module, not the class or the variable. For example, in the last example:
from pyroute2 import iproute
with iproute.RawIPRoute() as rawip:
    ...

Regards.

**Comment by svinota** [comment]
The plan was that it should work without any code change, so I'm to fix this. Will be fixed asap.

Still some import errors are possible (not all the modules are covered with CI), and thanks for reporting it.

**Comment by svinota** [comment]
Fixed in the master branch.
