### ISSUE TITLE
`vlan_id` key missing from NDB interfaces RecordSet

### ISSUE THREAD

**Issue by Etzeitet** [svinota/pyroute2#819]
I found an inconsistency today with the fields available in an NDB `Interface` instance vs a `Record`. Specifically, when getting interfaces via the `dump()` and `filter()` methods, the VLAN ID for a VLAN interface is not available:

**Getting a VLAN interface object and showing the `vlan_id`:**
``` python
>>> from pyroute2 import NDB
>>> ndb = NDB()
>>> ndb.interfaces["vlan.100"]["vlan_id"]
100
>>>
>>> ndb.interfaces["vlan.200"]["vlan_id"]
200
```

**Getting the VLAN interfaces via `dump()` and `filter()` doesn't provide the `vlan_id`:**
``` python
>>> for i in ndb.interfaces.dump().filter(kind="vlan"):
...     print(f"{i['ifname']} has VLAN: {i['vlan_id']}")
...
vlan.100 has VLAN: None
vlan.200 has VLAN: None
>>>
```

As you can see, the `vlan_id` key doesn't even exist:
``` python
>>> ndb.interfaces.dump().filter(kind="vlan")[0]._names
('target', 'tflags', 'family', 'ifi_type', 'index', 'flags', 'change', 'address', 'broadcast', 'ifname', 'mtu', 'link', 'qdisc', 'master', 'txqlen', 'linkmode', 'net_ns_pid', 'ifalias', 'num_vf', 'group', 'ext_mask', 'promiscuity', 'num_tx_queues', 'num_rx_queues', 'carrier', 'carrier_changes', 'link_netnsid', 'phys_port_name', 'proto_down', 'gso_max_segs', 'gso_max_size', 'if_netnsid', 'carrier_up_count', 'carrier_down_count', 'new_ifindex', 'min_mtu', 'max_mtu', 'alt_ifname', 'state', 'kind', 'slave_kind')
>>>
```

I did wonder if the `vlan_id` field had a different name in a Record, I don't see anything that looks like a VLAN ID.

Is there a reason for this difference, or have I overlooked something?

**Comment by svinota** [comment]
The `dump()` command returns only `ifinfmsg` structures for interfaces, while the vlan info is received as a specific structure and stored in a specific table — `ifinfo_vlan`. As well as specific attributes of bridge, bond etc. intefaces, you can run `ndb.schema.export()` to see all the database content, just create some bridges etc. to see what happens.

Like that:
```
$ ip ad
…
86: test01: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether a2:34:d1:d4:23:b5 brd ff:ff:ff:ff:ff:ff
87: test01.100@test01: <BROADCAST,NOARP,M-DOWN> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether a2:34:d1:d4:23:b5 brd ff:ff:ff:ff:ff:ff
88: br0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ca:ab:c5:f3:37:65 brd ff:ff:ff:ff:ff:ff
```
And the schema:
```
>>> ndb.schema.export()

table interfaces
…
localhost 0 0 1 86 130 0 a2:34:d1:d4:23:b5 ff:ff:ff:ff:ff:ff test01 1500 None noop None 1000 0 None None None 0 None 0 1 1 1 0 None None 0 65535 65536 None 0 0 None 0 0 None down dummy None
localhost 0 0 1 87 130 4294967295 a2:34:d1:d4:23:b5 ff:ff:ff:ff:ff:ff test01.100 1500 86 noop None 1000 0 None None None 0 None 0 1 1 1 0 None None 0 65535 65536 None 0 0 None 0 65535 None down vlan None
localhost 0 0 1 88 4098 0 ca:ab:c5:f3:37:65 ff:ff:ff:ff:ff:ff br0 1500 None noop None 1000 0 None None None 0 None 0 1 1 0 1 None None 0 65535 65536 None 0 1 None 68 65535 None down bridge None


table af_bridge_ifs

table af_bridge_vlans

table p2p

table ifinfo_bridge
localhost 0 1500 200 2000 30000 0 32768 0 33024 0 0 0 0 0 0 0 0 0 01:80:c2:00:00:00 1 1 0 0 16 4096 2 2 100 26000 25500 12500 1000 3125 0 0 0 1 None 0 0 2 1 88


table ifinfo_bond

table ifinfo_vlan
localhost 0 100 33024 87  ← here is the vlan info
```

We obviously can not include all the specific attributes in the dump, thus `dump()` returns only the least common denominator for all the interfaces.

But I'm open to any proposals how to implement this in a reasonable way.

**Comment by svinota** [comment]
As a (temporary) workaround you can use something like that:

```python
>>> for i in ndb.interfaces:
...     ndb.interfaces[i].show()
```

**Comment by Etzeitet** [comment]
That makes sense. I can't really offer you a reasonable way of implementing getting interface specifics into `dump()`. I managed to work around the issue in my specific use case by using the `ifname`. The convention we use to name VLAN interfaces means it's pretty much guaranteed to be in the name, i.e. `vlan.100`, `vlan.222`, etc.

I'm happy for this issue to be closed. Thanks for your time!

**Comment by svinota** [comment]
Thanks!
