### ISSUE TITLE
Ipset detecting wrong max revision on Ubuntu HWE kernel.

### ISSUE THREAD

**Issue by toonvd** [svinota/pyroute2#830]
After upgrading to kernel `5.11.0-25-generic` in Ubuntu 20.04, the following error occured when listing my usual sets:
`ipset v7.5: Kernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.`.

When investigating closer, Pyroute2 seemed to detect the wrong maximum revision:
```
cat test.py
from pyroute2.ipset import IPSet

with IPSet() as ipset_socket:
    print(ipset_socket.get_supported_revisions("hash:net"))
    ipset_socket.close()
```

```
python3 test.py
(0, 7)
```

Doing a man of IPset the following was returned:
```
hash:net		6	skbinfo support
```

For now, I have passed a fixed revision in the constructor to bypass this:

```
with IPSet(attr_revision=6) as ipset_socket:
```

**Comment by ffourcot** [comment]
Hello,

pyroute2 detects the maximum revision supported *by the kernel*. We don't have any way to detect supported versions for others userland tools, like ipset binary.

In my opinion, you have several choices:

- Upgrade ipset binary of your system. To be consistent with your kernel upgrade, and be able to use recent kernel features. That is sad that Ubuntu distribution does not provide ipset userland update when they are upgrading kernel
- Force revision version, like you did. For the best of my knowledge, ipset binary command does not provide option to export supported module revision (that could be a good ipset upstream patch) so you have to hardcode it for each ipset types that you want to use
- Use LTS kernel closer to your userland tools.

Between revision 6 and 7 for hash:net type, you are just missing bucketsize configuration and initval hash parameter in listing. See this commit for reference : https://github.com/svinota/pyroute2/commit/a7167e6ef45496fc122d2c324e9dcdbe67204e34

**Comment by toonvd** [comment]
Hi

Thanks for the feedback. I was looking for ways to export it myself and didn't find anything besides parsing the help command. An upstream patch to Ipset might indeed be the only way to do it cleanly since the help command already has the data anyways. Closing and hard coding it for now.
