### ISSUE TITLE
Question: network interface bond set option arp_ip_target

### ISSUE THREAD

**Issue by leeseungbin** [svinota/pyroute2#834]
When the network interface bond mode is 'active-backup'
I want to know how to do the same operation as 'ip link set bond1 type bond mode 1 arp_ip_target 1.1.1.1 1.1.1.2' command.

Python\Python38\site-packages\pr2modules\netlink\rtnl\ifinfmsg\plugins\bond.py file have the class below.

      from pr2modules.netlink import nla

      class bond(nla):
          prefix = 'IFLA_'
          nla_map = (('IFLA_BOND_UNSPEC', 'none'),
                     ('IFLA_BOND_MODE', 'uint8'),
                     ('IFLA_BOND_ACTIVE_SLAVE', 'uint32'),
                     ('IFLA_BOND_MIIMON', 'uint32'),
                     ('IFLA_BOND_UPDELAY', 'uint32'),
                   ('IFLA_BOND_DOWNDELAY', 'uint32'),
                   ('IFLA_BOND_USE_CARRIER', 'uint8'),
                   ('IFLA_BOND_ARP_INTERVAL', 'uint32'),
                   ('IFLA_BOND_ARP_IP_TARGET', 'arp_ip_target'),
                   ('IFLA_BOND_ARP_VALIDATE', 'uint32'),
                   ('IFLA_BOND_ARP_ALL_TARGETS', 'uint32'),
                   ('IFLA_BOND_PRIMARY', 'uint32'),
                   ('IFLA_BOND_PRIMARY_RESELECT', 'uint8'),
                   ('IFLA_BOND_FAIL_OVER_MAC', 'uint8'),
                   ('IFLA_BOND_XMIT_HASH_POLICY', 'uint8'),
                   ('IFLA_BOND_RESEND_IGMP', 'uint32'),
                   ('IFLA_BOND_NUM_PEER_NOTIF', 'uint8'),
                   ('IFLA_BOND_ALL_SLAVES_ACTIVE', 'uint8'),
                   ('IFLA_BOND_MIN_LINKS', 'uint32'),
                   ('IFLA_BOND_LP_INTERVAL', 'uint32'),
                   ('IFLA_BOND_PACKETS_PER_SLAVE', 'uint32'),
                   ('IFLA_BOND_AD_LACP_RATE', 'uint8'),
                   ('IFLA_BOND_AD_SELECT', 'uint8'),
                   ('IFLA_BOND_AD_INFO', 'ad_info'),
                   ('IFLA_BOND_AD_ACTOR_SYS_PRIO', 'uint16'),
                   ('IFLA_BOND_AD_USER_PORT_KEY', 'uint16'),
                   ('IFLA_BOND_AD_ACTOR_SYSTEM', 'hex'),
                   ('IFLA_BOND_TLB_DYNAMIC_LB', 'uint8'))
    
        class ad_info(nla):
            nla_map = (('IFLA_BOND_AD_INFO_UNSPEC', 'none'),
                       ('IFLA_BOND_AD_INFO_AGGREGATOR', 'uint16'),
                       ('IFLA_BOND_AD_INFO_NUM_PORTS', 'uint16'),
                       ('IFLA_BOND_AD_INFO_ACTOR_KEY', 'uint16'),
                       ('IFLA_BOND_AD_INFO_PARTNER_KEY', 'uint16'),
                       ('IFLA_BOND_AD_INFO_PARTNER_MAC', 'l2addr'))
    
        class arp_ip_target(nla):
            fields = (('targets', '16I'), )

It can be inferred that arp_ip_target is a dictionary type and has targets as key values, and targets value is a list containing 16 unsinged_interger elements.

If I change the ip to an integer type and put a value in the list of targets, I thought that the ip value would be put in arp_ip_target, but it failed!!. (ip to integer site: http://www.aboutmyip.com/AboutMyXApp/IP2Integer.jsp?ipAddress=1.1.1.1)

Interface configuration
ip link add bond8 type bond 
ip link set bond8 down
-----------------------------------------------------------------------------------------------------------
ip link set bond1 type bond arp_ip_target 1.1.1.1 1.1.1.2 -> set this cmd of pyroute2.link

my code
        from pyroute2 import IPRoute, NDB, IPDB
         # bond8 index 17
         with IPRoute() as ipr:
             ipr.link('set', index=17, kind='bond', IFLA_BOND_ARP_IP_TARGET={'targets': [16843009, 16843010, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]})

**Comment by svinota** [comment]
fixed, see also https://github.com/svinota/pyroute2/issues/873
