### ISSUE TITLE
Docs mention only 255 route tables, but it can be u32 ?

### ISSUE THREAD

**Issue by jamesmcm** [svinota/pyroute2#844]
Hi,

I noticed [the docs mention](https://github.com/svinota/pyroute2/blob/master/pyroute2.core/pr2modules/iproute/linux.py#L371):

>  There are 255 routing classes (tables)

However, the `ip route` manpage states:

> Route tables: Linux-2.x can pack routes into several routing tables identified by a number in the range from 1 to 2^32-1 or by name from the file /etc/iproute2/rt_tables By default all normal routes are inserted into the main table (ID 254) and the kernel only uses this table when calculating routes. Values (0, 253, 254, and 255) are reserved for built-in use.

And it seems pyroute2 actually uses a u32:

https://github.com/svinota/pyroute2/blob/afeae11f57102b87d20486bae5335331361d2131/pyroute2.core/pr2modules/netlink/rtnl/req.py#L265-L266

As does the relevant iproute2 code:

https://github.com/shemminger/iproute2/blob/main/ip/iproute.c#L1407

Is this just a case of stale docs, or do they refer to different things?

**Comment by svinota** [comment]
Yep, that's a doc's issue. To be fixed asap.
