### ISSUE TITLE
get_timeout seemingly not having an effect

### ISSUE THREAD

**Issue by flan** [svinota/pyroute2#867]
I may be doing something wrong, but in my code, I'm interacting with *pyroute2* like this (sample is copy/pastable and sufficient to reproduce):

```python
import pyroute2
with pyroute2.IW() as iw:
    iw.get_timeout = 5 #optional; the default is 30
    iw.bind()
    iw.add_membership('mlme')
    while True:
        print("starting loop")
        for event in iw.get():
            pass
```

But it never seems to trigger a timeout, evidenced by the `print` statement only firing once.

I suspect this is due to https://github.com/svinota/pyroute2/blob/e24994ffba4f81660142bfcf8193c34207a28a4b/pyroute2.core/pr2modules/netlink/nlsocket.py#L773-L774 checking `msg_seq` before evaluating the timeout condition itself and I'm not sure why having a non-zero value matters.

**Comment by svinota** [comment]
The `get_timeout`, as well as its checking, is a part of the library internals (todo: rename it not to be public)

Generally speaking, you can consider `get()` as blocking.

As an alternative, you can monitor `iw._sock` with `poll/select` and run `get()` only if there is any data.
