### ISSUE TITLE
taskstats:ac_comm decode error

### ISSUE THREAD

**Issue by hanyingzhong** [svinota/pyroute2#868]
[root@localhost python-test]# 
[root@localhost python-test]# cat taskstats.py 
import os
from pyroute2 import TaskStats

ts = TaskStats()
ts.bind()
pid = os.getpid()
statss = ts.get_pid_stat(pid)
print(statss)

result:
[root@localhost python-test]# python3.6 taskstats.py 
decoding TASKSTATS_TYPE_STATS
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pr2modules/netlink/__init__.py", line 1507, in try_to_decode
    cell.decode()
  File "/usr/local/lib/python3.6/site-packages/pr2modules/netlink/taskstats/__init__.py", line 83, in decode
    self['ac_comm'] = self['ac_comm'][:self['ac_comm'].find('\0')]
TypeError: a bytes-like object is required, not 'str'

({'cmd': 2, 'version': 1, 'reserved': 0, 'attrs': [('TASKSTATS_TYPE_AGGR_PID', {'attrs': [('TASKSTATS_TYPE_PID', 4394), ('TASKSTATS_TYPE_STATS', {'version': 8, 'ac_exitcode': 0, 'ac_flag': 2, 'ac_nice': 0, 'cpu_count': 31, 'cpu_delay_total': 7362326, 'blkio_count': 0, 'blkio_delay_total': 0, 'swapin_count': 0, 'swapin_delay_total': 0, 'cpu_run_real_total': 285000000, 'cpu_run_virtual_total': 280865132, 'ac_comm': b'python3.6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'ac_sched': 0, '__ac_pad': 0, '__implicit_pad': 0, 'ac_uid': 0, 'ac_gid': 0, 'ac_pid': 4394, 'ac_ppid': 5927, 'ac_btime': 1640414809, 'ac_etime': 290813, 'ac_utime': 249000, 'ac_stime': 36000, 'ac_minflt': 9574, 'ac_majflt': 0, 'coremem': 3343929, 'virtmem': 49116839, 'hiwater_rss': 23812, 'hiwater_vm': 243848, 'read_char': 3569664, 'write_char': 2048, 'read_syscalls': 0, 'write_syscalls': 0, 'read_bytes': 0, 'write_bytes': 4096, 'cancelled_write_bytes': 0, 'nvcsw': 6, 'nivcsw': 24, 'ac_utimescaled': 249000, 'ac_stimescaled': 36000, 'cpu_scaled_run_real_total': 285000000})]})], 'header': {'length': 364, 'type': 26, 'flags': 0, 'sequence_number': 255, 'pid': 4394, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}},)

modification:
self['ac_comm'] = self['ac_comm'][:self['ac_comm'].find('\0')]===>
self['ac_comm'] = self['ac_comm'][:self['ac_comm'].decode().find('\0')]

**Comment by svinota** [comment]
Fixed, thanks
