### ISSUE TITLE
Is it default that NDB starts several additional threads?

### ISSUE THREAD

**Issue by gtfaiwxm** [svinota/pyroute2#879]
Hi, when I use the NDB, I find that the NDB starts several additional threads. Is it default that NDB starts several additional threads? The version of pyroute2 is 0.5.18.

**Comment by svinota** [comment]
Yes it is. NDB provides a state DB being updated in the background, and it runs threads for that purpose.

If you don't want to use a thread-based app, you might prefer IPRoute as it has no threads by default and provides a file descriptor that may be used to integrate it in an async event loop.
