### ISSUE TITLE
Supports python3 ?

### ISSUE THREAD

**Issue by takaomag** [svinota/pyroute2#88]
Hi,

Does pyroute2 support python3 ?
As far as I tried, it seems pyroute2 works on Python3.4. But,

* [pyroute2 pypi page](https://pypi.python.org/pypi/pyroute2/)
No classifiers about supported python versions.

* [Requirements section in docs](http://docs.pyroute2.org/general.html#requires)
Says only "Python >= 2.6".

I think, developers who use python3 may avoid using a library which does not announce python3 support explicitly.

If pyroute2 does support python3, **classifiers** in setup.py should have more lines like,
```
classifiers = [
    ...
    "Programming Language :: Python :: 2.6",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    ...
]
```
and also requirements section in docs.

Even if does not support python3, it is worth announcing only python 2 support lines like,
```
classifiers = [
    ...
    "Programming Language :: Python :: 2.6",
    "Programming Language :: Python :: 2.7",
    ...
]
```

This is just what I felt when I searched a python library to configure Linux network settings, and just a trivial suggestion.

**Comment by svinota** [comment]
Closing as fixed.
