### ISSUE TITLE
interrupted dump causes NDB startup to stall

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#883]
Related: https://github.com/svinota/pyroute2/issues/874

Starting NDB under high loads or with rapidly changing network settings like add/removal large amounts interfaces and addresses may cause NDB startup stalled.

Source restart seems to be broken and needs a fix.

**Comment by luis5tb** [comment]
@svinota is there any chance of backporting this to 0.6.6 (instead of just up to 0.6.8)? Asking because we are hitting this in openstack wallaby version where the upper constraint limit pyroute2 to 0.6.6

**Comment by luis5tb** [comment]
nevermind, that would be indeed a new tag anyway, so not solving the issues, sorry for the noise
