### ISSUE TITLE
Custom ifinfmsg plugin stopped working with version 0.6

### ISSUE THREAD

**Issue by MJDickensheets** [svinota/pyroute2#886]
We have been using a custom plugin module and adding it to the ifinfmsg handler via the following procedure:
```
from pyroute2.netlink.rtnl import ifinfmsg
ifinfmsg.ifinfbase.ifinfo.data_map.update(
    ifinfmsg.load_plugins_by_path(_plugins)
)
```
An interface with our custom type can then be added:
```
ipr = IPRoute()
ipr.link("add", kind="custom-kind", msgfield1="data")
```
As of version 0.6, the `link("add")` results in `pr2modules.netlink.exceptions.NetlinkError: (22, 'Invalid argument')`. Some investigation revealed that the `ifinfmsg` instance visible to the `IPRoute` object did not have its `ifinfo.data_map` updated as we would have expected.

As a side note, it would also be nice to have a proper API with which to load plugins, particularly dynamically and not just at import time.

**Comment by svinota** [comment]
Got it, working on the issue.

**Comment by svinota** [comment]
@MJDickensheets pls review the commit: https://github.com/svinota/pyroute2/commit/7dd1d553a92be967b373e007a59a15b78993a316

it is also possible to override existing kinds like to make your own bridge, bond etc. implementation

**Comment by MJDickensheets** [comment]
Looks like there may be a left-over print statement, but otherwise I think this will do very nicely for our purposes. Thank you for the quick work!

**Comment by svinota** [comment]
Please reopen the ticket if there will be issues with the functionality, I'm to fix it asap.

**Comment by MJDickensheets** [comment]
I have tested the fix/feature from my end, everything appears to be working as expected. Would it be possible to schedule a tagged release in the near term?

**Comment by svinota** [comment]
0.6.8 is to be tagged on Saturday.
