### ISSUE TITLE
`exception <(22, 'Invalid argument')> in source localhost` when creating interface

### ISSUE THREAD

**Issue by sirkrypt0** [svinota/pyroute2#890]
Hi,

since version `0.6.8` when creating an interface, I sometimes get the following log output:

```log
2022-03-28 13:43:13,526 WARNING [pr2modules.ndb.main] unsupported event ignored: <class 'pr2modules.netlink.nlmsg'>
2022-03-28 13:43:13,526    ERROR pyroute2.ndb.140652981319136.main: exception <(22, 'Invalid argument')> in source localhost
2022-03-28 13:43:13,526 ERROR [pyroute2.ndb.140652981319136.main] exception <(22, 'Invalid argument')> in source localhost
```

While the interface seems to be created correctly, I'm wondering whether this behavior is desired or rather some bug.

Repeatedly run the following script until you get the error message, which on my machine takes on average no more than 10 runs.

```python
import logging
import pyroute2

def main():
    IFACE = 'test-br'
    logging.basicConfig(format='%(asctime)s %(levelname)s [%(name)s] %(message)s', level='DEBUG')

    ndb = pyroute2.NDB(log='on')
    interface = ndb.interfaces.create(ifname=IFACE, kind='bridge')
    interface.set('state', 'up')
    interface.commit()

    input('Press any key to tear down')

    interface.set('state', 'down')
    interface.commit()
    with pyroute2.IPRoute() as ipr:
        ipr.link('delete', ifname=IFACE)
    ndb.close()

if __name__ == '__main__':
    main()
```

Tested this on the `Ubuntu 5.13.0-37-generic` and `5.15.28-1-MANJARO` kernels.

**Comment by svinota** [comment]
This is a false positive on an (almost) regular RTNL message. Ok, not so regular, a bit more complicated, but anyways:

1. the interface should be created and set up
2. this RTNL message interpretation by itself is a bug and will be fixed

**Comment by svinota** [comment]
The issue code located, the fix will be ready this week.

**Comment by svinota** [comment]
Pls check, should be fixed now.

The important regression was that this error triggered full DB reload, which is expensive if there is a lot of network objects like routes or addresses.

Thanks for the report, it is an important fix.

**Comment by sirkrypt0** [comment]
Just tested it and can confirm that the error message does not appear anymore. Thanks!

**Comment by sirkrypt0** [comment]
Hi,

thanks again for fixing this! As I'd like to make use of this fix and the other new features you implemented, a new release would be awesome :) Or, is there a release that includes this fix here already?

**Comment by svinota** [comment]
Thanks for heads-up! The next release including this fix will be available this weekend.

**Comment by svinota** [comment]
@sirkrypt0 0.6.10 has been tagged
