### ISSUE TITLE
Regression on altname management

### ISSUE THREAD

**Issue by ffourcot** [svinota/pyroute2#903]
Sorry for this second regression found. I will have a look to migrate more nosetests to pytest and add some coverage.

But currently, ```IPLinkRequest``` is mangling ```altname``` argument. So this block code is actually dead code:

```python
          if 'altname' in request:
              altname = request.pop("altname")
              if msg_type in (RTM_NEWLINKPROP, RTM_DELLINKPROP):
                  if not isinstance(altname, (list, tuple, set)):
                      altname = [altname]
  
                  request["IFLA_PROP_LIST"] = {
                      "attrs": [
                          ("IFLA_ALT_IFNAME", alt_ifname)
                          for alt_ifname in altname
                      ]
                  }
              else:
                  request["IFLA_ALT_IFNAME"] = altname
```

This is a little bit related to #901, since to move this code in req module we will need to read ```msg_type``` in IPLinkRequest, and it looks currently not available.

This issue should be easy to reproduce with ```test_link_altname```, currently not migrated to pytest

**Comment by svinota** [comment]
I'm sorry. Trying to refactor the code and moving tests from nose to pytest at the same time, thus regressions.

Hope that none will sneak into the next release.

**Comment by svinota** [comment]
Should be fixed now.

**Comment by ffourcot** [comment]
@svinota thank you!

I will migrate ipset/wiset to pytest. But if you need help to more modules, do not hesitate to ask for help, we can try to help you.
