### ISSUE TITLE
NDB warning: unsupported event ignored

### ISSUE THREAD

**Issue by qingbo** [svinota/pyroute2#906]
Hi,

I was using IPDB to bring up a WireGuard interface but as it's deprecated, I'm trying to use NDB instead. It works but there's a warning which is a bit worrying:

```
unsupported event ignored: <class 'pr2modules.netlink.nlmsg'>
```

This short program can reproduce it on a Ubuntu 20.04 virtual machine:

```
from pyroute2 import NDB

ndb = NDB()
interface = ndb.interfaces.create(kind="wireguard", ifname="wg0")
interface.set("state", "up")
interface.add_ip("10.0.0.1/24")
print("before commit")
interface.commit()
print("after commit")
```

I also modified one line to replace `type` with `str`: https://github.com/svinota/pyroute2/blob/0b5118947de02c97aec043c23e3a8e7a8f4b0e2b/pyroute2.ndb/pr2modules/ndb/main.py#L1144

The output is like:

```
before commit
unsupported event ignored: {'header': {'length': 36, 'type': 2, 'flags': 256, 'sequence_number': 265, 'pid': 2862686842, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'NLMSG_ERROR'}
unsupported event ignored: {'header': {'length': 36, 'type': 2, 'flags': 256, 'sequence_number': 264, 'pid': 4282968587, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'NLMSG_ERROR'}
after commit
```

Sometimes there are 2 warnings, sometimes only one, and sometimes there's none.

Is it an issue? Pyroute version is 0.6.9.

**Comment by svinota** [comment]
No, it's not an issue in terms that it doesn't affect the functionality. But it spams the log, so I will try to fix it.
