### ISSUE TITLE
How to remove interfaces from bridge?

### ISSUE THREAD

**Issue by woosonchan** [svinota/pyroute2#909]
I attached an interface `eth0` into the bridge `br0` through this code:
```
ip.link("set",
        index=ip.link_lookup(ifname="eth0")[0],
        master=ip.link_lookup(ifname="br0")[0])
```

But how can I remove `eth0` from `br0` after that?
We have `brctl delif ...` operation in command `brctl`, but I found no information about it in pyroute2. @svinota

**Comment by svinota** [comment]
Thanks for the reminder, I'm to update the docs.

Here we go:
```python
ipr.link("set",
         index=ipr.link_lookup(ifname="eth0"),  # as of now, you can drop this «[0]»
         master=0)  # setting master to 0 removes eth0 from a bridge
```

**Comment by svinota** [comment]
Or using ndb:
```python
(
    ndb.interfaces["br0"]
    .del_port("eth0")
    .commit()
)
```
The difference from `IPRoute` is that `NDB` will wait on `commit()` until the changes will be actually applied, while `IPRoute.link()` only triggers the change in the kernel, and returns immediately.

**Comment by woosonchan** [comment]
Got it, thanks Peter !
