### ISSUE TITLE
Empty bridge.ports using NDB

### ISSUE THREAD

**Issue by carloslockward** [svinota/pyroute2#912]
I noticed that calling `ndb.interfaces["test-bridge"].ports` returns an empty dict.

## Steps to reproduce

1. Create a bridge with ndb: `ndb.interfaces.create(ifname="test-bridge", kind="bridge").add_port("enp1s0").add_port("wlan0").set("state", "up").commit()`
2. Try to retrieve the ports: `ndb.interfaces["test-bridge"].ports`

## Notes

I also tried getting the ports using IPRoute and had similar results.

`ip.brport("show", index=ip.link_lookup(ifname="test-bridge")[0])` returns an empty tuple.

**Comment by svinota** [comment]
**NDB**

`bridge.ports` is a view with an ordinary NDB view API:
```python
(
    ndb.interfaces["test-bridge"]
    .ports
    .summary()
    .select("index", "ifname")
    .format("json")
)
```
TODO: update the docs to reflect it

**IPRoute**
```python
with IPRoute() as ipr:
    ipr.link("dump", master=ipr.link_lookup(ifname="br0")[0])
```

**NB**: Pls keep in mind that bridge on wlan & eth may work not as expected

**Comment by carloslockward** [comment]
Thanks for the clarification. Works like a charm!

**Comment by svinota** [comment]
This commit fixes repr on views: https://github.com/svinota/pyroute2/commit/e283cba7c7f9ab2582ceb3c5206d03454dd9a52c

Thus closing the ticket.
