### ISSUE TITLE
Conntrack dump_entries filters incorrect with mark

### ISSUE THREAD

**Issue by ohashemzadeh** [svinota/pyroute2#916]
using pyroute2==0.6.9

```python3
>from pr2modules.conntrack import Conntrack
>conntrack = Conntrack()
>sample_mark=9999
>entries = list(conntrack.dump_entries(mark=sample_mark))

>len(entries)
10

>[entry.mark for entry in entries]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

`dump_entries` function does not filter entries by mark correctly.

**Comment by svinota** [comment]
Thanks, to be investigated today.

**Comment by svinota** [comment]
So far can not reproduce:

```python
>>> ct.entry('set',
    mark=5,
    tuple_orig=NFCTAttrTuple(
        saddr='172.17.0.2',
        daddr='192.168.100.10',
        sport=47042,
        dport=80,
        proto=IPPROTO_TCP,
        family=AF_INET))
>>> [x.mark for x in ct.dump_entries(mark=5)]
[5]
```
```bash
$ sudo conntrack -L | grep 192.168.100.10
tcp      6 431946 ESTABLISHED \
    src=172.17.0.2 dst=192.168.100.10 sport=47042 dport=80 \
    src=192.168.100.10 dst=172.16.254.206 sport=80 dport=47042 \
    [ASSURED] mark=5 secctx=system_u:object_r:unlabeled_t:s0 use=1
```

Probably it would be helpful to see the original messages, not only the mark field, and see corresponding conntrack entries from the shell command line. And the kernel and python versions, just in case.

And please check if the `mark_mask` helps, on some kernels there may be issues with the kernel side record filtering.

**Comment by ohashemzadeh** [comment]
I am using:

> Python 3.8.10
> Linux version 5.4.0-113-generic (buildd@lcy02-amd64-067) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1))
> pyroute2==0.6.9

**Comment by svinota** [comment]
Ok, got it. Checking on Ubuntu 20.04 LTS

**Comment by svinota** [comment]
The fix is in the master and will be available in the nearest release ready on Monday.
