### ISSUE TITLE
Fix code scanning alert - Binding a socket to all network interfaces

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#919]
Tracking issue for:
- [ ] https://github.com/svinota/pyroute2/security/code-scanning/1

Change to explicit interface binding OR deprecate own messaging in favor of zeromq?

**Comment by crosser** [comment]
I, for one, am always in favour of using unix domain sockets when the parties are guaranteed to be on the same host...

**Comment by svinota** [comment]
A good point.
