### ISSUE TITLE
Setting per-route MTU

### ISSUE THREAD

**Issue by takaomag** [svinota/pyroute2#92]
Hi,

As described as [Circumventing Path MTU Discovery issues with per route MTU settings](http://lartc.org/howto/lartc.cookbook.mtu-discovery.html), I want to set per-route MTU. For example,

````
special_mtu = 4000

with IPDB() as ipdb:  # Or with IPDB(nl=some_netns_name) as ipdb:
    ipdb.routes.add({
        'dst': 'fdff:ffff:ffff:ffff::/64',
        'RTA_OIF': ipdb.routes['default']['oif'],
        '????': special_mtu,
    }).commit()
````

Is there any way to do it ?

**Comment by svinota** [comment]
Good question. Investigating.

**Comment by svinota** [comment]
Low-level will be done today. Expect IPDB stuff tomorrow afternoon.

**Comment by takaomag** [comment]
Thank you for the quick reply !

**Comment by svinota** [comment]
As a beta-version of the support, it is done and tested, and will be packed with 0.3.4 this weekend:

```
ip = IPDB()
ip.routes.add(dst='172.16.1.0/24',
              oif=4,
              metrics={'attrs': [['RTAX_MTU', 1280],
                                 ['RTAX_ADVMSS', 536]]}).commit()
```

You can specify any set of RTAX attributes in metrics. The full list: https://github.com/svinota/pyroute2/blob/master/pyroute2/netlink/rtnl/rtmsg.py#L54

E.g.:

```
ip.routes.add(dst='172.16.1.0/24',
              oif=4,
              metrics={'attrs': [['RTAX_HOPLIMIT', 2]]}.commit()
```

This particular syntax will be supported from now on, but there will be more usable form implemented with 0.3.5 as well.

**Comment by svinota** [comment]
Metrics now fully supported by IPDB. You can create, remove and change routes with metrics, it should work now.

Pls take into account that it is beta version — though covered with tests. But there can be some surprises. If so, ping me please, I will fix it asap.

**Comment by takaomag** [comment]
I tested the above codes and it works well.

Always thank you so much !

(Can I close this issue ?)

**Comment by svinota** [comment]
Yep, I close it since it looks to be done completely.

Thank you for heads-up — I didn't use route metrics, so w/o your request I wouldn't implement it, just being unaware :)
