### ISSUE TITLE
Unable to delete filter of clsact/ingress

### ISSUE THREAD

**Issue by jschwinger233** [svinota/pyroute2#928]
## Reproduce steps:

First let's create the clsact qdisc and a bpf filter.

```python
ipr.tc("add", "clsact", 1) # dev lo
ipr.tc(
    "add-filter",
    "bpf",
    1, # dev lo
    ":1",
    fd=func.fd,
    name=func.name,
    parent='ffff:fff2',
    classid=1,
    direct_action=True,
)
```

Then we can check the status:

```bash
$ tc filter show dev lo parent ffff:fff2
filter protocol all pref 49152 bpf chain 0 
filter protocol all pref 49152 bpf chain 0 handle 0x1 flowid :1 tc_pass direct-action not_in_hw id 329 tag 15858a412926acbb
```

However the consequent del-filter won't work:

```bash
ipr.tc("del-filter", "bpf", iface_idx, ':1', parent='ffff:fff2')
```

will raise error

```
Traceback (most recent call last):
  File "basic01-xdp-pass/tc_loader.bcc.py", line 45, in <module>
    ipr.tc("del-filter", "bpf", iface_idx, ':0', parent=parent)
  File "/usr/lib/python3/dist-packages/pyroute2/iproute/linux.py", line 1614, in tc
    return tuple(self.nlm_request(msg, msg_type=command, msg_flags=flags))
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 867, in nlm_request
    for msg in self.get(msg_seq=msg_seq,
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 379, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 704, in get
    raise msg['header']['error']
pyroute2.netlink.exceptions.NetlinkError: (2, 'No such file or directory')
```

I guess it's caused by `tcm_info` in the request of RTM_DELTFILTER, somehow the parameter is set to 0x300 instead of 0, but I don't know how to make the correction.

**Comment by jschwinger233** [comment]
Maybe [this issue](https://github.com/svinota/pyroute2/issues/745) is interrelated?

**Comment by svinota** [comment]
Thanks, working on it!

**Comment by svinota** [comment]
Issue confirmed, looking for the cause.

Sorry for inconvenience, and really thanks for the report — so far this part of API got significantly less attention from my side. Time to work closer with it.

**Comment by svinota** [comment]
The issue caused by incorrect tcm_info encoding.

To mitigate the error, you can use right now:
```python
ipr.tc("del-filter", "bpf", iface_idx, ':1', protocol=0, prio=0xc000, parent='ffff:fff2')
```
Corresponding code:
https://github.com/svinota/pyroute2/blob/4e739617e2a1f26ab5a02b4b91f52b23b64a6697/pyroute2.core/pr2modules/netlink/rtnl/tcmsg/sched_bpf.py#L23-L26

Tomorrow I'm to fix this. And https://github.com/svinota/pyroute2/issues/745 as well.

**Comment by svinota** [comment]
Looks like fixed:
https://github.com/svinota/pyroute2/blob/878bbc91da7aadba7903baa434d2868668046fe2/tests/test_linux/test_tc/test_bpf.py#L80-L107

The next release which will include this fix is to be tagged tomorrow
