### ISSUE TITLE
How to test master branch in an automated CI

### ISSUE THREAD

**Issue by ralonsoh** [svinota/pyroute2#939]
Hello Peter:

This is more a question than a bug. In OpenStack/Neutron we strongly depend on pyroute2. This is why we want to create a CI job using master branch, instead of the latest released version.

We have followed the manual to install the project from source. However, that works only when a tag version is checked, it doesn't work with master (untagged hash) branch. Do you have a way to do this?

Link: https://review.opendev.org/c/openstack/neutron/+/846288

Thank you in advance.

**Comment by svinota** [comment]
Yep, that's the task I started to work much more deeply on from my side as well

- [ ] one simple package (again, + pyroute2-minimal, but that's not relevant for Neutron)
- [ ] static version file ⇒ `pip install git+https` should work
- [ ] some tasks land here: https://github.com/users/svinota/projects/4 you can track it, and please don't hesitate **to create tasks for that topic**! It's important
- [ ] migrated tox ⇒ nox; if you will have — I will accept there any specific Neutron sessions as well; (CI against the master is running on a daily basis on my side, and we can have both sides tests)
- [ ] there is already a partly relevent test module: https://github.com/svinota/pyroute2/tree/master/tests/test_linux/test_integration , but
    - [ ] there will be more (eventlet)
    - [ ] it will migrate to a separate module, so it will not be needed to run all the functional tests to check the Neutron used code

I will elaborate more when I wake up back tonight. And commit some skeleton module.

**Comment by svinota** [comment]
Started `test_neutron` integration module, see e70fe8913ad7704d778a127248b8d939e125a434 , more tests on my side will follow.

Added nox session `build`, see 72ef6f19d567e1d79371bb1530bc21fdd27dcabc

Regarding the install — 
```bash
# 1. using pip
pip install git+https://github.com/svinota/pyroute2.git

# 2. using git
git clone https://github.com/svinota/pyroute2.git
cd pyroute2
make install
```

**Comment by svinota** [comment]
Another possible solution could be publishing nightly builds somewhere, and you could use them to install for the tests.

So tell me which option suits better, and we do this way.

**Comment by svinota** [comment]
Yep. The only disadvantage of `pip install git+https` is that `0.6.13` from there != `0.6.13` from pypi.

But this going to be fixed as well within one week max.

**Comment by elajkat** [comment]
Thanks for it, for our effort to have quick feedback with master pyroute2 it is good now

**Comment by svinota** [comment]
Ok, then I close the issue for now.
