### ISSUE TITLE
eventlet: lnst code failure

### ISSUE THREAD

**Issue by svinota** [svinota/pyroute2#96]
```
======================================================================
FAIL: test_lnst.TestLnst.test_imports
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/peet/Projects/pyroute2/tests/test_lnst.py", line 23, in test_imports
    assert issubclass(IPRSocket, socket.socket)
AssertionError
```

**Comment by svinota** [comment]
Related lnst issue: https://github.com/jpirko/lnst/issues/101

**Comment by anguslees** [comment]
Hrm, I don't have easy answers for this one.  Is it important that `IPRSocket` is a `socket.socket`, or only that it can be used in the place of one?  Specifically, it might be better to check that it has a `fileno()` method, since that will allow it to be used in `select()` and friends.

**Comment by svinota** [comment]
This particular one is already being tested by LNST guys

**Comment by svinota** [comment]
We have issue with the code, I will investigate it during the weekend. Please refer to the discussion at https://github.com/jpirko/lnst/issues/101

**Comment by svinota** [comment]
Saved the old architecture as the default, so nothing breaks LNST anymore.

At the same time it is possible to use the new way too. So let's treat it as «fixed».
