### ISSUE TITLE
eventlet: multiprocessing (used by netns) doesn't work with eventlet

### ISSUE THREAD

**Issue by anguslees** [svinota/pyroute2#99]
For what it's worth, multiprocessing doesn't work with eventlet.  This is really eventlet's bug, but the workaround is quite easy for pyroute2's limited use of multiprocessing (only `.Pipe` and `.Process`).

The issue is that `multiprocessing.Pipe` uses some C code internally to read from the communication socket, and this C code thus can't be patched by eventlet to use its GreenSocket class.

The fix is as easy as defining our own python replacement for multiprocessing.Connection.  This works for me with pyroute2.netns:

```python
import socket
import multiprocessing
import cPickle as pickle

class MyMpConnection(object):
    def __init__(self, sock):
        sock.setblocking(True)
        self.sock = sock
    def fileno(self):
        return self.sock.fileno()
    def send(self, obj):
       pickle.dump(obj, self, protocol=-1)
    def write(self, s):
        self.sock.sendall(s)
    def recv(self):
        return pickle.load(self)
    def read(self, n):
        return self.sock.recv(n)
    def readline(self):
        buf = b''
        c = None
        while c != '\n':
            c = self.sock.recv(1)
            buf += c
        return buf

def Pipe():
    s1, s2 = socket.socketpair()
    return (MyMpConnection(s1), MyMpConnection(s2))

# and then use Pipe() above rather than multiprocessing.Pipe.  multiprocessing.Process can be used unmodified.
```

Again, I'm only mentioning this here for completeness with other eventlet+pyroute2 work.  This is really an issue between multiprocessing and eventlet, and I'm fine if you wish to close this bug "will not fix".

**Comment by svinota** [comment]
Mmmmkay… Task queued. Since the usage of `multiprocessing.Pipe` is not a requirement, I believe, we can fix it somehow.

If it will help — I'm not sure there is a reasonable replacement for `multiprocessing.Process` in my case. But if it will work for you, why not.

I'm thinking, if it would be OK for you, if I will provide an easy interface to replace the pipe with some other transport — so I would not incorporate the code above, but instead would let you easily plug your pipe implementation in?

**Comment by svinota** [comment]
Please check this approach: https://github.com/svinota/pyroute2/commit/d9cc016817b92d721302077baeaf45f939f5c986

If it work for you, I would make the same for Pipe and Process.

Also, this solves the issue with LNST and others, in which case the substitution of the socket class breaks the 3rd party library functionality.

**Comment by svinota** [comment]
Implemented Pipe and Process overridable variables in the `pyroute2.common` module.

To use:

1. switch off autoimport in the pyroute2 root module::
    export PYROUTE2_NO_AUTOIMPORT="True"

2. override variables::
    from pyroute2 import common
    common.MpPipe = YourOwnClass
    common.MpProcess = YourOwnProcess

3. import whatever you want (remember, root imports don't work in that case)::
    from pyroute2.netns import NetNS

**Comment by svinota** [comment]
And even better approach (doesn't require any environment variables): https://github.com/svinota/pyroute2/commit/01589ce5bbd3b447cb5aa86daa68b7914709c43b

**Comment by svinota** [comment]
Being really generic and backward-compatible, this solution is merged to the master branch.

From now on you can substitute some base classes by `pyroute2.config`, refer to `examples/custom_socket_base.py`

**Comment by svinota** [comment]
Any news?

Since if it is not enough, I would try to provide something better, but I have to know, what to provide :)

**Comment by svinota** [comment]
Closing for now. If you think, the issue can be solved better, pls reopen.
